services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - know-agent-network
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - know-agent-network
    restart: always

networks:
  know-agent-network:
    driver: bridge