services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: know-agent-frontend
    ports:
      - "80:80"
    networks:
      - know-agent-network
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: know-agent-backend
    volumes:
      - ./etc/config-prod.yaml:/app/etc/config-prod.yaml
    # ports:
    #   - "8080:8080"
    networks:
      - know-agent-network
    restart: always

networks:
  know-agent-network:
    driver: bridge