// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package convert

import (
	"encoding/json"
	"time"

	datatypes "gorm.io/datatypes"

	chat "github.com/swiftbit/know-agent/api/chat"
	document "github.com/swiftbit/know-agent/api/document"
	knowledge "github.com/swiftbit/know-agent/api/knowledge"
	common "github.com/swiftbit/know-agent/common"
	aggregate "github.com/swiftbit/know-agent/internal/domain/chat/model/aggregate"
	entity "github.com/swiftbit/know-agent/internal/domain/chat/model/entity"
	vo "github.com/swiftbit/know-agent/internal/domain/chat/model/vo"
	aggregate1 "github.com/swiftbit/know-agent/internal/domain/document/model/aggregate"
	entity1 "github.com/swiftbit/know-agent/internal/domain/document/model/entity"
	vo1 "github.com/swiftbit/know-agent/internal/domain/document/model/vo"
	aggregate2 "github.com/swiftbit/know-agent/internal/domain/knowledge/model/aggregate"
	entity2 "github.com/swiftbit/know-agent/internal/domain/knowledge/model/entity"
	vo2 "github.com/swiftbit/know-agent/internal/domain/knowledge/model/vo"
	model "github.com/swiftbit/know-agent/internal/infrastructure/persistence/model"
)

func FromChatReq(source *chat.ChatReq) *vo.ChatCommand {
	var pVoChatCommand *vo.ChatCommand
	if source != nil {
		var voChatCommand vo.ChatCommand
		voChatCommand.Question = (*source).Question
		voChatCommand.ConversationId = (*source).ConversationId
		voChatCommand.ChatMode = (*source).ChatMode
		voChatCommand.SelectedDocumentId = StringToInt64((*source).SelectedDocumentId)
		voChatCommand.KnowledgeBaseSelectionMode = (*source).KnowledgeBaseSelectionMode
		voChatCommand.SelectedKnowledgeBaseIds = (*source).SelectedKnowledgeBaseIds
		pVoChatCommand = &voChatCommand
	}
	return pVoChatCommand
}
func ToChannelExecutionResp(source *vo.ChatChannelExecution) *chat.ChannelExecutionResp {
	var pChatChannelExecutionResp *chat.ChannelExecutionResp
	if source != nil {
		var chatChannelExecutionResp chat.ChannelExecutionResp
		chatChannelExecutionResp.ID = Int64ToString((*source).ID)
		chatChannelExecutionResp.ConversationId = (*source).ConversationId
		chatChannelExecutionResp.ExchangeId = Int64ToString((*source).ExchangeId)
		chatChannelExecutionResp.TraceId = (*source).TraceId
		chatChannelExecutionResp.SubQuestionIndex = (*source).SubQuestionIndex
		chatChannelExecutionResp.SubQuestion = (*source).SubQuestion
		chatChannelExecutionResp.ChannelType = (*source).ChannelType
		chatChannelExecutionResp.ExecutionState = (*source).ExecutionState
		chatChannelExecutionResp.StartTime = TimeToStringMs((*source).StartTime)
		chatChannelExecutionResp.EndTime = TimeToStringMs((*source).EndTime)
		chatChannelExecutionResp.DurationMs = (*source).DurationMs
		chatChannelExecutionResp.RecalledCount = (*source).RecalledCount
		chatChannelExecutionResp.AcceptedCount = (*source).AcceptedCount
		chatChannelExecutionResp.FinalSelectedCount = (*source).FinalSelectedCount
		chatChannelExecutionResp.AvgScore = (*source).AvgScore
		chatChannelExecutionResp.MaxScore = (*source).MaxScore
		chatChannelExecutionResp.MinScore = (*source).MinScore
		chatChannelExecutionResp.ErrorMessage = (*source).ErrorMessage
		chatChannelExecutionResp.CreateTime = TimeToString((*source).CreateTime)
		pChatChannelExecutionResp = &chatChannelExecutionResp
	}
	return pChatChannelExecutionResp
}
func ToChannelExecutionRespList(source []*vo.ChatChannelExecution) []*chat.ChannelExecutionResp {
	var pChatChannelExecutionRespList []*chat.ChannelExecutionResp
	if source != nil {
		pChatChannelExecutionRespList = make([]*chat.ChannelExecutionResp, len(source))
		for i := 0; i < len(source); i++ {
			pChatChannelExecutionRespList[i] = ToChannelExecutionResp(source[i])
		}
	}
	return pChatChannelExecutionRespList
}
func ToChatChannelExecutionModel(source *vo.ChatChannelExecution) *model.ChatChannelExecution {
	var pModelChatChannelExecution *model.ChatChannelExecution
	if source != nil {
		var modelChatChannelExecution model.ChatChannelExecution
		modelChatChannelExecution.Model = voChatChannelExecutionToCommonModel((*source))
		modelChatChannelExecution.ConversationId = (*source).ConversationId
		modelChatChannelExecution.ExchangeId = (*source).ExchangeId
		modelChatChannelExecution.TraceId = (*source).TraceId
		modelChatChannelExecution.SubQuestionIndex = (*source).SubQuestionIndex
		modelChatChannelExecution.SubQuestion = (*source).SubQuestion
		modelChatChannelExecution.ChannelType = (*source).ChannelType
		modelChatChannelExecution.ExecutionState = (*source).ExecutionState
		modelChatChannelExecution.StartTime = timeTimeToTimeTime((*source).StartTime)
		modelChatChannelExecution.EndTime = timeTimeToTimeTime((*source).EndTime)
		modelChatChannelExecution.DurationMs = (*source).DurationMs
		modelChatChannelExecution.RecalledCount = (*source).RecalledCount
		modelChatChannelExecution.AcceptedCount = (*source).AcceptedCount
		modelChatChannelExecution.FinalSelectedCount = (*source).FinalSelectedCount
		modelChatChannelExecution.AvgScore = (*source).AvgScore
		modelChatChannelExecution.MaxScore = (*source).MaxScore
		modelChatChannelExecution.MinScore = (*source).MinScore
		modelChatChannelExecution.ConfigSnapshot = (*source).ConfigSnapshot
		modelChatChannelExecution.ErrorMessage = (*source).ErrorMessage
		pModelChatChannelExecution = &modelChatChannelExecution
	}
	return pModelChatChannelExecution
}
func ToChatChannelExecutionModelList(source []*vo.ChatChannelExecution) []*model.ChatChannelExecution {
	var pModelChatChannelExecutionList []*model.ChatChannelExecution
	if source != nil {
		pModelChatChannelExecutionList = make([]*model.ChatChannelExecution, len(source))
		for i := 0; i < len(source); i++ {
			pModelChatChannelExecutionList[i] = ToChatChannelExecutionModel(source[i])
		}
	}
	return pModelChatChannelExecutionList
}
func ToChatDialogueModel(source *entity.ChatDialogue) *model.ChatDialogue {
	var pModelChatDialogue *model.ChatDialogue
	if source != nil {
		var modelChatDialogue model.ChatDialogue
		modelChatDialogue.Model = entityChatDialogueToCommonModel((*source))
		modelChatDialogue.ConversationId = (*source).ConversationId
		modelChatDialogue.SessionStatus = (*source).SessionStatus
		modelChatDialogue.ChatMode = (*source).ChatMode
		modelChatDialogue.SelectedDocumentId = (*source).SelectedDocumentId
		modelChatDialogue.SelectedDocumentName = (*source).SelectedDocumentName
		modelChatDialogue.KnowledgeBaseSelectionMode = (*source).KnowledgeBaseSelectionMode
		modelChatDialogue.SelectedKnowledgeBaseIdsJson = (*source).SelectedKnowledgeBaseIdsJson
		modelChatDialogue.SelectedKnowledgeBaseNamesJson = (*source).SelectedKnowledgeBaseNamesJson
		pModelChatDialogue = &modelChatDialogue
	}
	return pModelChatDialogue
}
func ToChatExchangeModel(source *entity.ChatExchange) *model.ChatExchange {
	var pModelChatExchange *model.ChatExchange
	if source != nil {
		var modelChatExchange model.ChatExchange
		modelChatExchange.Model = entityChatExchangeToCommonModel((*source))
		modelChatExchange.ConversationId = (*source).ConversationId
		modelChatExchange.Question = (*source).Question
		modelChatExchange.Answer = (*source).Answer
		modelChatExchange.TurnStatus = (*source).TurnStatus
		modelChatExchange.ThinkingSteps = commonJSONArrayToCommonJSONArray((*source).ThinkingSteps)
		modelChatExchange.References = commonJSONArrayToCommonJSONArray((*source).References)
		modelChatExchange.Recommendations = commonJSONArrayToCommonJSONArray((*source).Recommendations)
		modelChatExchange.UsedTools = commonJSONArrayToCommonJSONArray((*source).UsedTools)
		modelChatExchange.DebugTrace = (*source).DebugTrace
		modelChatExchange.ErrorMessage = (*source).ErrorMessage
		modelChatExchange.FirstResponseTimeMs = (*source).FirstResponseTimeMs
		modelChatExchange.TotalResponseTimeMs = (*source).TotalResponseTimeMs
		modelChatExchange.KnowledgeBaseSelectionMode = (*source).KnowledgeBaseSelectionMode
		modelChatExchange.SelectedKnowledgeBaseIdsJson = (*source).SelectedKnowledgeBaseIdsJson
		modelChatExchange.SelectedKnowledgeBaseNamesJson = (*source).SelectedKnowledgeBaseNamesJson
		modelChatExchange.RetrievalConfigSnapshot = (*source).RetrievalConfigSnapshot
		pModelChatExchange = &modelChatExchange
	}
	return pModelChatExchange
}
func ToChatExchangeTraceStageModel(source *entity.ChatExchangeTraceStage) *model.ChatExchangeTraceStage {
	var pModelChatExchangeTraceStage *model.ChatExchangeTraceStage
	if source != nil {
		var modelChatExchangeTraceStage model.ChatExchangeTraceStage
		modelChatExchangeTraceStage.Model = entityChatExchangeTraceStageToCommonModel((*source))
		modelChatExchangeTraceStage.ConversationId = (*source).ConversationId
		modelChatExchangeTraceStage.ExchangeId = (*source).ExchangeId
		modelChatExchangeTraceStage.TraceId = (*source).TraceId
		modelChatExchangeTraceStage.StageCode = (*source).StageCode
		modelChatExchangeTraceStage.StageName = (*source).StageName
		modelChatExchangeTraceStage.StageOrder = (*source).StageOrder
		modelChatExchangeTraceStage.StageLevel = (*source).StageLevel
		modelChatExchangeTraceStage.ParentStageId = (*source).ParentStageId
		modelChatExchangeTraceStage.ExecutionMode = (*source).ExecutionMode
		modelChatExchangeTraceStage.StageState = (*source).StageState
		modelChatExchangeTraceStage.StartTime = (*source).StartTime
		modelChatExchangeTraceStage.EndTime = (*source).EndTime
		modelChatExchangeTraceStage.DurationMs = (*source).DurationMs
		modelChatExchangeTraceStage.SummaryText = (*source).SummaryText
		modelChatExchangeTraceStage.ErrorMessage = (*source).ErrorMessage
		modelChatExchangeTraceStage.SnapshotJson = (*source).SnapshotJson
		pModelChatExchangeTraceStage = &modelChatExchangeTraceStage
	}
	return pModelChatExchangeTraceStage
}
func ToChatMemorySummaryModel(source *entity.ChatMemorySummary) *model.ChatMemorySummary {
	var pModelChatMemorySummary *model.ChatMemorySummary
	if source != nil {
		var modelChatMemorySummary model.ChatMemorySummary
		modelChatMemorySummary.Model = entityChatMemorySummaryToCommonModel((*source))
		modelChatMemorySummary.ConversationId = (*source).ConversationId
		modelChatMemorySummary.CoveredExchangeId = (*source).CoveredExchangeId
		modelChatMemorySummary.CoveredExchangeCount = (*source).CoveredExchangeCount
		modelChatMemorySummary.CompressionCount = (*source).CompressionCount
		modelChatMemorySummary.SummaryVersion = (*source).SummaryVersion
		modelChatMemorySummary.SummaryText = (*source).SummaryText
		modelChatMemorySummary.SummaryJson = (*source).SummaryJson
		modelChatMemorySummary.LastSourceUpdateTime = timeTimeToTimeTime((*source).LastSourceUpdateTime)
		pModelChatMemorySummary = &modelChatMemorySummary
	}
	return pModelChatMemorySummary
}
func ToChatRetrievalResultModel(source *vo.ChatRetrievalResult) *model.ChatRetrievalResult {
	var pModelChatRetrievalResult *model.ChatRetrievalResult
	if source != nil {
		var modelChatRetrievalResult model.ChatRetrievalResult
		modelChatRetrievalResult.Model = voChatRetrievalResultToCommonModel((*source))
		modelChatRetrievalResult.ConversationId = (*source).ConversationId
		modelChatRetrievalResult.ExchangeId = (*source).ExchangeId
		modelChatRetrievalResult.TraceId = (*source).TraceId
		modelChatRetrievalResult.SubQuestionIndex = (*source).SubQuestionIndex
		modelChatRetrievalResult.SubQuestion = (*source).SubQuestion
		modelChatRetrievalResult.ChannelType = (*source).ChannelType
		modelChatRetrievalResult.ChannelRank = (*source).ChannelRank
		modelChatRetrievalResult.RrfRank = (*source).RrfRank
		modelChatRetrievalResult.FinalRank = (*source).FinalRank
		modelChatRetrievalResult.OriginalScore = (*source).OriginalScore
		modelChatRetrievalResult.RrfScore = (*source).RrfScore
		modelChatRetrievalResult.RerankScore = (*source).RerankScore
		modelChatRetrievalResult.GatePassed = (*source).GatePassed
		modelChatRetrievalResult.IsElevated = (*source).IsElevated
		modelChatRetrievalResult.IsSelected = (*source).IsSelected
		modelChatRetrievalResult.SelectionReason = (*source).SelectionReason
		modelChatRetrievalResult.DocumentId = (*source).DocumentId
		modelChatRetrievalResult.DocumentName = (*source).DocumentName
		modelChatRetrievalResult.ChunkId = (*source).ChunkId
		modelChatRetrievalResult.ChunkNo = (*source).ChunkNo
		modelChatRetrievalResult.ParentBlockId = (*source).ParentBlockId
		modelChatRetrievalResult.ParentBlockNo = (*source).ParentBlockNo
		modelChatRetrievalResult.SectionPath = (*source).SectionPath
		modelChatRetrievalResult.ChunkTextPreview = (*source).ChunkTextPreview
		modelChatRetrievalResult.ChunkCharCount = (*source).ChunkCharCount
		pModelChatRetrievalResult = &modelChatRetrievalResult
	}
	return pModelChatRetrievalResult
}
func ToChatRetrievalResultModelList(source []*vo.ChatRetrievalResult) []*model.ChatRetrievalResult {
	var pModelChatRetrievalResultList []*model.ChatRetrievalResult
	if source != nil {
		pModelChatRetrievalResultList = make([]*model.ChatRetrievalResult, len(source))
		for i := 0; i < len(source); i++ {
			pModelChatRetrievalResultList[i] = ToChatRetrievalResultModel(source[i])
		}
	}
	return pModelChatRetrievalResultList
}
func ToConversationExchange(source *entity.ChatExchange) *chat.ConversationExchange {
	var pChatConversationExchange *chat.ConversationExchange
	if source != nil {
		var chatConversationExchange chat.ConversationExchange
		chatConversationExchange.ID = Int64ToString((*source).ID)
		chatConversationExchange.Question = (*source).Question
		chatConversationExchange.Answer = (*source).Answer
		chatConversationExchange.ThinkingSteps = JsonArrayToStringSlice((*source).ThinkingSteps)
		chatConversationExchange.References = JsonArrayToSearchReferences((*source).References)
		chatConversationExchange.Recommendations = JsonArrayToStringSlice((*source).Recommendations)
		chatConversationExchange.UsedTools = JsonArrayToStringSlice((*source).UsedTools)
		chatConversationExchange.DebugTrace = ToChatDebugTrace((*source).DebugTrace)
		chatConversationExchange.TurnStatus = (*source).TurnStatus
		chatConversationExchange.ErrorMessage = (*source).ErrorMessage
		chatConversationExchange.FirstResponseTimeMs = (*source).FirstResponseTimeMs
		chatConversationExchange.TotalResponseTimeMs = (*source).TotalResponseTimeMs
		chatConversationExchange.CreateTime = TimeToString((*source).CreateTime)
		chatConversationExchange.UpdateTime = TimeToString((*source).UpdateTime)
		pChatConversationExchange = &chatConversationExchange
	}
	return pChatConversationExchange
}
func ToConversationMemorySummaryResp(source *entity.ChatMemorySummary) *chat.ConversationMemorySummaryResp {
	var pChatConversationMemorySummaryResp *chat.ConversationMemorySummaryResp
	if source != nil {
		var chatConversationMemorySummaryResp chat.ConversationMemorySummaryResp
		chatConversationMemorySummaryResp.ConversationId = (*source).ConversationId
		chatConversationMemorySummaryResp.IsCompressed = (*source).IsCompressed
		chatConversationMemorySummaryResp.CoveredExchangeId = Int64ToString((*source).CoveredExchangeId)
		chatConversationMemorySummaryResp.CoveredExchangeCount = (*source).CoveredExchangeCount
		chatConversationMemorySummaryResp.CompressionCount = (*source).CompressionCount
		chatConversationMemorySummaryResp.SummaryVersion = (*source).SummaryVersion
		chatConversationMemorySummaryResp.SummaryText = (*source).SummaryText
		chatConversationMemorySummaryResp.SummaryPayload = pVoConversationSummaryToPChatSummaryPayload((*source).SummaryPayload)
		chatConversationMemorySummaryResp.LastSourceUpdateTime = TimeToString((*source).LastSourceUpdateTime)
		chatConversationMemorySummaryResp.UpdateTime = TimeToStringMs((*source).UpdateTime)
		pChatConversationMemorySummaryResp = &chatConversationMemorySummaryResp
	}
	return pChatConversationMemorySummaryResp
}
func ToConversationResetResp(source *vo.ConversationReset) *chat.ConversationResetResp {
	var pChatConversationResetResp *chat.ConversationResetResp
	if source != nil {
		var chatConversationResetResp chat.ConversationResetResp
		chatConversationResetResp.ConversationId = (*source).ConversationId
		chatConversationResetResp.RemovedDialogueCount = (*source).RemovedDialogueCount
		chatConversationResetResp.RemovedExchangeCount = (*source).RemovedExchangeCount
		chatConversationResetResp.RemovedCheckpointCount = (*source).RemovedCheckpointCount
		chatConversationResetResp.Message = (*source).Message
		pChatConversationResetResp = &chatConversationResetResp
	}
	return pChatConversationResetResp
}
func ToConversationSessionResp(source *aggregate.ConversationArchiveRecord) *chat.ConversationSessionResp {
	var pChatConversationSessionResp *chat.ConversationSessionResp
	if source != nil {
		var chatConversationSessionResp chat.ConversationSessionResp
		chatConversationSessionResp.ConversationId = (*source).ConversationId
		chatConversationSessionResp.Running = (*source).Running
		chatConversationSessionResp.CheckpointCount = (*source).CheckpointCount
		chatConversationSessionResp.MessageCount = (*source).MessageCount
		chatConversationSessionResp.LatestUserMessage = (*source).LatestUserMessage
		chatConversationSessionResp.LatestAssistantMessage = (*source).LatestAssistantMessage
		chatConversationSessionResp.LatestExchangeId = Int64ToString((*source).LatestExchangeId)
		chatConversationSessionResp.LatestTurnStatus = (*source).LatestTurnStatus
		chatConversationSessionResp.LatestTurnErrorMessage = (*source).LatestTurnErrorMessage
		chatConversationSessionResp.ChatMode = ToChatQueryModeName((*source).ChatMode)
		chatConversationSessionResp.SelectedDocumentId = Int64ToString((*source).SelectedDocumentId)
		chatConversationSessionResp.SelectedDocumentName = (*source).SelectedDocumentName
		chatConversationSessionResp.CreatedTime = TimeToString((*source).CreatedTime)
		chatConversationSessionResp.UpdatedTime = TimeToString((*source).UpdatedTime)
		if (*source).Exchanges != nil {
			chatConversationSessionResp.Exchanges = make([]*chat.ConversationExchange, len((*source).Exchanges))
			for i := 0; i < len((*source).Exchanges); i++ {
				chatConversationSessionResp.Exchanges[i] = ToConversationExchange((*source).Exchanges[i])
			}
		}
		chatConversationSessionResp.MemorySummary = ToConversationMemorySummaryResp((*source).MemorySummary)
		pChatConversationSessionResp = &chatConversationSessionResp
	}
	return pChatConversationSessionResp
}
func ToConversationSessionRespList(source []*aggregate.ConversationArchiveRecord) []*chat.ConversationSessionResp {
	var pChatConversationSessionRespList []*chat.ConversationSessionResp
	if source != nil {
		pChatConversationSessionRespList = make([]*chat.ConversationSessionResp, len(source))
		for i := 0; i < len(source); i++ {
			pChatConversationSessionRespList[i] = ToConversationSessionResp(source[i])
		}
	}
	return pChatConversationSessionRespList
}
func ToConversationStageTraces(source []*entity.ChatExchangeTraceStage) []*chat.ConversationTraceStage {
	var pChatConversationTraceStageList []*chat.ConversationTraceStage
	if source != nil {
		pChatConversationTraceStageList = make([]*chat.ConversationTraceStage, len(source))
		for i := 0; i < len(source); i++ {
			pChatConversationTraceStageList[i] = pEntityChatExchangeTraceStageToPChatConversationTraceStage(source[i])
		}
	}
	return pChatConversationTraceStageList
}
func ToRetrievalResultRespList(source []*vo.ChatRetrievalResult) []*chat.RetrievalResultResp {
	var pChatRetrievalResultRespList []*chat.RetrievalResultResp
	if source != nil {
		pChatRetrievalResultRespList = make([]*chat.RetrievalResultResp, len(source))
		for i := 0; i < len(source); i++ {
			pChatRetrievalResultRespList[i] = pVoChatRetrievalResultToPChatRetrievalResultResp(source[i])
		}
	}
	return pChatRetrievalResultRespList
}
func commonJSONArrayToCommonJSONArray(source common.JSONArray) common.JSONArray {
	return source
}
func entityChatDialogueToCommonModel(source entity.ChatDialogue) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityChatExchangeToCommonModel(source entity.ChatExchange) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityChatExchangeTraceStageToCommonModel(source entity.ChatExchangeTraceStage) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityChatMemorySummaryToCommonModel(source entity.ChatMemorySummary) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func pEntityChatExchangeTraceStageToPChatConversationTraceStage(source *entity.ChatExchangeTraceStage) *chat.ConversationTraceStage {
	var pChatConversationTraceStage *chat.ConversationTraceStage
	if source != nil {
		var chatConversationTraceStage chat.ConversationTraceStage
		chatConversationTraceStage.ID = Int64ToString((*source).ID)
		chatConversationTraceStage.TraceId = (*source).TraceId
		chatConversationTraceStage.StageCode = (*source).StageCode
		chatConversationTraceStage.StageName = (*source).StageName
		chatConversationTraceStage.StageOrder = (*source).StageOrder
		chatConversationTraceStage.StageLevel = (*source).StageLevel
		chatConversationTraceStage.ParentStageId = Int64ToString((*source).ParentStageId)
		chatConversationTraceStage.ExecutionMode = (*source).ExecutionMode
		chatConversationTraceStage.StageState = (*source).StageState
		chatConversationTraceStage.StartTime = pTimeTimeToString((*source).StartTime)
		chatConversationTraceStage.EndTime = pTimeTimeToString((*source).EndTime)
		chatConversationTraceStage.DurationMs = (*source).DurationMs
		if (*source).SummaryText != nil {
			chatConversationTraceStage.SummaryText = *(*source).SummaryText
		}
		if (*source).ErrorMessage != nil {
			chatConversationTraceStage.ErrorMessage = *(*source).ErrorMessage
		}
		if (*source).SnapshotJson != nil {
			chatConversationTraceStage.SnapshotJson = *(*source).SnapshotJson
		}
		pChatConversationTraceStage = &chatConversationTraceStage
	}
	return pChatConversationTraceStage
}
func pTimeTimeToString(source *time.Time) string {
	var xstring string
	if source != nil {
		xstring = TimeToString((*source))
	}
	return xstring
}
func pVoChatRetrievalResultToPChatRetrievalResultResp(source *vo.ChatRetrievalResult) *chat.RetrievalResultResp {
	var pChatRetrievalResultResp *chat.RetrievalResultResp
	if source != nil {
		var chatRetrievalResultResp chat.RetrievalResultResp
		chatRetrievalResultResp.ID = Int64ToString((*source).ID)
		chatRetrievalResultResp.ConversationId = (*source).ConversationId
		chatRetrievalResultResp.ExchangeId = Int64ToString((*source).ExchangeId)
		chatRetrievalResultResp.TraceId = (*source).TraceId
		chatRetrievalResultResp.SubQuestionIndex = (*source).SubQuestionIndex
		chatRetrievalResultResp.SubQuestion = (*source).SubQuestion
		chatRetrievalResultResp.ChannelType = (*source).ChannelType
		chatRetrievalResultResp.ChannelRank = (*source).ChannelRank
		chatRetrievalResultResp.RrfRank = (*source).RrfRank
		chatRetrievalResultResp.FinalRank = (*source).FinalRank
		chatRetrievalResultResp.OriginalScore = (*source).OriginalScore
		chatRetrievalResultResp.RrfScore = (*source).RrfScore
		chatRetrievalResultResp.RerankScore = (*source).RerankScore
		chatRetrievalResultResp.GatePassed = (*source).GatePassed
		chatRetrievalResultResp.IsElevated = (*source).IsElevated
		chatRetrievalResultResp.IsSelected = (*source).IsSelected
		chatRetrievalResultResp.SelectionReason = (*source).SelectionReason
		chatRetrievalResultResp.DocumentId = Int64ToString((*source).DocumentId)
		chatRetrievalResultResp.DocumentName = (*source).DocumentName
		chatRetrievalResultResp.ChunkId = Int64ToString((*source).ChunkId)
		chatRetrievalResultResp.ChunkNo = (*source).ChunkNo
		chatRetrievalResultResp.ParentBlockId = Int64ToString((*source).ParentBlockId)
		chatRetrievalResultResp.ParentBlockNo = (*source).ParentBlockNo
		chatRetrievalResultResp.SectionPath = (*source).SectionPath
		chatRetrievalResultResp.ChunkTextPreview = (*source).ChunkTextPreview
		chatRetrievalResultResp.ChunkCharCount = (*source).ChunkCharCount
		chatRetrievalResultResp.CreateTime = TimeToString((*source).CreateTime)
		pChatRetrievalResultResp = &chatRetrievalResultResp
	}
	return pChatRetrievalResultResp
}
func pVoConversationSummaryToPChatSummaryPayload(source *vo.ConversationSummary) *chat.SummaryPayload {
	var pChatSummaryPayload *chat.SummaryPayload
	if source != nil {
		var chatSummaryPayload chat.SummaryPayload
		chatSummaryPayload.Summary = (*source).Summary
		chatSummaryPayload.ConversationGoal = (*source).ConversationGoal
		chatSummaryPayload.StableFacts = (*source).StableFacts
		chatSummaryPayload.UserPreferences = (*source).UserPreferences
		chatSummaryPayload.ResolvedPoints = (*source).ResolvedPoints
		chatSummaryPayload.PendingQuestions = (*source).PendingQuestions
		chatSummaryPayload.RetrievalHints = (*source).RetrievalHints
		pChatSummaryPayload = &chatSummaryPayload
	}
	return pChatSummaryPayload
}
func timeTimeToTimeTime(source time.Time) time.Time {
	return source
}
func voChatChannelExecutionToCommonModel(source vo.ChatChannelExecution) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func voChatRetrievalResultToCommonModel(source vo.ChatRetrievalResult) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func FromConfirmStrategyReq(source *document.ConfirmStrategyReq) *vo1.DocumentStrategyConfirmCmd {
	var pVoDocumentStrategyConfirmCmd *vo1.DocumentStrategyConfirmCmd
	if source != nil {
		var voDocumentStrategyConfirmCmd vo1.DocumentStrategyConfirmCmd
		voDocumentStrategyConfirmCmd.DocumentId = StringToInt64((*source).DocumentId)
		voDocumentStrategyConfirmCmd.BasePlanId = StringToInt64((*source).BasePlanId)
		voDocumentStrategyConfirmCmd.OperatorId = StringToInt64((*source).OperatorId)
		voDocumentStrategyConfirmCmd.AdjustNote = (*source).AdjustNote
		if (*source).ParentSteps != nil {
			voDocumentStrategyConfirmCmd.ParentSteps = make([]*vo1.DocumentStrategyStepItem, len((*source).ParentSteps))
			for i := 0; i < len((*source).ParentSteps); i++ {
				voDocumentStrategyConfirmCmd.ParentSteps[i] = pDocumentStrategyStepItemToPVoDocumentStrategyStepItem((*source).ParentSteps[i])
			}
		}
		if (*source).ChildSteps != nil {
			voDocumentStrategyConfirmCmd.ChildSteps = make([]*vo1.DocumentStrategyStepItem, len((*source).ChildSteps))
			for j := 0; j < len((*source).ChildSteps); j++ {
				voDocumentStrategyConfirmCmd.ChildSteps[j] = pDocumentStrategyStepItemToPVoDocumentStrategyStepItem((*source).ChildSteps[j])
			}
		}
		pVoDocumentStrategyConfirmCmd = &voDocumentStrategyConfirmCmd
	}
	return pVoDocumentStrategyConfirmCmd
}
func FromUploadDocumentReq(source *document.UploadDocumentReq) *entity1.Document {
	var pEntityDocument *entity1.Document
	if source != nil {
		var entityDocument entity1.Document
		entityDocument.DocumentName = (*source).DocumentName
		entityDocument.KnowledgeBaseId = StringToInt64((*source).KnowledgeBaseId)
		entityDocument.OperatorId = StringToInt64((*source).OperatorId)
		pEntityDocument = &entityDocument
	}
	return pEntityDocument
}
func ToBuildIndexResp(source *vo1.DocumentIndexBuild) *document.BuildIndexResp {
	var pDocumentBuildIndexResp *document.BuildIndexResp
	if source != nil {
		var documentBuildIndexResp document.BuildIndexResp
		documentBuildIndexResp.TaskId = Int64ToString((*source).TaskId)
		documentBuildIndexResp.DocumentId = Int64ToString((*source).DocumentId)
		documentBuildIndexResp.TaskType = (*source).TaskType
		documentBuildIndexResp.TaskTypeName = (*source).TaskTypeName
		documentBuildIndexResp.TaskStatus = (*source).TaskStatus
		documentBuildIndexResp.TaskStatusName = (*source).TaskStatusName
		documentBuildIndexResp.IndexStatus = (*source).IndexStatus
		documentBuildIndexResp.IndexStatusName = (*source).IndexStatusName
		pDocumentBuildIndexResp = &documentBuildIndexResp
	}
	return pDocumentBuildIndexResp
}
func ToConfirmStrategyResp(source *entity1.DocumentStrategyPlan) *document.ConfirmStrategyResp {
	var pDocumentConfirmStrategyResp *document.ConfirmStrategyResp
	if source != nil {
		var documentConfirmStrategyResp document.ConfirmStrategyResp
		documentConfirmStrategyResp.ID = Int64ToString((*source).ID)
		documentConfirmStrategyResp.DocumentId = Int64ToString((*source).DocumentId)
		documentConfirmStrategyResp.PlanVersion = (*source).PlanVersion
		documentConfirmStrategyResp.Normalized = (*source).Normalized
		documentConfirmStrategyResp.ParentPipeline = pEntityDocumentStrategyPipelineToPDocumentDocumentStrategyPipeline((*source).ParentPipeline)
		documentConfirmStrategyResp.ChildPipeline = pEntityDocumentStrategyPipelineToPDocumentDocumentStrategyPipeline((*source).ChildPipeline)
		pDocumentConfirmStrategyResp = &documentConfirmStrategyResp
	}
	return pDocumentConfirmStrategyResp
}
func ToDocumentBlockModel(source *entity1.DocumentBlock) *model.DocumentBlock {
	var pModelDocumentBlock *model.DocumentBlock
	if source != nil {
		var modelDocumentBlock model.DocumentBlock
		modelDocumentBlock.Model = entityDocumentBlockToCommonModel((*source))
		modelDocumentBlock.DocumentId = (*source).DocumentId
		modelDocumentBlock.TaskId = (*source).TaskId
		modelDocumentBlock.BlockNo = (*source).BlockNo
		modelDocumentBlock.BlockType = (*source).BlockType
		modelDocumentBlock.ParentBlockId = (*source).ParentBlockId
		modelDocumentBlock.SectionPath = (*source).SectionPath
		modelDocumentBlock.CanonicalPath = (*source).CanonicalPath
		modelDocumentBlock.PageNo = (*source).PageNo
		modelDocumentBlock.PageRange = (*source).PageRange
		modelDocumentBlock.BboxJson = (*source).BboxJson
		modelDocumentBlock.Text = (*source).Text
		modelDocumentBlock.ContentWithWeight = (*source).ContentWithWeight
		modelDocumentBlock.TableHTML = (*source).TableHTML
		modelDocumentBlock.ImageObjectName = (*source).ImageObjectName
		modelDocumentBlock.ImageCaption = (*source).ImageCaption
		modelDocumentBlock.MetadataJson = (*source).MetadataJson
		pModelDocumentBlock = &modelDocumentBlock
	}
	return pModelDocumentBlock
}
func ToDocumentBlockModelList(source []*entity1.DocumentBlock) []*model.DocumentBlock {
	var pModelDocumentBlockList []*model.DocumentBlock
	if source != nil {
		pModelDocumentBlockList = make([]*model.DocumentBlock, len(source))
		for i := 0; i < len(source); i++ {
			pModelDocumentBlockList[i] = ToDocumentBlockModel(source[i])
		}
	}
	return pModelDocumentBlockList
}
func ToDocumentChunkItemList(source []*entity1.DocumentChunk) []*document.DocumentChunkItem {
	var pDocumentDocumentChunkItemList []*document.DocumentChunkItem
	if source != nil {
		pDocumentDocumentChunkItemList = make([]*document.DocumentChunkItem, len(source))
		for i := 0; i < len(source); i++ {
			pDocumentDocumentChunkItemList[i] = pEntityDocumentChunkToPDocumentDocumentChunkItem(source[i])
		}
	}
	return pDocumentDocumentChunkItemList
}
func ToDocumentChunkModel(source *entity1.DocumentChunk) *model.DocumentChunk {
	var pModelDocumentChunk *model.DocumentChunk
	if source != nil {
		var modelDocumentChunk model.DocumentChunk
		modelDocumentChunk.Model = entityDocumentChunkToCommonModel((*source))
		modelDocumentChunk.DocumentId = (*source).DocumentId
		modelDocumentChunk.TaskId = (*source).TaskId
		modelDocumentChunk.PlanId = (*source).PlanId
		modelDocumentChunk.ParentChunkId = (*source).ParentChunkId
		modelDocumentChunk.ChunkNo = (*source).ChunkNo
		modelDocumentChunk.SourceType = (*source).SourceType
		modelDocumentChunk.SectionPath = (*source).SectionPath
		modelDocumentChunk.StructureNodeId = (*source).StructureNodeId
		modelDocumentChunk.StructureNodeType = (*source).StructureNodeType
		modelDocumentChunk.CanonicalPath = (*source).CanonicalPath
		modelDocumentChunk.ItemIndex = (*source).ItemIndex
		modelDocumentChunk.ChunkText = (*source).ChunkText
		modelDocumentChunk.CharCount = (*source).CharCount
		modelDocumentChunk.TokenCount = (*source).TokenCount
		modelDocumentChunk.VectorStatus = (*source).VectorStatus
		modelDocumentChunk.VectorStoreType = (*source).VectorStoreType
		modelDocumentChunk.VectorId = (*source).VectorId
		modelDocumentChunk.ContentWithWeight = (*source).ContentWithWeight
		modelDocumentChunk.ChunkType = (*source).ChunkType
		modelDocumentChunk.Title = (*source).Title
		modelDocumentChunk.Keywords = (*source).Keywords
		modelDocumentChunk.Questions = (*source).Questions
		modelDocumentChunk.PageNo = (*source).PageNo
		modelDocumentChunk.PageRange = (*source).PageRange
		modelDocumentChunk.BboxJson = (*source).BboxJson
		modelDocumentChunk.SourceBlockIds = (*source).SourceBlockIds
		pModelDocumentChunk = &modelDocumentChunk
	}
	return pModelDocumentChunk
}
func ToDocumentChunkModelList(source []*entity1.DocumentChunk) []*model.DocumentChunk {
	var pModelDocumentChunkList []*model.DocumentChunk
	if source != nil {
		pModelDocumentChunkList = make([]*model.DocumentChunk, len(source))
		for i := 0; i < len(source); i++ {
			pModelDocumentChunkList[i] = ToDocumentChunkModel(source[i])
		}
	}
	return pModelDocumentChunkList
}
func ToDocumentDetailResp(source *entity1.Document) *document.DocumentDetailResp {
	var pDocumentDocumentDetailResp *document.DocumentDetailResp
	if source != nil {
		var documentDocumentDetailResp document.DocumentDetailResp
		documentDocumentDetailResp.ID = Int64ToString((*source).ID)
		documentDocumentDetailResp.DocumentName = (*source).DocumentName
		documentDocumentDetailResp.OriginalFileName = (*source).OriginalFileName
		documentDocumentDetailResp.FileType = (*source).FileType
		documentDocumentDetailResp.FileTypeName = (*source).FileTypeName
		documentDocumentDetailResp.FileSize = (*source).FileSize
		documentDocumentDetailResp.CharCount = (*source).CharCount
		documentDocumentDetailResp.TokenCount = (*source).TokenCount
		documentDocumentDetailResp.ParseStatus = (*source).ParseStatus
		documentDocumentDetailResp.ParseStatusName = (*source).ParseStatusName
		documentDocumentDetailResp.StrategyStatus = (*source).StrategyStatus
		documentDocumentDetailResp.StrategyStatusName = (*source).StrategyStatusName
		documentDocumentDetailResp.IndexStatus = (*source).IndexStatus
		documentDocumentDetailResp.IndexStatusName = (*source).IndexStatusName
		if (*source).ParseErrorMsg != nil {
			documentDocumentDetailResp.ParseErrorMsg = *(*source).ParseErrorMsg
		}
		documentDocumentDetailResp.CurrentPlanId = Int64ToString((*source).CurrentPlanId)
		documentDocumentDetailResp.LastIndexTaskId = Int64ToString((*source).LastIndexTaskId)
		documentDocumentDetailResp.LatestTaskId = Int64ToString((*source).LatestTaskId)
		documentDocumentDetailResp.LatestTaskType = (*source).LatestTaskType
		documentDocumentDetailResp.LatestTaskTypeName = (*source).LatestTaskTypeName
		documentDocumentDetailResp.LatestTaskStatus = (*source).LatestTaskStatus
		documentDocumentDetailResp.LatestTaskStatusName = (*source).LatestTaskStatusName
		documentDocumentDetailResp.CreateTime = TimeToString((*source).CreateTime)
		documentDocumentDetailResp.UpdateTime = TimeToString((*source).UpdateTime)
		pDocumentDocumentDetailResp = &documentDocumentDetailResp
	}
	return pDocumentDocumentDetailResp
}
func ToDocumentDetailRespList(source []*entity1.Document) []*document.DocumentDetailResp {
	var pDocumentDocumentDetailRespList []*document.DocumentDetailResp
	if source != nil {
		pDocumentDocumentDetailRespList = make([]*document.DocumentDetailResp, len(source))
		for i := 0; i < len(source); i++ {
			pDocumentDocumentDetailRespList[i] = ToDocumentDetailResp(source[i])
		}
	}
	return pDocumentDocumentDetailRespList
}
func ToDocumentModel(source *entity1.Document) *model.Document {
	var pModelDocument *model.Document
	if source != nil {
		var modelDocument model.Document
		modelDocument.Model = entityDocumentToCommonModel((*source))
		modelDocument.DocumentName = (*source).DocumentName
		modelDocument.OriginalFileName = (*source).OriginalFileName
		modelDocument.FileType = (*source).FileType
		modelDocument.MimeType = (*source).MimeType
		modelDocument.FileSize = (*source).FileSize
		modelDocument.StorageType = (*source).StorageType
		modelDocument.BucketName = (*source).BucketName
		modelDocument.ObjectName = (*source).ObjectName
		modelDocument.ObjectUrl = (*source).ObjectUrl
		modelDocument.ParseStatus = (*source).ParseStatus
		modelDocument.StrategyStatus = (*source).StrategyStatus
		modelDocument.IndexStatus = (*source).IndexStatus
		modelDocument.CharCount = (*source).CharCount
		modelDocument.TokenCount = (*source).TokenCount
		modelDocument.StructureLevel = (*source).StructureLevel
		modelDocument.ContentQualityLevel = (*source).ContentQualityLevel
		modelDocument.ParseTextPath = (*source).ParseTextPath
		if (*source).ParseErrorMsg != nil {
			modelDocument.ParseErrorMsg = *(*source).ParseErrorMsg
		}
		modelDocument.KnowledgeBaseId = (*source).KnowledgeBaseId
		modelDocument.KnowledgeBaseName = (*source).KnowledgeBaseName
		modelDocument.CurrentPlanId = (*source).CurrentPlanId
		modelDocument.LastParseTaskId = (*source).LastParseTaskId
		modelDocument.StructureNodeCount = (*source).StructureNodeCount
		modelDocument.LastIndexTaskId = (*source).LastIndexTaskId
		pModelDocument = &modelDocument
	}
	return pModelDocument
}
func ToDocumentParentBlockModel(source *entity1.DocumentParentChunk) *model.DocumentParentChunk {
	var pModelDocumentParentChunk *model.DocumentParentChunk
	if source != nil {
		var modelDocumentParentChunk model.DocumentParentChunk
		modelDocumentParentChunk.Model = entityDocumentParentChunkToCommonModel((*source))
		modelDocumentParentChunk.DocumentId = (*source).DocumentId
		modelDocumentParentChunk.TaskId = (*source).TaskId
		modelDocumentParentChunk.PlanId = (*source).PlanId
		modelDocumentParentChunk.ParentNo = (*source).ParentNo
		modelDocumentParentChunk.SourceType = (*source).SourceType
		modelDocumentParentChunk.SectionPath = (*source).SectionPath
		modelDocumentParentChunk.StructureNodeId = (*source).StructureNodeId
		modelDocumentParentChunk.StructureNodeType = (*source).StructureNodeType
		modelDocumentParentChunk.CanonicalPath = (*source).CanonicalPath
		modelDocumentParentChunk.ItemIndex = (*source).ItemIndex
		modelDocumentParentChunk.ParentText = (*source).ParentText
		modelDocumentParentChunk.CharCount = (*source).CharCount
		modelDocumentParentChunk.TokenCount = (*source).TokenCount
		modelDocumentParentChunk.ChildCount = (*source).ChildCount
		modelDocumentParentChunk.StartChunkNo = (*source).StartChunkNo
		modelDocumentParentChunk.EndChunkNo = (*source).EndChunkNo
		modelDocumentParentChunk.PageRange = (*source).PageRange
		modelDocumentParentChunk.SourceBlockIds = (*source).SourceBlockIds
		pModelDocumentParentChunk = &modelDocumentParentChunk
	}
	return pModelDocumentParentChunk
}
func ToDocumentParentBlockModelList(source []*entity1.DocumentParentChunk) []*model.DocumentParentChunk {
	var pModelDocumentParentChunkList []*model.DocumentParentChunk
	if source != nil {
		pModelDocumentParentChunkList = make([]*model.DocumentParentChunk, len(source))
		for i := 0; i < len(source); i++ {
			pModelDocumentParentChunkList[i] = ToDocumentParentBlockModel(source[i])
		}
	}
	return pModelDocumentParentChunkList
}
func ToDocumentProfileModel(source *entity1.DocumentProfile) *model.DocumentProfile {
	var pModelDocumentProfile *model.DocumentProfile
	if source != nil {
		var modelDocumentProfile model.DocumentProfile
		modelDocumentProfile.Model = entityDocumentProfileToCommonModel((*source))
		modelDocumentProfile.DocumentId = (*source).DocumentId
		modelDocumentProfile.ProfileVersion = (*source).ProfileVersion
		modelDocumentProfile.DocumentSummary = (*source).DocumentSummary
		modelDocumentProfile.DocumentType = (*source).DocumentType
		modelDocumentProfile.CoreTopics = (*source).CoreTopics
		modelDocumentProfile.ExampleQuestions = (*source).ExampleQuestions
		modelDocumentProfile.GraphFriendly = (*source).GraphFriendly
		modelDocumentProfile.SupportsGraphOutline = (*source).SupportsGraphOutline
		modelDocumentProfile.SupportsItemLookup = (*source).SupportsItemLookup
		modelDocumentProfile.SupportsGraphAssist = (*source).SupportsGraphAssist
		modelDocumentProfile.ProfileSource = (*source).ProfileSource
		modelDocumentProfile.ProfileStatus = (*source).ProfileStatus
		modelDocumentProfile.ErrorMsg = (*source).ErrorMsg
		pModelDocumentProfile = &modelDocumentProfile
	}
	return pModelDocumentProfile
}
func ToDocumentProfileResp(source *entity1.DocumentProfile) *document.DocumentProfileResp {
	var pDocumentDocumentProfileResp *document.DocumentProfileResp
	if source != nil {
		var documentDocumentProfileResp document.DocumentProfileResp
		documentDocumentProfileResp.DocumentId = Int64ToString((*source).DocumentId)
		documentDocumentProfileResp.DocumentSummary = (*source).DocumentSummary
		documentDocumentProfileResp.DocumentType = (*source).DocumentType
		documentDocumentProfileResp.CoreTopics = (*source).CoreTopics
		documentDocumentProfileResp.ExampleQuestions = (*source).ExampleQuestions
		documentDocumentProfileResp.GraphFriendly = (*source).GraphFriendly
		documentDocumentProfileResp.SupportsGraphOutline = (*source).SupportsGraphOutline
		documentDocumentProfileResp.SupportsItemLookup = (*source).SupportsItemLookup
		documentDocumentProfileResp.SupportsGraphAssist = (*source).SupportsGraphAssist
		documentDocumentProfileResp.ProfileSource = (*source).ProfileSource
		documentDocumentProfileResp.ProfileStatus = (*source).ProfileStatus
		if (*source).ErrorMsg != nil {
			documentDocumentProfileResp.ErrorMsg = *(*source).ErrorMsg
		}
		pDocumentDocumentProfileResp = &documentDocumentProfileResp
	}
	return pDocumentDocumentProfileResp
}
func ToDocumentProfileRespList(source []*entity1.DocumentProfile) []*document.DocumentProfileResp {
	var pDocumentDocumentProfileRespList []*document.DocumentProfileResp
	if source != nil {
		pDocumentDocumentProfileRespList = make([]*document.DocumentProfileResp, len(source))
		for i := 0; i < len(source); i++ {
			pDocumentDocumentProfileRespList[i] = ToDocumentProfileResp(source[i])
		}
	}
	return pDocumentDocumentProfileRespList
}
func ToDocumentStrategyPlan(source *entity1.DocumentStrategyPlan) *document.DocumentStrategyPlan {
	var pDocumentDocumentStrategyPlan *document.DocumentStrategyPlan
	if source != nil {
		var documentDocumentStrategyPlan document.DocumentStrategyPlan
		documentDocumentStrategyPlan.ID = Int64ToString((*source).ID)
		documentDocumentStrategyPlan.PlanVersion = (*source).PlanVersion
		documentDocumentStrategyPlan.PlanSource = (*source).PlanSource
		documentDocumentStrategyPlan.PlanSourceName = (*source).PlanSourceName
		documentDocumentStrategyPlan.PlanStatus = (*source).PlanStatus
		documentDocumentStrategyPlan.PlanStatusName = (*source).PlanStatusName
		documentDocumentStrategyPlan.StrategySnapshot = (*source).StrategySnapshot
		documentDocumentStrategyPlan.RecommendReason = (*source).RecommendReason
		documentDocumentStrategyPlan.ParentPipeline = pEntityDocumentStrategyPipelineToPDocumentDocumentStrategyPipeline((*source).ParentPipeline)
		documentDocumentStrategyPlan.ChildPipeline = pEntityDocumentStrategyPipelineToPDocumentDocumentStrategyPipeline((*source).ChildPipeline)
		pDocumentDocumentStrategyPlan = &documentDocumentStrategyPlan
	}
	return pDocumentDocumentStrategyPlan
}
func ToDocumentStrategyPlanModel(source *entity1.DocumentStrategyPlan) *model.DocumentStrategyPlan {
	var pModelDocumentStrategyPlan *model.DocumentStrategyPlan
	if source != nil {
		var modelDocumentStrategyPlan model.DocumentStrategyPlan
		modelDocumentStrategyPlan.Model = entityDocumentStrategyPlanToCommonModel((*source))
		modelDocumentStrategyPlan.DocumentId = (*source).DocumentId
		modelDocumentStrategyPlan.PlanVersion = (*source).PlanVersion
		modelDocumentStrategyPlan.PlanSource = (*source).PlanSource
		modelDocumentStrategyPlan.PlanStatus = (*source).PlanStatus
		modelDocumentStrategyPlan.StrategyCount = (*source).StrategyCount
		modelDocumentStrategyPlan.StrategySnapshot = (*source).StrategySnapshot
		modelDocumentStrategyPlan.RecommendReason = (*source).RecommendReason
		modelDocumentStrategyPlan.AdjustNote = (*source).AdjustNote
		modelDocumentStrategyPlan.ConfirmUserId = (*source).ConfirmUserId
		modelDocumentStrategyPlan.ConfirmTime = (*source).ConfirmTime
		pModelDocumentStrategyPlan = &modelDocumentStrategyPlan
	}
	return pModelDocumentStrategyPlan
}
func ToDocumentStrategyStepModel(source *entity1.DocumentStrategyStep) *model.DocumentStrategyStep {
	var pModelDocumentStrategyStep *model.DocumentStrategyStep
	if source != nil {
		var modelDocumentStrategyStep model.DocumentStrategyStep
		modelDocumentStrategyStep.Model = entityDocumentStrategyStepToCommonModel((*source))
		modelDocumentStrategyStep.PlanId = (*source).PlanId
		modelDocumentStrategyStep.DocumentId = (*source).DocumentId
		modelDocumentStrategyStep.StepNo = (*source).StepNo
		modelDocumentStrategyStep.PipelineType = (*source).PipelineType
		modelDocumentStrategyStep.StrategyType = (*source).StrategyType
		modelDocumentStrategyStep.StrategyRole = (*source).StrategyRole
		modelDocumentStrategyStep.SourceType = (*source).SourceType
		modelDocumentStrategyStep.ExecuteStatus = (*source).ExecuteStatus
		modelDocumentStrategyStep.RecommendReason = (*source).RecommendReason
		pModelDocumentStrategyStep = &modelDocumentStrategyStep
	}
	return pModelDocumentStrategyStep
}
func ToDocumentStrategyStepModelList(source []*entity1.DocumentStrategyStep) []*model.DocumentStrategyStep {
	var pModelDocumentStrategyStepList []*model.DocumentStrategyStep
	if source != nil {
		pModelDocumentStrategyStepList = make([]*model.DocumentStrategyStep, len(source))
		for i := 0; i < len(source); i++ {
			pModelDocumentStrategyStepList[i] = ToDocumentStrategyStepModel(source[i])
		}
	}
	return pModelDocumentStrategyStepList
}
func ToDocumentStructureNodeModel(source *entity1.StructureNode) *model.DocumentStructureNode {
	var pModelDocumentStructureNode *model.DocumentStructureNode
	if source != nil {
		var modelDocumentStructureNode model.DocumentStructureNode
		modelDocumentStructureNode.Model = entityStructureNodeToCommonModel((*source))
		modelDocumentStructureNode.DocumentId = (*source).DocumentId
		modelDocumentStructureNode.ParseTaskId = (*source).ParseTaskId
		modelDocumentStructureNode.NodeNo = (*source).NodeNo
		modelDocumentStructureNode.NodeType = (*source).NodeType
		modelDocumentStructureNode.ParentNodeId = (*source).ParentNodeId
		modelDocumentStructureNode.PrevSiblingNodeId = (*source).PrevSiblingNodeId
		modelDocumentStructureNode.NextSiblingNodeId = (*source).NextSiblingNodeId
		modelDocumentStructureNode.Depth = (*source).Depth
		modelDocumentStructureNode.NodeCode = (*source).NodeCode
		modelDocumentStructureNode.Title = (*source).Title
		modelDocumentStructureNode.AnchorText = (*source).AnchorText
		modelDocumentStructureNode.CanonicalPath = (*source).CanonicalPath
		modelDocumentStructureNode.SectionPath = (*source).SectionPath
		modelDocumentStructureNode.ContentText = (*source).ContentText
		modelDocumentStructureNode.ItemIndex = (*source).ItemIndex
		modelDocumentStructureNode.SyntaxSchemaVersion = (*source).SyntaxSchemaVersion
		modelDocumentStructureNode.SyntaxSourceSha256 = (*source).SyntaxSourceSha256
		modelDocumentStructureNode.SyntaxNodeId = (*source).SyntaxNodeId
		modelDocumentStructureNode.SyntaxNodeType = (*source).SyntaxNodeType
		modelDocumentStructureNode.SyntaxSourceOrigin = (*source).SyntaxSourceOrigin
		modelDocumentStructureNode.SourceStartByte = (*source).SourceStartByte
		modelDocumentStructureNode.SourceEndByte = (*source).SourceEndByte
		modelDocumentStructureNode.SourceStartLine = (*source).SourceStartLine
		modelDocumentStructureNode.SourceStartColumn = (*source).SourceStartColumn
		modelDocumentStructureNode.SourceEndLine = (*source).SourceEndLine
		modelDocumentStructureNode.SourceEndColumn = (*source).SourceEndColumn
		pModelDocumentStructureNode = &modelDocumentStructureNode
	}
	return pModelDocumentStructureNode
}
func ToDocumentStructureNodeModelList(source []*entity1.StructureNode) []*model.DocumentStructureNode {
	var pModelDocumentStructureNodeList []*model.DocumentStructureNode
	if source != nil {
		pModelDocumentStructureNodeList = make([]*model.DocumentStructureNode, len(source))
		for i := 0; i < len(source); i++ {
			pModelDocumentStructureNodeList[i] = ToDocumentStructureNodeModel(source[i])
		}
	}
	return pModelDocumentStructureNodeList
}
func ToDocumentTableCellModel(source *entity1.TableCell) *model.DocumentTableCell {
	var pModelDocumentTableCell *model.DocumentTableCell
	if source != nil {
		var modelDocumentTableCell model.DocumentTableCell
		modelDocumentTableCell.Model = entityTableCellToCommonModel((*source))
		modelDocumentTableCell.DocumentId = (*source).DocumentId
		modelDocumentTableCell.TaskId = (*source).TaskId
		modelDocumentTableCell.TableId = (*source).TableId
		modelDocumentTableCell.RowId = (*source).RowId
		modelDocumentTableCell.ColumnId = (*source).ColumnId
		modelDocumentTableCell.RowNo = (*source).RowNo
		modelDocumentTableCell.ColumnNo = (*source).ColumnNo
		modelDocumentTableCell.CellText = (*source).CellText
		modelDocumentTableCell.NumericValue = (*source).NumericValue
		modelDocumentTableCell.SourceRowNo = (*source).SourceRowNo
		modelDocumentTableCell.SourceColumnNo = (*source).SourceColumnNo
		modelDocumentTableCell.SourceCellRef = (*source).SourceCellRef
		pModelDocumentTableCell = &modelDocumentTableCell
	}
	return pModelDocumentTableCell
}
func ToDocumentTableCellModelList(source []*entity1.TableCell) []*model.DocumentTableCell {
	var pModelDocumentTableCellList []*model.DocumentTableCell
	if source != nil {
		pModelDocumentTableCellList = make([]*model.DocumentTableCell, len(source))
		for i := 0; i < len(source); i++ {
			pModelDocumentTableCellList[i] = ToDocumentTableCellModel(source[i])
		}
	}
	return pModelDocumentTableCellList
}
func ToDocumentTableColumnModel(source *entity1.TableColumn) *model.DocumentTableColumn {
	var pModelDocumentTableColumn *model.DocumentTableColumn
	if source != nil {
		var modelDocumentTableColumn model.DocumentTableColumn
		modelDocumentTableColumn.Model = entityTableColumnToCommonModel((*source))
		modelDocumentTableColumn.DocumentId = (*source).DocumentId
		modelDocumentTableColumn.TaskId = (*source).TaskId
		modelDocumentTableColumn.TableId = (*source).TableId
		modelDocumentTableColumn.ColumnNo = (*source).ColumnNo
		modelDocumentTableColumn.ColumnName = (*source).ColumnName
		modelDocumentTableColumn.NormalizedName = (*source).NormalizedName
		modelDocumentTableColumn.ValueType = (*source).ValueType
		pModelDocumentTableColumn = &modelDocumentTableColumn
	}
	return pModelDocumentTableColumn
}
func ToDocumentTableColumnModelList(source []*entity1.TableColumn) []*model.DocumentTableColumn {
	var pModelDocumentTableColumnList []*model.DocumentTableColumn
	if source != nil {
		pModelDocumentTableColumnList = make([]*model.DocumentTableColumn, len(source))
		for i := 0; i < len(source); i++ {
			pModelDocumentTableColumnList[i] = ToDocumentTableColumnModel(source[i])
		}
	}
	return pModelDocumentTableColumnList
}
func ToDocumentTableModel(source *entity1.DocumentTable) *model.DocumentTable {
	var pModelDocumentTable *model.DocumentTable
	if source != nil {
		var modelDocumentTable model.DocumentTable
		modelDocumentTable.Model = entityDocumentTableToCommonModel((*source))
		modelDocumentTable.DocumentId = (*source).DocumentId
		modelDocumentTable.TaskId = (*source).TaskId
		modelDocumentTable.BlockId = (*source).BlockId
		modelDocumentTable.TableNo = (*source).TableNo
		modelDocumentTable.SectionPath = (*source).SectionPath
		modelDocumentTable.PageNo = (*source).PageNo
		modelDocumentTable.PageRange = (*source).PageRange
		modelDocumentTable.BboxJson = (*source).BboxJson
		modelDocumentTable.Title = (*source).Title
		modelDocumentTable.RowCount = (*source).RowCount
		modelDocumentTable.ColumnCount = (*source).ColumnCount
		pModelDocumentTable = &modelDocumentTable
	}
	return pModelDocumentTable
}
func ToDocumentTableModelList(source []*entity1.DocumentTable) []*model.DocumentTable {
	var pModelDocumentTableList []*model.DocumentTable
	if source != nil {
		pModelDocumentTableList = make([]*model.DocumentTable, len(source))
		for i := 0; i < len(source); i++ {
			pModelDocumentTableList[i] = ToDocumentTableModel(source[i])
		}
	}
	return pModelDocumentTableList
}
func ToDocumentTableRowModel(source *entity1.TableRow) *model.DocumentTableRow {
	var pModelDocumentTableRow *model.DocumentTableRow
	if source != nil {
		var modelDocumentTableRow model.DocumentTableRow
		modelDocumentTableRow.Model = entityTableRowToCommonModel((*source))
		modelDocumentTableRow.DocumentId = (*source).DocumentId
		modelDocumentTableRow.TaskId = (*source).TaskId
		modelDocumentTableRow.TableId = (*source).TableId
		modelDocumentTableRow.RowNo = (*source).RowNo
		modelDocumentTableRow.RowText = (*source).RowText
		pModelDocumentTableRow = &modelDocumentTableRow
	}
	return pModelDocumentTableRow
}
func ToDocumentTableRowModelList(source []*entity1.TableRow) []*model.DocumentTableRow {
	var pModelDocumentTableRowList []*model.DocumentTableRow
	if source != nil {
		pModelDocumentTableRowList = make([]*model.DocumentTableRow, len(source))
		for i := 0; i < len(source); i++ {
			pModelDocumentTableRowList[i] = ToDocumentTableRowModel(source[i])
		}
	}
	return pModelDocumentTableRowList
}
func ToDocumentTaskLogModel(source *entity1.DocumentTaskLog) *model.DocumentTaskLog {
	var pModelDocumentTaskLog *model.DocumentTaskLog
	if source != nil {
		var modelDocumentTaskLog model.DocumentTaskLog
		modelDocumentTaskLog.Model = entityDocumentTaskLogToCommonModel((*source))
		modelDocumentTaskLog.TaskId = (*source).TaskId
		modelDocumentTaskLog.DocumentId = (*source).DocumentId
		modelDocumentTaskLog.StageType = (*source).StageType
		modelDocumentTaskLog.EventType = (*source).EventType
		modelDocumentTaskLog.LogLevel = (*source).LogLevel
		modelDocumentTaskLog.OperatorType = (*source).OperatorType
		modelDocumentTaskLog.OperatorId = (*source).OperatorId
		modelDocumentTaskLog.Content = (*source).Content
		modelDocumentTaskLog.DetailJson = (*source).DetailJson
		pModelDocumentTaskLog = &modelDocumentTaskLog
	}
	return pModelDocumentTaskLog
}
func ToDocumentTaskModel(source *entity1.DocumentTask) *model.DocumentTask {
	var pModelDocumentTask *model.DocumentTask
	if source != nil {
		var modelDocumentTask model.DocumentTask
		modelDocumentTask.Model = entityDocumentTaskToCommonModel((*source))
		modelDocumentTask.DocumentId = (*source).DocumentId
		modelDocumentTask.PlanId = (*source).PlanId
		modelDocumentTask.SourceParseTaskId = (*source).SourceParseTaskId
		modelDocumentTask.TaskType = (*source).TaskType
		modelDocumentTask.TaskStatus = (*source).TaskStatus
		modelDocumentTask.CurrentStage = (*source).CurrentStage
		modelDocumentTask.TriggerSource = (*source).TriggerSource
		modelDocumentTask.StrategySnapshot = (*source).StrategySnapshot
		modelDocumentTask.RetryCount = (*source).RetryCount
		modelDocumentTask.StartTime = (*source).StartTime
		modelDocumentTask.FinishTime = (*source).FinishTime
		modelDocumentTask.CostMillis = (*source).CostMillis
		modelDocumentTask.ErrorCode = (*source).ErrorCode
		modelDocumentTask.ErrorMsg = (*source).ErrorMsg
		modelDocumentTask.ExtJson = (*source).ExtJson
		pModelDocumentTask = &modelDocumentTask
	}
	return pModelDocumentTask
}
func ToKnowledgeDocumentOptionRespList(source []*vo1.DocumentMetadata) []*document.KnowledgeDocumentOptionResp {
	var pDocumentKnowledgeDocumentOptionRespList []*document.KnowledgeDocumentOptionResp
	if source != nil {
		pDocumentKnowledgeDocumentOptionRespList = make([]*document.KnowledgeDocumentOptionResp, len(source))
		for i := 0; i < len(source); i++ {
			pDocumentKnowledgeDocumentOptionRespList[i] = pVoDocumentMetadataToPDocumentKnowledgeDocumentOptionResp(source[i])
		}
	}
	return pDocumentKnowledgeDocumentOptionRespList
}
func ToParseArtifactModel(source *entity1.ParseArtifact) *model.DocumentParseArtifact {
	var pModelDocumentParseArtifact *model.DocumentParseArtifact
	if source != nil {
		var modelDocumentParseArtifact model.DocumentParseArtifact
		modelDocumentParseArtifact.Model = entityParseArtifactToCommonModel((*source))
		modelDocumentParseArtifact.DocumentId = (*source).DocumentId
		modelDocumentParseArtifact.TaskId = (*source).TaskId
		modelDocumentParseArtifact.ArtifactType = (*source).ArtifactType
		modelDocumentParseArtifact.ObjectName = (*source).ObjectName
		modelDocumentParseArtifact.ContentHash = (*source).ContentHash
		modelDocumentParseArtifact.ParserName = (*source).ParserName
		modelDocumentParseArtifact.ParserVersion = (*source).ParserVersion
		pModelDocumentParseArtifact = &modelDocumentParseArtifact
	}
	return pModelDocumentParseArtifact
}
func ToParseArtifactModelList(source []*entity1.ParseArtifact) []*model.DocumentParseArtifact {
	var pModelDocumentParseArtifactList []*model.DocumentParseArtifact
	if source != nil {
		pModelDocumentParseArtifactList = make([]*model.DocumentParseArtifact, len(source))
		for i := 0; i < len(source); i++ {
			pModelDocumentParseArtifactList[i] = ToParseArtifactModel(source[i])
		}
	}
	return pModelDocumentParseArtifactList
}
func ToQueryDocumentChunkDetailResp(source *aggregate1.DocumentChunkDetail) *document.QueryDocumentChunkDetailResp {
	var pDocumentQueryDocumentChunkDetailResp *document.QueryDocumentChunkDetailResp
	if source != nil {
		var documentQueryDocumentChunkDetailResp document.QueryDocumentChunkDetailResp
		documentQueryDocumentChunkDetailResp.DocumentId = Int64ToString((*source).DocumentId)
		documentQueryDocumentChunkDetailResp.TaskId = Int64ToString((*source).TaskId)
		documentQueryDocumentChunkDetailResp.PlanId = Int64ToString((*source).PlanId)
		documentQueryDocumentChunkDetailResp.Chunk = pEntityDocumentChunkToPDocumentDocumentChunkItem((*source).Chunk)
		documentQueryDocumentChunkDetailResp.SiblingChunks = ToDocumentChunkItemList((*source).SiblingChunks)
		pDocumentQueryDocumentChunkDetailResp = &documentQueryDocumentChunkDetailResp
	}
	return pDocumentQueryDocumentChunkDetailResp
}
func ToQueryStrategyPlanResp(source *entity1.Document) *document.QueryStrategyPlanResp {
	var pDocumentQueryStrategyPlanResp *document.QueryStrategyPlanResp
	if source != nil {
		var documentQueryStrategyPlanResp document.QueryStrategyPlanResp
		documentQueryStrategyPlanResp.ID = Int64ToString((*source).ID)
		documentQueryStrategyPlanResp.DocumentName = (*source).DocumentName
		documentQueryStrategyPlanResp.ParseStatus = (*source).ParseStatus
		documentQueryStrategyPlanResp.ParseStatusName = (*source).ParseStatusName
		documentQueryStrategyPlanResp.StrategyStatus = (*source).StrategyStatus
		documentQueryStrategyPlanResp.StrategyStatusName = (*source).StrategyStatusName
		documentQueryStrategyPlanResp.IndexStatus = (*source).IndexStatus
		documentQueryStrategyPlanResp.IndexStatusName = (*source).IndexStatusName
		if (*source).ParseErrorMsg != nil {
			documentQueryStrategyPlanResp.ParseErrorMsg = *(*source).ParseErrorMsg
		}
		documentQueryStrategyPlanResp.PlanReady = (*source).PlanReady
		pDocumentQueryStrategyPlanResp = &documentQueryStrategyPlanResp
	}
	return pDocumentQueryStrategyPlanResp
}
func ToQueryTaskLogsResp(source *entity1.DocumentTask) *document.QueryTaskLogsResp {
	var pDocumentQueryTaskLogsResp *document.QueryTaskLogsResp
	if source != nil {
		var documentQueryTaskLogsResp document.QueryTaskLogsResp
		documentQueryTaskLogsResp.ID = Int64ToString((*source).ID)
		documentQueryTaskLogsResp.DocumentId = Int64ToString((*source).DocumentId)
		documentQueryTaskLogsResp.TaskType = (*source).TaskType
		documentQueryTaskLogsResp.TaskTypeName = (*source).TaskTypeName
		documentQueryTaskLogsResp.TaskStatus = (*source).TaskStatus
		documentQueryTaskLogsResp.TaskStatusName = (*source).TaskStatusName
		documentQueryTaskLogsResp.CurrentStage = (*source).CurrentStage
		documentQueryTaskLogsResp.CurrentStageName = (*source).CurrentStageName
		documentQueryTaskLogsResp.StartTime = pTimeTimeToString2((*source).StartTime)
		documentQueryTaskLogsResp.FinishTime = pTimeTimeToString2((*source).FinishTime)
		documentQueryTaskLogsResp.CostMillis = (*source).CostMillis
		if (*source).ErrorCode != nil {
			documentQueryTaskLogsResp.ErrorCode = *(*source).ErrorCode
		}
		if (*source).ErrorMsg != nil {
			documentQueryTaskLogsResp.ErrorMsg = *(*source).ErrorMsg
		}
		if (*source).Logs != nil {
			documentQueryTaskLogsResp.Logs = make([]*document.TaskLog, len((*source).Logs))
			for i := 0; i < len((*source).Logs); i++ {
				documentQueryTaskLogsResp.Logs[i] = pEntityDocumentTaskLogToPDocumentTaskLog((*source).Logs[i])
			}
		}
		pDocumentQueryTaskLogsResp = &documentQueryTaskLogsResp
	}
	return pDocumentQueryTaskLogsResp
}
func entityDocumentBlockToCommonModel(source entity1.DocumentBlock) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityDocumentChunkToCommonModel(source entity1.DocumentChunk) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityDocumentParentChunkToCommonModel(source entity1.DocumentParentChunk) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityDocumentProfileToCommonModel(source entity1.DocumentProfile) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityDocumentStrategyPlanToCommonModel(source entity1.DocumentStrategyPlan) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityDocumentStrategyStepToCommonModel(source entity1.DocumentStrategyStep) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityDocumentTableToCommonModel(source entity1.DocumentTable) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityDocumentTaskLogToCommonModel(source entity1.DocumentTaskLog) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityDocumentTaskToCommonModel(source entity1.DocumentTask) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityDocumentToCommonModel(source entity1.Document) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityParseArtifactToCommonModel(source entity1.ParseArtifact) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityStructureNodeToCommonModel(source entity1.StructureNode) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityTableCellToCommonModel(source entity1.TableCell) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityTableColumnToCommonModel(source entity1.TableColumn) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityTableRowToCommonModel(source entity1.TableRow) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func pDocumentStrategyStepItemToPVoDocumentStrategyStepItem(source *document.StrategyStepItem) *vo1.DocumentStrategyStepItem {
	var pVoDocumentStrategyStepItem *vo1.DocumentStrategyStepItem
	if source != nil {
		var voDocumentStrategyStepItem vo1.DocumentStrategyStepItem
		voDocumentStrategyStepItem.StepNo = (*source).StepNo
		voDocumentStrategyStepItem.StrategyType = (*source).StrategyType
		pVoDocumentStrategyStepItem = &voDocumentStrategyStepItem
	}
	return pVoDocumentStrategyStepItem
}
func pEntityDocumentChunkToPDocumentDocumentChunkItem(source *entity1.DocumentChunk) *document.DocumentChunkItem {
	var pDocumentDocumentChunkItem *document.DocumentChunkItem
	if source != nil {
		var documentDocumentChunkItem document.DocumentChunkItem
		documentDocumentChunkItem.ID = Int64ToString((*source).ID)
		documentDocumentChunkItem.ParentBlockNo = (*source).ParentBlockNo
		documentDocumentChunkItem.ParentChildCount = (*source).ParentChildCount
		documentDocumentChunkItem.ParentStartChunkNo = (*source).ParentStartChunkNo
		documentDocumentChunkItem.ParentEndChunkNo = (*source).ParentEndChunkNo
		documentDocumentChunkItem.ChunkNo = (*source).ChunkNo
		documentDocumentChunkItem.SectionPath = (*source).SectionPath
		documentDocumentChunkItem.SourceType = (*source).SourceType
		documentDocumentChunkItem.SourceTypeName = (*source).SourceTypeName
		documentDocumentChunkItem.CharCount = (*source).CharCount
		documentDocumentChunkItem.TokenCount = (*source).TokenCount
		documentDocumentChunkItem.VectorStatus = (*source).VectorStatus
		documentDocumentChunkItem.VectorStatusName = (*source).VectorStatusName
		documentDocumentChunkItem.ChunkText = (*source).ChunkText
		pDocumentDocumentChunkItem = &documentDocumentChunkItem
	}
	return pDocumentDocumentChunkItem
}
func pEntityDocumentStrategyPipelineToPDocumentDocumentStrategyPipeline(source *entity1.DocumentStrategyPipeline) *document.DocumentStrategyPipeline {
	var pDocumentDocumentStrategyPipeline *document.DocumentStrategyPipeline
	if source != nil {
		var documentDocumentStrategyPipeline document.DocumentStrategyPipeline
		documentDocumentStrategyPipeline.PipelineType = (*source).PipelineType
		documentDocumentStrategyPipeline.PipelineTypeName = (*source).PipelineTypeName
		documentDocumentStrategyPipeline.StrategySnapshot = (*source).StrategySnapshot
		if (*source).Steps != nil {
			documentDocumentStrategyPipeline.Steps = make([]*document.DocumentStrategyStep, len((*source).Steps))
			for i := 0; i < len((*source).Steps); i++ {
				documentDocumentStrategyPipeline.Steps[i] = pEntityDocumentStrategyStepToPDocumentDocumentStrategyStep((*source).Steps[i])
			}
		}
		pDocumentDocumentStrategyPipeline = &documentDocumentStrategyPipeline
	}
	return pDocumentDocumentStrategyPipeline
}
func pEntityDocumentStrategyStepToPDocumentDocumentStrategyStep(source *entity1.DocumentStrategyStep) *document.DocumentStrategyStep {
	var pDocumentDocumentStrategyStep *document.DocumentStrategyStep
	if source != nil {
		var documentDocumentStrategyStep document.DocumentStrategyStep
		documentDocumentStrategyStep.StepNo = (*source).StepNo
		documentDocumentStrategyStep.PipelineType = (*source).PipelineType
		documentDocumentStrategyStep.PipelineTypeName = (*source).PipelineTypeName
		documentDocumentStrategyStep.StrategyType = (*source).StrategyType
		documentDocumentStrategyStep.StrategyTypeName = (*source).StrategyTypeName
		documentDocumentStrategyStep.StrategyRole = (*source).StrategyRole
		documentDocumentStrategyStep.StrategyRoleName = (*source).StrategyRoleName
		documentDocumentStrategyStep.SourceType = (*source).SourceType
		documentDocumentStrategyStep.SourceTypeName = (*source).SourceTypeName
		documentDocumentStrategyStep.ExecuteStatus = (*source).ExecuteStatus
		documentDocumentStrategyStep.ExecuteStatusName = (*source).ExecuteStatusName
		documentDocumentStrategyStep.RecommendReason = (*source).RecommendReason
		pDocumentDocumentStrategyStep = &documentDocumentStrategyStep
	}
	return pDocumentDocumentStrategyStep
}
func pEntityDocumentTaskLogToPDocumentTaskLog(source *entity1.DocumentTaskLog) *document.TaskLog {
	var pDocumentTaskLog *document.TaskLog
	if source != nil {
		var documentTaskLog document.TaskLog
		documentTaskLog.ID = Int64ToString((*source).ID)
		documentTaskLog.StageType = (*source).StageType
		documentTaskLog.StageTypeName = (*source).StageTypeName
		documentTaskLog.EventType = (*source).EventType
		documentTaskLog.EventTypeName = (*source).EventTypeName
		documentTaskLog.LogLevel = (*source).LogLevel
		documentTaskLog.LogLevelName = (*source).LogLevelName
		documentTaskLog.Content = (*source).Content
		documentTaskLog.DetailJson = (*source).DetailJson
		documentTaskLog.CreateTime = TimeToString((*source).CreateTime)
		pDocumentTaskLog = &documentTaskLog
	}
	return pDocumentTaskLog
}
func pTimeTimeToString2(source *time.Time) string {
	var xstring string
	if source != nil {
		xstring = TimeToString((*source))
	}
	return xstring
}
func pVoDocumentMetadataToPDocumentKnowledgeDocumentOptionResp(source *vo1.DocumentMetadata) *document.KnowledgeDocumentOptionResp {
	var pDocumentKnowledgeDocumentOptionResp *document.KnowledgeDocumentOptionResp
	if source != nil {
		var documentKnowledgeDocumentOptionResp document.KnowledgeDocumentOptionResp
		documentKnowledgeDocumentOptionResp.DocumentId = Int64ToString((*source).DocumentId)
		documentKnowledgeDocumentOptionResp.DocumentName = (*source).DocumentName
		pDocumentKnowledgeDocumentOptionResp = &documentKnowledgeDocumentOptionResp
	}
	return pDocumentKnowledgeDocumentOptionResp
}
func FromKnowledgeScopeSaveReq(source *knowledge.KnowledgeScopeSaveReq) *entity2.KnowledgeScopeNode {
	var pEntityKnowledgeScopeNode *entity2.KnowledgeScopeNode
	if source != nil {
		var entityKnowledgeScopeNode entity2.KnowledgeScopeNode
		entityKnowledgeScopeNode.ID = StringToInt64((*source).ID)
		entityKnowledgeScopeNode.ScopeCode = NormalizeString((*source).ScopeCode)
		entityKnowledgeScopeNode.ScopeName = NormalizeString((*source).ScopeName)
		entityKnowledgeScopeNode.ParentScopeCode = NormalizeString((*source).ParentScopeCode)
		entityKnowledgeScopeNode.Description = NormalizeString((*source).Description)
		entityKnowledgeScopeNode.Aliases = NormalizeString((*source).Aliases)
		entityKnowledgeScopeNode.Examples = NormalizeString((*source).Examples)
		entityKnowledgeScopeNode.SortOrder = (*source).SortOrder
		entityKnowledgeScopeNode.OperatorId = NormalizeString((*source).OperatorId)
		pEntityKnowledgeScopeNode = &entityKnowledgeScopeNode
	}
	return pEntityKnowledgeScopeNode
}
func FromKnowledgeTopicDocumentRelationSaveReq(source *knowledge.TopicDocumentRelationSaveReq) *entity2.KnowledgeTopicDocumentRelation {
	var pEntityKnowledgeTopicDocumentRelation *entity2.KnowledgeTopicDocumentRelation
	if source != nil {
		var entityKnowledgeTopicDocumentRelation entity2.KnowledgeTopicDocumentRelation
		entityKnowledgeTopicDocumentRelation.TopicCode = NormalizeString((*source).TopicCode)
		entityKnowledgeTopicDocumentRelation.DocumentId = StringToInt64((*source).DocumentId)
		entityKnowledgeTopicDocumentRelation.RelationScore = (*source).RelationScore
		entityKnowledgeTopicDocumentRelation.RelationSource = NormalizeString((*source).RelationSource)
		entityKnowledgeTopicDocumentRelation.Reason = NormalizeString((*source).Reason)
		pEntityKnowledgeTopicDocumentRelation = &entityKnowledgeTopicDocumentRelation
	}
	return pEntityKnowledgeTopicDocumentRelation
}
func FromKnowledgeTopicSaveReq(source *knowledge.KnowledgeTopicSaveReq) *entity2.KnowledgeTopicNode {
	var pEntityKnowledgeTopicNode *entity2.KnowledgeTopicNode
	if source != nil {
		var entityKnowledgeTopicNode entity2.KnowledgeTopicNode
		entityKnowledgeTopicNode.ID = StringToInt64((*source).ID)
		entityKnowledgeTopicNode.TopicCode = NormalizeString((*source).TopicCode)
		entityKnowledgeTopicNode.TopicName = NormalizeString((*source).TopicName)
		entityKnowledgeTopicNode.ScopeCode = NormalizeString((*source).ScopeCode)
		entityKnowledgeTopicNode.Description = NormalizeString((*source).Description)
		entityKnowledgeTopicNode.Aliases = NormalizeString((*source).Aliases)
		entityKnowledgeTopicNode.Examples = NormalizeString((*source).Examples)
		entityKnowledgeTopicNode.AnswerShape = NormalizeString((*source).AnswerShape)
		entityKnowledgeTopicNode.ExecutionPreference = NormalizeString((*source).ExecutionPreference)
		entityKnowledgeTopicNode.SortOrder = (*source).SortOrder
		entityKnowledgeTopicNode.OperatorId = NormalizeString((*source).OperatorId)
		pEntityKnowledgeTopicNode = &entityKnowledgeTopicNode
	}
	return pEntityKnowledgeTopicNode
}
func ToKnowledgeBaseEntities(source []*model.KnowledgeBase) []*entity2.KnowledgeBase {
	var pEntityKnowledgeBaseList []*entity2.KnowledgeBase
	if source != nil {
		pEntityKnowledgeBaseList = make([]*entity2.KnowledgeBase, len(source))
		for i := 0; i < len(source); i++ {
			pEntityKnowledgeBaseList[i] = ToKnowledgeBaseEntity(source[i])
		}
	}
	return pEntityKnowledgeBaseList
}
func ToKnowledgeBaseEntity(source *model.KnowledgeBase) *entity2.KnowledgeBase {
	var pEntityKnowledgeBase *entity2.KnowledgeBase
	if source != nil {
		var entityKnowledgeBase entity2.KnowledgeBase
		entityKnowledgeBase.ID = (*source).Model.ID
		entityKnowledgeBase.BaseName = NormalizeString((*source).BaseName)
		entityKnowledgeBase.Description = NormalizeString((*source).Description)
		entityKnowledgeBase.EmbeddingModel = NormalizeString((*source).EmbeddingModel)
		entityKnowledgeBase.RetrievalConfigJson = datatypesJSONToJsonRawMessage((*source).RetrievalConfigJson)
		entityKnowledgeBase.GraphRagConfigJson = datatypesJSONToJsonRawMessage((*source).GraphRagConfigJson)
		entityKnowledgeBase.RaptorConfigJson = datatypesJSONToJsonRawMessage((*source).RaptorConfigJson)
		entityKnowledgeBase.MetadataFilterJson = datatypesJSONToJsonRawMessage((*source).MetadataFilterJson)
		entityKnowledgeBase.IsDefault = (*source).IsDefault
		entityKnowledgeBase.SortOrder = (*source).SortOrder
		pEntityKnowledgeBase = &entityKnowledgeBase
	}
	return pEntityKnowledgeBase
}
func ToKnowledgeBaseModel(source *entity2.KnowledgeBase) *model.KnowledgeBase {
	var pModelKnowledgeBase *model.KnowledgeBase
	if source != nil {
		var modelKnowledgeBase model.KnowledgeBase
		modelKnowledgeBase.Model = entityKnowledgeBaseToCommonModel((*source))
		modelKnowledgeBase.BaseName = NormalizeString((*source).BaseName)
		modelKnowledgeBase.Description = NormalizeString((*source).Description)
		modelKnowledgeBase.EmbeddingModel = NormalizeString((*source).EmbeddingModel)
		modelKnowledgeBase.RetrievalConfigJson = jsonRawMessageToDatatypesJSON((*source).RetrievalConfigJson)
		modelKnowledgeBase.GraphRagConfigJson = jsonRawMessageToDatatypesJSON((*source).GraphRagConfigJson)
		modelKnowledgeBase.RaptorConfigJson = jsonRawMessageToDatatypesJSON((*source).RaptorConfigJson)
		modelKnowledgeBase.MetadataFilterJson = jsonRawMessageToDatatypesJSON((*source).MetadataFilterJson)
		modelKnowledgeBase.IsDefault = (*source).IsDefault
		modelKnowledgeBase.SortOrder = (*source).SortOrder
		pModelKnowledgeBase = &modelKnowledgeBase
	}
	return pModelKnowledgeBase
}
func ToKnowledgeBaseModelList(source []*entity2.KnowledgeBase) []*model.KnowledgeBase {
	var pModelKnowledgeBaseList []*model.KnowledgeBase
	if source != nil {
		pModelKnowledgeBaseList = make([]*model.KnowledgeBase, len(source))
		for i := 0; i < len(source); i++ {
			pModelKnowledgeBaseList[i] = ToKnowledgeBaseModel(source[i])
		}
	}
	return pModelKnowledgeBaseList
}
func ToKnowledgeBaseSelectionSnapshot(source *aggregate2.KnowledgeBaseSelectionSnapshot) *vo.KnowledgeBaseSelectionSnapshot {
	var pVoKnowledgeBaseSelectionSnapshot *vo.KnowledgeBaseSelectionSnapshot
	if source != nil {
		var voKnowledgeBaseSelectionSnapshot vo.KnowledgeBaseSelectionSnapshot
		voKnowledgeBaseSelectionSnapshot.SelectionMode = NormalizeString((*source).SelectionMode)
		voKnowledgeBaseSelectionSnapshot.SelectedKnowledgeBaseIds = (*source).SelectedKnowledgeBaseIds
		voKnowledgeBaseSelectionSnapshot.SelectedKnowledgeBaseNames = (*source).SelectedKnowledgeBaseNames
		if (*source).SelectedKnowledgeBases != nil {
			voKnowledgeBaseSelectionSnapshot.SelectedKnowledgeBases = make([]*vo.KnowledgeBase, len((*source).SelectedKnowledgeBases))
			for i := 0; i < len((*source).SelectedKnowledgeBases); i++ {
				voKnowledgeBaseSelectionSnapshot.SelectedKnowledgeBases[i] = pEntityKnowledgeBaseToPVoKnowledgeBase((*source).SelectedKnowledgeBases[i])
			}
		}
		if (*source).AllowedDocuments != nil {
			voKnowledgeBaseSelectionSnapshot.AllowedDocuments = make([]*vo.DocumentMetadata, len((*source).AllowedDocuments))
			for j := 0; j < len((*source).AllowedDocuments); j++ {
				voKnowledgeBaseSelectionSnapshot.AllowedDocuments[j] = pVoDocumentMetadataToPVoDocumentMetadata((*source).AllowedDocuments[j])
			}
		}
		voKnowledgeBaseSelectionSnapshot.RagRuntimeOptions = pVoRagRuntimeOptionsToPVoRagRuntimeOptions((*source).RagRuntimeOptions)
		pVoKnowledgeBaseSelectionSnapshot = &voKnowledgeBaseSelectionSnapshot
	}
	return pVoKnowledgeBaseSelectionSnapshot
}
func ToKnowledgeRouteTraceItem(source *entity2.KnowledgeRouteTrace) *knowledge.KnowledgeRouteTraceItem {
	var pKnowledgeKnowledgeRouteTraceItem *knowledge.KnowledgeRouteTraceItem
	if source != nil {
		var knowledgeKnowledgeRouteTraceItem knowledge.KnowledgeRouteTraceItem
		knowledgeKnowledgeRouteTraceItem.ID = Int64ToString((*source).ID)
		knowledgeKnowledgeRouteTraceItem.ConversationId = NormalizeString((*source).ConversationId)
		knowledgeKnowledgeRouteTraceItem.ExchangeId = Int64ToString((*source).ExchangeId)
		knowledgeKnowledgeRouteTraceItem.Question = NormalizeString((*source).Question)
		knowledgeKnowledgeRouteTraceItem.RewriteQuestion = NormalizeString((*source).RewriteQuestion)
		knowledgeKnowledgeRouteTraceItem.Mode = NormalizeString((*source).Mode)
		knowledgeKnowledgeRouteTraceItem.TopScopesJson = NormalizeString((*source).TopScopesJson)
		knowledgeKnowledgeRouteTraceItem.TopTopicsJson = NormalizeString((*source).TopTopicsJson)
		knowledgeKnowledgeRouteTraceItem.TopDocumentsJson = NormalizeString((*source).TopDocumentsJson)
		knowledgeKnowledgeRouteTraceItem.SelectedDocumentId = Int64ToString((*source).SelectedDocumentId)
		knowledgeKnowledgeRouteTraceItem.HitSelectedDocument = (*source).HitSelectedDocument
		knowledgeKnowledgeRouteTraceItem.Confidence = (*source).Confidence
		knowledgeKnowledgeRouteTraceItem.RouteStatus = ToRouteStatus((*source).RouteStatus)
		knowledgeKnowledgeRouteTraceItem.ErrorMsg = NormalizeString((*source).ErrorMsg)
		pKnowledgeKnowledgeRouteTraceItem = &knowledgeKnowledgeRouteTraceItem
	}
	return pKnowledgeKnowledgeRouteTraceItem
}
func ToKnowledgeRouteTraceItemList(source []*entity2.KnowledgeRouteTrace) []*knowledge.KnowledgeRouteTraceItem {
	var pKnowledgeKnowledgeRouteTraceItemList []*knowledge.KnowledgeRouteTraceItem
	if source != nil {
		pKnowledgeKnowledgeRouteTraceItemList = make([]*knowledge.KnowledgeRouteTraceItem, len(source))
		for i := 0; i < len(source); i++ {
			pKnowledgeKnowledgeRouteTraceItemList[i] = ToKnowledgeRouteTraceItem(source[i])
		}
	}
	return pKnowledgeKnowledgeRouteTraceItemList
}
func ToKnowledgeRouteTraceModel(source *entity2.KnowledgeRouteTrace) *model.KnowledgeRouteTrace {
	var pModelKnowledgeRouteTrace *model.KnowledgeRouteTrace
	if source != nil {
		var modelKnowledgeRouteTrace model.KnowledgeRouteTrace
		modelKnowledgeRouteTrace.Model = entityKnowledgeRouteTraceToCommonModel((*source))
		modelKnowledgeRouteTrace.ConversationId = NormalizeString((*source).ConversationId)
		modelKnowledgeRouteTrace.ExchangeId = (*source).ExchangeId
		modelKnowledgeRouteTrace.Question = NormalizeString((*source).Question)
		modelKnowledgeRouteTrace.RewriteQuestion = NormalizeString((*source).RewriteQuestion)
		modelKnowledgeRouteTrace.Mode = NormalizeString((*source).Mode)
		modelKnowledgeRouteTrace.TopScopesJson = NormalizeString((*source).TopScopesJson)
		modelKnowledgeRouteTrace.TopTopicsJson = NormalizeString((*source).TopTopicsJson)
		modelKnowledgeRouteTrace.TopDocumentsJson = NormalizeString((*source).TopDocumentsJson)
		modelKnowledgeRouteTrace.SelectedDocumentId = (*source).SelectedDocumentId
		modelKnowledgeRouteTrace.HitSelectedDocument = (*source).HitSelectedDocument
		modelKnowledgeRouteTrace.Confidence = (*source).Confidence
		modelKnowledgeRouteTrace.RouteStatus = (*source).RouteStatus
		modelKnowledgeRouteTrace.ErrorMsg = NormalizeString((*source).ErrorMsg)
		pModelKnowledgeRouteTrace = &modelKnowledgeRouteTrace
	}
	return pModelKnowledgeRouteTrace
}
func ToKnowledgeScopeNodeModel(source *entity2.KnowledgeScopeNode) *model.KnowledgeScopeNode {
	var pModelKnowledgeScopeNode *model.KnowledgeScopeNode
	if source != nil {
		var modelKnowledgeScopeNode model.KnowledgeScopeNode
		modelKnowledgeScopeNode.Model = entityKnowledgeScopeNodeToCommonModel((*source))
		modelKnowledgeScopeNode.ScopeName = NormalizeString((*source).ScopeName)
		modelKnowledgeScopeNode.Description = NormalizeString((*source).Description)
		modelKnowledgeScopeNode.Aliases = NormalizeString((*source).Aliases)
		modelKnowledgeScopeNode.Examples = NormalizeString((*source).Examples)
		modelKnowledgeScopeNode.SortOrder = (*source).SortOrder
		pModelKnowledgeScopeNode = &modelKnowledgeScopeNode
	}
	return pModelKnowledgeScopeNode
}
func ToKnowledgeScopeResp(source *entity2.KnowledgeScopeNode) *knowledge.KnowledgeScopeResp {
	var pKnowledgeKnowledgeScopeResp *knowledge.KnowledgeScopeResp
	if source != nil {
		var knowledgeKnowledgeScopeResp knowledge.KnowledgeScopeResp
		knowledgeKnowledgeScopeResp.ID = Int64ToString((*source).ID)
		knowledgeKnowledgeScopeResp.ScopeCode = NormalizeString((*source).ScopeCode)
		knowledgeKnowledgeScopeResp.ScopeName = NormalizeString((*source).ScopeName)
		knowledgeKnowledgeScopeResp.ParentScopeCode = NormalizeString((*source).ParentScopeCode)
		knowledgeKnowledgeScopeResp.Description = NormalizeString((*source).Description)
		knowledgeKnowledgeScopeResp.Aliases = NormalizeString((*source).Aliases)
		knowledgeKnowledgeScopeResp.Examples = NormalizeString((*source).Examples)
		knowledgeKnowledgeScopeResp.SortOrder = (*source).SortOrder
		pKnowledgeKnowledgeScopeResp = &knowledgeKnowledgeScopeResp
	}
	return pKnowledgeKnowledgeScopeResp
}
func ToKnowledgeScopeRespList(source []*entity2.KnowledgeScopeNode) []*knowledge.KnowledgeScopeResp {
	var pKnowledgeKnowledgeScopeRespList []*knowledge.KnowledgeScopeResp
	if source != nil {
		pKnowledgeKnowledgeScopeRespList = make([]*knowledge.KnowledgeScopeResp, len(source))
		for i := 0; i < len(source); i++ {
			pKnowledgeKnowledgeScopeRespList[i] = ToKnowledgeScopeResp(source[i])
		}
	}
	return pKnowledgeKnowledgeScopeRespList
}
func ToKnowledgeTopicDocumentRelationModel(source *entity2.KnowledgeTopicDocumentRelation) *model.KnowledgeTopicDocumentRelation {
	var pModelKnowledgeTopicDocumentRelation *model.KnowledgeTopicDocumentRelation
	if source != nil {
		var modelKnowledgeTopicDocumentRelation model.KnowledgeTopicDocumentRelation
		modelKnowledgeTopicDocumentRelation.Model = entityKnowledgeTopicDocumentRelationToCommonModel((*source))
		modelKnowledgeTopicDocumentRelation.TopicCode = NormalizeString((*source).TopicCode)
		modelKnowledgeTopicDocumentRelation.DocumentId = (*source).DocumentId
		modelKnowledgeTopicDocumentRelation.RelationScore = (*source).RelationScore
		modelKnowledgeTopicDocumentRelation.RelationSource = NormalizeString((*source).RelationSource)
		modelKnowledgeTopicDocumentRelation.Reason = NormalizeString((*source).Reason)
		pModelKnowledgeTopicDocumentRelation = &modelKnowledgeTopicDocumentRelation
	}
	return pModelKnowledgeTopicDocumentRelation
}
func ToKnowledgeTopicNodeModel(source *entity2.KnowledgeTopicNode) *model.KnowledgeTopicNode {
	var pModelKnowledgeTopicNode *model.KnowledgeTopicNode
	if source != nil {
		var modelKnowledgeTopicNode model.KnowledgeTopicNode
		modelKnowledgeTopicNode.Model = entityKnowledgeTopicNodeToCommonModel((*source))
		modelKnowledgeTopicNode.TopicName = NormalizeString((*source).TopicName)
		modelKnowledgeTopicNode.Description = NormalizeString((*source).Description)
		modelKnowledgeTopicNode.Aliases = NormalizeString((*source).Aliases)
		modelKnowledgeTopicNode.Examples = NormalizeString((*source).Examples)
		modelKnowledgeTopicNode.AnswerShape = NormalizeString((*source).AnswerShape)
		modelKnowledgeTopicNode.ExecutionPreference = NormalizeString((*source).ExecutionPreference)
		modelKnowledgeTopicNode.SortOrder = (*source).SortOrder
		pModelKnowledgeTopicNode = &modelKnowledgeTopicNode
	}
	return pModelKnowledgeTopicNode
}
func ToKnowledgeTopicResp(source *entity2.KnowledgeTopicNode) *knowledge.KnowledgeTopicResp {
	var pKnowledgeKnowledgeTopicResp *knowledge.KnowledgeTopicResp
	if source != nil {
		var knowledgeKnowledgeTopicResp knowledge.KnowledgeTopicResp
		knowledgeKnowledgeTopicResp.ID = Int64ToString((*source).ID)
		knowledgeKnowledgeTopicResp.TopicCode = NormalizeString((*source).TopicCode)
		knowledgeKnowledgeTopicResp.TopicName = NormalizeString((*source).TopicName)
		knowledgeKnowledgeTopicResp.ScopeCode = NormalizeString((*source).ScopeCode)
		knowledgeKnowledgeTopicResp.Description = NormalizeString((*source).Description)
		knowledgeKnowledgeTopicResp.Aliases = NormalizeString((*source).Aliases)
		knowledgeKnowledgeTopicResp.Examples = NormalizeString((*source).Examples)
		knowledgeKnowledgeTopicResp.AnswerShape = NormalizeString((*source).AnswerShape)
		knowledgeKnowledgeTopicResp.ExecutionPreference = NormalizeString((*source).ExecutionPreference)
		knowledgeKnowledgeTopicResp.SortOrder = (*source).SortOrder
		pKnowledgeKnowledgeTopicResp = &knowledgeKnowledgeTopicResp
	}
	return pKnowledgeKnowledgeTopicResp
}
func ToKnowledgeTopicRespList(source []*entity2.KnowledgeTopicNode) []*knowledge.KnowledgeTopicResp {
	var pKnowledgeKnowledgeTopicRespList []*knowledge.KnowledgeTopicResp
	if source != nil {
		pKnowledgeKnowledgeTopicRespList = make([]*knowledge.KnowledgeTopicResp, len(source))
		for i := 0; i < len(source); i++ {
			pKnowledgeKnowledgeTopicRespList[i] = ToKnowledgeTopicResp(source[i])
		}
	}
	return pKnowledgeKnowledgeTopicRespList
}
func ToTopicDocumentRelationResp(source *entity2.KnowledgeTopicDocumentRelation) *knowledge.TopicDocumentRelationResp {
	var pKnowledgeTopicDocumentRelationResp *knowledge.TopicDocumentRelationResp
	if source != nil {
		var knowledgeTopicDocumentRelationResp knowledge.TopicDocumentRelationResp
		knowledgeTopicDocumentRelationResp.TopicCode = NormalizeString((*source).TopicCode)
		knowledgeTopicDocumentRelationResp.DocumentId = Int64ToString((*source).DocumentId)
		knowledgeTopicDocumentRelationResp.DocumentName = NormalizeString((*source).DocumentName)
		knowledgeTopicDocumentRelationResp.KnowledgeScopeCode = NormalizeString((*source).KnowledgeScopeCode)
		knowledgeTopicDocumentRelationResp.KnowledgeScopeName = NormalizeString((*source).KnowledgeScopeName)
		knowledgeTopicDocumentRelationResp.BusinessCategory = NormalizeString((*source).BusinessCategory)
		knowledgeTopicDocumentRelationResp.DocumentTags = NormalizeString((*source).DocumentTags)
		knowledgeTopicDocumentRelationResp.RelationScore = (*source).RelationScore
		knowledgeTopicDocumentRelationResp.RelationSource = NormalizeString((*source).RelationSource)
		knowledgeTopicDocumentRelationResp.Reason = NormalizeString((*source).Reason)
		pKnowledgeTopicDocumentRelationResp = &knowledgeTopicDocumentRelationResp
	}
	return pKnowledgeTopicDocumentRelationResp
}
func ToTopicDocumentRelationRespList(source []*entity2.KnowledgeTopicDocumentRelation) []*knowledge.TopicDocumentRelationResp {
	var pKnowledgeTopicDocumentRelationRespList []*knowledge.TopicDocumentRelationResp
	if source != nil {
		pKnowledgeTopicDocumentRelationRespList = make([]*knowledge.TopicDocumentRelationResp, len(source))
		for i := 0; i < len(source); i++ {
			pKnowledgeTopicDocumentRelationRespList[i] = ToTopicDocumentRelationResp(source[i])
		}
	}
	return pKnowledgeTopicDocumentRelationRespList
}
func datatypesJSONToJsonRawMessage(source datatypes.JSON) json.RawMessage {
	var jsonRawMessage json.RawMessage
	if source != nil {
		jsonRawMessage = make(json.RawMessage, len(source))
		for i := 0; i < len(source); i++ {
			jsonRawMessage[i] = source[i]
		}
	}
	return jsonRawMessage
}
func entityKnowledgeBaseToCommonModel(source entity2.KnowledgeBase) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityKnowledgeRouteTraceToCommonModel(source entity2.KnowledgeRouteTrace) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityKnowledgeScopeNodeToCommonModel(source entity2.KnowledgeScopeNode) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityKnowledgeTopicDocumentRelationToCommonModel(source entity2.KnowledgeTopicDocumentRelation) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityKnowledgeTopicNodeToCommonModel(source entity2.KnowledgeTopicNode) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func jsonRawMessageToDatatypesJSON(source json.RawMessage) datatypes.JSON {
	var datatypesJSON datatypes.JSON
	if source != nil {
		datatypesJSON = make(datatypes.JSON, len(source))
		for i := 0; i < len(source); i++ {
			datatypesJSON[i] = source[i]
		}
	}
	return datatypesJSON
}
func jsonRawMessageToJsonRawMessage(source json.RawMessage) json.RawMessage {
	return source
}
func pEntityKnowledgeBaseToPVoKnowledgeBase(source *entity2.KnowledgeBase) *vo.KnowledgeBase {
	var pVoKnowledgeBase *vo.KnowledgeBase
	if source != nil {
		var voKnowledgeBase vo.KnowledgeBase
		voKnowledgeBase.ID = (*source).ID
		voKnowledgeBase.BaseName = NormalizeString((*source).BaseName)
		voKnowledgeBase.Description = NormalizeString((*source).Description)
		voKnowledgeBase.EmbeddingModel = NormalizeString((*source).EmbeddingModel)
		voKnowledgeBase.RetrievalConfigJson = jsonRawMessageToJsonRawMessage((*source).RetrievalConfigJson)
		voKnowledgeBase.GraphRagConfigJson = jsonRawMessageToJsonRawMessage((*source).GraphRagConfigJson)
		voKnowledgeBase.RaptorConfigJson = jsonRawMessageToJsonRawMessage((*source).RaptorConfigJson)
		voKnowledgeBase.MetadataFilterJson = jsonRawMessageToJsonRawMessage((*source).MetadataFilterJson)
		voKnowledgeBase.IsDefault = (*source).IsDefault
		voKnowledgeBase.SortOrder = (*source).SortOrder
		pVoKnowledgeBase = &voKnowledgeBase
	}
	return pVoKnowledgeBase
}
func pVoDocumentMetadataToPVoDocumentMetadata(source *vo2.DocumentMetadata) *vo.DocumentMetadata {
	var pVoDocumentMetadata *vo.DocumentMetadata
	if source != nil {
		var voDocumentMetadata vo.DocumentMetadata
		voDocumentMetadata.DocumentId = (*source).DocumentId
		voDocumentMetadata.DocumentName = NormalizeString((*source).DocumentName)
		voDocumentMetadata.KnowledgeBaseId = (*source).KnowledgeBaseId
		voDocumentMetadata.KnowledgeBaseName = NormalizeString((*source).KnowledgeBaseName)
		voDocumentMetadata.LastIndexTaskId = (*source).LastIndexTaskId
		pVoDocumentMetadata = &voDocumentMetadata
	}
	return pVoDocumentMetadata
}
func pVoHybridOptionsToPVoHybridOptions(source *vo2.HybridOptions) *vo.HybridOptions {
	var pVoHybridOptions *vo.HybridOptions
	if source != nil {
		var voHybridOptions vo.HybridOptions
		voHybridOptions.VectorWeight = (*source).VectorWeight
		voHybridOptions.KeywordWeight = (*source).KeywordWeight
		voHybridOptions.TableWeight = (*source).TableWeight
		voHybridOptions.GraphRagWeight = (*source).GraphRagWeight
		voHybridOptions.RaptorWeight = (*source).RaptorWeight
		voHybridOptions.RankWeight = (*source).RankWeight
		voHybridOptions.OriginalScoreWeight = (*source).OriginalScoreWeight
		voHybridOptions.MetadataBoostWeight = (*source).MetadataBoostWeight
		voHybridOptions.MaxMetadataBoost = (*source).MaxMetadataBoost
		pVoHybridOptions = &voHybridOptions
	}
	return pVoHybridOptions
}
func pVoRagRuntimeOptionsToPVoRagRuntimeOptions(source *vo2.RagRuntimeOptions) *vo.RagRuntimeOptions {
	var pVoRagRuntimeOptions *vo.RagRuntimeOptions
	if source != nil {
		var voRagRuntimeOptions vo.RagRuntimeOptions
		voRagRuntimeOptions.VectorTopK = (*source).VectorTopK
		voRagRuntimeOptions.KeywordTopK = (*source).KeywordTopK
		voRagRuntimeOptions.GraphRagTopK = (*source).GraphRagTopK
		voRagRuntimeOptions.GraphRagMaxHops = (*source).GraphRagMaxHops
		voRagRuntimeOptions.RaptorTopK = (*source).RaptorTopK
		voRagRuntimeOptions.RaptorSourceChunkTopK = (*source).RaptorSourceChunkTopK
		voRagRuntimeOptions.CandidateTopK = (*source).CandidateTopK
		voRagRuntimeOptions.RerankCandidateTopK = (*source).RerankCandidateTopK
		voRagRuntimeOptions.FinalTopK = (*source).FinalTopK
		voRagRuntimeOptions.RerankEnabled = (*source).RerankEnabled
		voRagRuntimeOptions.ChannelTimeout = timeDurationToTimeDuration((*source).ChannelTimeout)
		voRagRuntimeOptions.SubQuestionTimeout = timeDurationToTimeDuration((*source).SubQuestionTimeout)
		voRagRuntimeOptions.MinVectorSimilarity = (*source).MinVectorSimilarity
		voRagRuntimeOptions.KeywordRelativeScoreFloor = (*source).KeywordRelativeScoreFloor
		voRagRuntimeOptions.KeywordChannelEnabled = (*source).KeywordChannelEnabled
		voRagRuntimeOptions.TableChannelEnabled = (*source).TableChannelEnabled
		voRagRuntimeOptions.GraphRagChannelEnabled = (*source).GraphRagChannelEnabled
		voRagRuntimeOptions.RaptorChannelEnabled = (*source).RaptorChannelEnabled
		voRagRuntimeOptions.Hybrid = pVoHybridOptionsToPVoHybridOptions((*source).Hybrid)
		voRagRuntimeOptions.KbConfigConflictFields = (*source).KbConfigConflictFields
		pVoRagRuntimeOptions = &voRagRuntimeOptions
	}
	return pVoRagRuntimeOptions
}
func timeDurationToTimeDuration(source time.Duration) time.Duration {
	return source
}
