// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package convert

import (
	chat "github.com/swiftbit/know-agent/api/chat"
	document "github.com/swiftbit/know-agent/api/document"
	knowledge "github.com/swiftbit/know-agent/api/knowledge"
	common "github.com/swiftbit/know-agent/common"
	entity "github.com/swiftbit/know-agent/internal/domain/chat/model/entity"
	vo "github.com/swiftbit/know-agent/internal/domain/chat/model/vo"
	aggregate "github.com/swiftbit/know-agent/internal/domain/document/model/aggregate"
	entity1 "github.com/swiftbit/know-agent/internal/domain/document/model/entity"
	vo1 "github.com/swiftbit/know-agent/internal/domain/document/model/vo"
	entity2 "github.com/swiftbit/know-agent/internal/domain/knowledge/model/entity"
	model "github.com/swiftbit/know-agent/internal/infrastructure/model"
	"time"
)

func FromChatReq(source *chat.ChatReq) *vo.ChatCommand {
	var pVoChatCommand *vo.ChatCommand
	if source != nil {
		var voChatCommand vo.ChatCommand
		voChatCommand.Question = (*source).Question
		voChatCommand.ConversationId = (*source).ConversationId
		voChatCommand.ChatMode = ToChatQueryMode((*source).ChatMode)
		voChatCommand.SelectedDocumentId = (*source).SelectedDocumentId
		pVoChatCommand = &voChatCommand
	}
	return pVoChatCommand
}
func ToChannelExecutionResp(source *vo.ChatChannelExecution) *chat.ChannelExecutionResp {
	var pChatChannelExecutionResp *chat.ChannelExecutionResp
	if source != nil {
		var chatChannelExecutionResp chat.ChannelExecutionResp
		chatChannelExecutionResp.ID = (*source).ID
		chatChannelExecutionResp.ConversationId = (*source).ConversationId
		chatChannelExecutionResp.ExchangeId = (*source).ExchangeId
		chatChannelExecutionResp.TraceId = (*source).TraceId
		chatChannelExecutionResp.SubQuestionIndex = (*source).SubQuestionIndex
		chatChannelExecutionResp.SubQuestion = (*source).SubQuestion
		chatChannelExecutionResp.ChannelType = (*source).ChannelType
		chatChannelExecutionResp.ExecutionState = (*source).ExecutionState
		chatChannelExecutionResp.StartTime = TimeToStringMs((*source).StartTime)
		chatChannelExecutionResp.EndTime = TimeToStringMs((*source).EndTime)
		chatChannelExecutionResp.DurationMs = (*source).DurationMs
		chatChannelExecutionResp.RecalledCount = (*source).RecalledCount
		chatChannelExecutionResp.AcceptedCount = (*source).AcceptedCount
		chatChannelExecutionResp.FinalSelectedCount = (*source).FinalSelectedCount
		chatChannelExecutionResp.AvgScore = (*source).AvgScore
		chatChannelExecutionResp.MaxScore = (*source).MaxScore
		chatChannelExecutionResp.MinScore = (*source).MinScore
		chatChannelExecutionResp.ErrorMessage = (*source).ErrorMessage
		chatChannelExecutionResp.CreateTime = TimeToString((*source).CreateTime)
		pChatChannelExecutionResp = &chatChannelExecutionResp
	}
	return pChatChannelExecutionResp
}
func ToChannelExecutionRespList(source []*vo.ChatChannelExecution) []*chat.ChannelExecutionResp {
	var pChatChannelExecutionRespList []*chat.ChannelExecutionResp
	if source != nil {
		pChatChannelExecutionRespList = make([]*chat.ChannelExecutionResp, len(source))
		for i := 0; i < len(source); i++ {
			pChatChannelExecutionRespList[i] = ToChannelExecutionResp(source[i])
		}
	}
	return pChatChannelExecutionRespList
}
func ToChatChannelExecutionModelList(source []*vo.ChatChannelExecution) []*model.ChatChannelExecution {
	var pModelChatChannelExecutionList []*model.ChatChannelExecution
	if source != nil {
		pModelChatChannelExecutionList = make([]*model.ChatChannelExecution, len(source))
		for i := 0; i < len(source); i++ {
			pModelChatChannelExecutionList[i] = pVoChatChannelExecutionToPModelChatChannelExecution(source[i])
		}
	}
	return pModelChatChannelExecutionList
}
func ToChatDialogueModel(source *entity.ChatDialogue) *model.ChatDialogue {
	var pModelChatDialogue *model.ChatDialogue
	if source != nil {
		var modelChatDialogue model.ChatDialogue
		modelChatDialogue.ID = (*source).ID
		modelChatDialogue.ConversationId = (*source).ConversationId
		modelChatDialogue.SessionStatus = (*source).SessionStatus
		modelChatDialogue.ChatMode = (*source).ChatMode
		modelChatDialogue.SelectedDocumentId = (*source).SelectedDocumentId
		modelChatDialogue.SelectedDocumentName = (*source).SelectedDocumentName
		pModelChatDialogue = &modelChatDialogue
	}
	return pModelChatDialogue
}
func ToChatExchangeModel(source *entity.ChatExchange) *model.ChatExchange {
	var pModelChatExchange *model.ChatExchange
	if source != nil {
		var modelChatExchange model.ChatExchange
		modelChatExchange.ID = (*source).ID
		modelChatExchange.ConversationId = (*source).ConversationId
		modelChatExchange.Question = (*source).Question
		modelChatExchange.Answer = (*source).Answer
		modelChatExchange.ThinkingSteps = commonJSONArrayToCommonJSONArray((*source).ThinkingSteps)
		modelChatExchange.References = commonJSONArrayToCommonJSONArray((*source).References)
		modelChatExchange.Recommendations = commonJSONArrayToCommonJSONArray((*source).Recommendations)
		modelChatExchange.UsedTools = commonJSONArrayToCommonJSONArray((*source).UsedTools)
		modelChatExchange.DebugTraceJson = (*source).DebugTraceJson
		modelChatExchange.TurnStatus = (*source).TurnStatus
		modelChatExchange.ErrorMessage = (*source).ErrorMessage
		modelChatExchange.FirstResponseTimeMs = (*source).FirstResponseTimeMs
		modelChatExchange.TotalResponseTimeMs = (*source).TotalResponseTimeMs
		pModelChatExchange = &modelChatExchange
	}
	return pModelChatExchange
}
func ToChatExchangeTraceStageModel(source *entity.ChatExchangeTraceStage) *model.ChatExchangeTraceStage {
	var pModelChatExchangeTraceStage *model.ChatExchangeTraceStage
	if source != nil {
		var modelChatExchangeTraceStage model.ChatExchangeTraceStage
		modelChatExchangeTraceStage.ID = (*source).ID
		modelChatExchangeTraceStage.ConversationId = (*source).ConversationId
		modelChatExchangeTraceStage.ExchangeId = (*source).ExchangeId
		modelChatExchangeTraceStage.TraceId = (*source).TraceId
		modelChatExchangeTraceStage.StageCode = (*source).StageCode
		modelChatExchangeTraceStage.StageName = (*source).StageName
		modelChatExchangeTraceStage.StageOrder = (*source).StageOrder
		modelChatExchangeTraceStage.StageLevel = (*source).StageLevel
		modelChatExchangeTraceStage.ParentStageId = (*source).ParentStageId
		modelChatExchangeTraceStage.ExecutionMode = (*source).ExecutionMode
		modelChatExchangeTraceStage.StageState = (*source).StageState
		modelChatExchangeTraceStage.StartTime = timeTimeToTimeTime((*source).StartTime)
		modelChatExchangeTraceStage.EndTime = timeTimeToTimeTime((*source).EndTime)
		modelChatExchangeTraceStage.DurationMs = (*source).DurationMs
		modelChatExchangeTraceStage.SummaryText = (*source).SummaryText
		modelChatExchangeTraceStage.ErrorMessage = (*source).ErrorMessage
		modelChatExchangeTraceStage.SnapshotJson = (*source).SnapshotJson
		pModelChatExchangeTraceStage = &modelChatExchangeTraceStage
	}
	return pModelChatExchangeTraceStage
}
func ToChatMemorySummaryModel(source *entity.ChatMemorySummary) *model.ChatMemorySummary {
	var pModelChatMemorySummary *model.ChatMemorySummary
	if source != nil {
		var modelChatMemorySummary model.ChatMemorySummary
		modelChatMemorySummary.ID = (*source).ID
		modelChatMemorySummary.ConversationId = (*source).ConversationId
		modelChatMemorySummary.CoveredExchangeId = (*source).CoveredExchangeId
		modelChatMemorySummary.CoveredExchangeCount = (*source).CoveredExchangeCount
		modelChatMemorySummary.CompressionCount = (*source).CompressionCount
		modelChatMemorySummary.SummaryVersion = (*source).SummaryVersion
		modelChatMemorySummary.SummaryText = (*source).SummaryText
		modelChatMemorySummary.SummaryJson = (*source).SummaryJson
		modelChatMemorySummary.LastSourceUpdateTime = timeTimeToTimeTime((*source).LastSourceUpdateTime)
		pModelChatMemorySummary = &modelChatMemorySummary
	}
	return pModelChatMemorySummary
}
func ToChatRetrievalResultModelList(source []*vo.ChatRetrievalResult) []*model.ChatRetrievalResult {
	var pModelChatRetrievalResultList []*model.ChatRetrievalResult
	if source != nil {
		pModelChatRetrievalResultList = make([]*model.ChatRetrievalResult, len(source))
		for i := 0; i < len(source); i++ {
			pModelChatRetrievalResultList[i] = pVoChatRetrievalResultToPModelChatRetrievalResult(source[i])
		}
	}
	return pModelChatRetrievalResultList
}
func ToConversationExchangeResp(source *entity.ChatExchange) *chat.ConversationExchangeResp {
	var pChatConversationExchangeResp *chat.ConversationExchangeResp
	if source != nil {
		var chatConversationExchangeResp chat.ConversationExchangeResp
		chatConversationExchangeResp.ID = (*source).ID
		chatConversationExchangeResp.Question = (*source).Question
		chatConversationExchangeResp.Answer = (*source).Answer
		chatConversationExchangeResp.ThinkingSteps = JsonArrayToStringSlice((*source).ThinkingSteps)
		chatConversationExchangeResp.References = JsonArrayToSearchReferences((*source).References)
		chatConversationExchangeResp.Recommendations = JsonArrayToStringSlice((*source).Recommendations)
		chatConversationExchangeResp.UsedTools = JsonArrayToStringSlice((*source).UsedTools)
		chatConversationExchangeResp.DebugTraceJson = (*source).DebugTraceJson
		chatConversationExchangeResp.TurnStatus = (*source).TurnStatus
		chatConversationExchangeResp.ErrorMessage = (*source).ErrorMessage
		chatConversationExchangeResp.FirstResponseTimeMs = (*source).FirstResponseTimeMs
		chatConversationExchangeResp.TotalResponseTimeMs = (*source).TotalResponseTimeMs
		chatConversationExchangeResp.CreateTime = TimeToString((*source).CreateTime)
		chatConversationExchangeResp.UpdateTime = TimeToString((*source).UpdateTime)
		pChatConversationExchangeResp = &chatConversationExchangeResp
	}
	return pChatConversationExchangeResp
}
func ToConversationMemorySummaryResp(source *entity.ChatMemorySummary) *chat.ConversationMemorySummaryResp {
	var pChatConversationMemorySummaryResp *chat.ConversationMemorySummaryResp
	if source != nil {
		var chatConversationMemorySummaryResp chat.ConversationMemorySummaryResp
		chatConversationMemorySummaryResp.ConversationId = (*source).ConversationId
		chatConversationMemorySummaryResp.IsCompressed = (*source).IsCompressed
		chatConversationMemorySummaryResp.CoveredExchangeId = (*source).CoveredExchangeId
		chatConversationMemorySummaryResp.CoveredExchangeCount = (*source).CoveredExchangeCount
		chatConversationMemorySummaryResp.CompressionCount = (*source).CompressionCount
		chatConversationMemorySummaryResp.SummaryVersion = (*source).SummaryVersion
		chatConversationMemorySummaryResp.SummaryText = (*source).SummaryText
		chatConversationMemorySummaryResp.SummaryPayload = pEntityConversationSummaryToPChatConversationSummary((*source).SummaryPayload)
		chatConversationMemorySummaryResp.LastSourceUpdateTime = TimeToString((*source).LastSourceUpdateTime)
		chatConversationMemorySummaryResp.UpdateTime = TimeToStringMs((*source).UpdateTime)
		pChatConversationMemorySummaryResp = &chatConversationMemorySummaryResp
	}
	return pChatConversationMemorySummaryResp
}
func ToConversationResetResp(source *vo.ConversationReset) *chat.ConversationResetResp {
	var pChatConversationResetResp *chat.ConversationResetResp
	if source != nil {
		var chatConversationResetResp chat.ConversationResetResp
		chatConversationResetResp.ConversationId = (*source).ConversationId
		chatConversationResetResp.RemovedDialogueCount = (*source).RemovedDialogueCount
		chatConversationResetResp.RemovedExchangeCount = (*source).RemovedExchangeCount
		chatConversationResetResp.RemovedCheckpointCount = (*source).RemovedCheckpointCount
		chatConversationResetResp.Message = (*source).Message
		pChatConversationResetResp = &chatConversationResetResp
	}
	return pChatConversationResetResp
}
func ToConversationSessionResp(source *vo.ConversationArchiveRecord) *chat.ConversationSessionResp {
	var pChatConversationSessionResp *chat.ConversationSessionResp
	if source != nil {
		var chatConversationSessionResp chat.ConversationSessionResp
		chatConversationSessionResp.ConversationId = (*source).ConversationId
		chatConversationSessionResp.Running = (*source).Running
		chatConversationSessionResp.CheckpointCount = (*source).CheckpointCount
		chatConversationSessionResp.MessageCount = (*source).MessageCount
		chatConversationSessionResp.LatestUserMessage = (*source).LatestUserMessage
		chatConversationSessionResp.LatestAssistantMessage = (*source).LatestAssistantMessage
		chatConversationSessionResp.LatestExchangeId = (*source).LatestExchangeId
		chatConversationSessionResp.LatestTurnStatus = (*source).LatestTurnStatus
		chatConversationSessionResp.LatestTurnErrorMessage = (*source).LatestTurnErrorMessage
		chatConversationSessionResp.ChatMode = ToChatQueryModeName((*source).ChatMode)
		chatConversationSessionResp.SelectedDocumentId = (*source).SelectedDocumentId
		chatConversationSessionResp.SelectedDocumentName = (*source).SelectedDocumentName
		chatConversationSessionResp.CreatedTime = TimeToString((*source).CreatedTime)
		chatConversationSessionResp.UpdatedTime = TimeToString((*source).UpdatedTime)
		if (*source).Exchanges != nil {
			chatConversationSessionResp.Exchanges = make([]*chat.ConversationExchangeResp, len((*source).Exchanges))
			for i := 0; i < len((*source).Exchanges); i++ {
				chatConversationSessionResp.Exchanges[i] = ToConversationExchangeResp((*source).Exchanges[i])
			}
		}
		chatConversationSessionResp.MemorySummary = ToConversationMemorySummaryResp((*source).MemorySummary)
		pChatConversationSessionResp = &chatConversationSessionResp
	}
	return pChatConversationSessionResp
}
func ToConversationSessionRespList(source []*vo.ConversationArchiveRecord) []*chat.ConversationSessionResp {
	var pChatConversationSessionRespList []*chat.ConversationSessionResp
	if source != nil {
		pChatConversationSessionRespList = make([]*chat.ConversationSessionResp, len(source))
		for i := 0; i < len(source); i++ {
			pChatConversationSessionRespList[i] = ToConversationSessionResp(source[i])
		}
	}
	return pChatConversationSessionRespList
}
func ToConversationStageTraceRespList(source []*entity.ChatExchangeTraceStage) []*chat.ConversationTraceStageResp {
	var pChatConversationTraceStageRespList []*chat.ConversationTraceStageResp
	if source != nil {
		pChatConversationTraceStageRespList = make([]*chat.ConversationTraceStageResp, len(source))
		for i := 0; i < len(source); i++ {
			pChatConversationTraceStageRespList[i] = pEntityChatExchangeTraceStageToPChatConversationTraceStageResp(source[i])
		}
	}
	return pChatConversationTraceStageRespList
}
func ToRetrievalResultRespList(source []*vo.ChatRetrievalResult) []*chat.RetrievalResultResp {
	var pChatRetrievalResultRespList []*chat.RetrievalResultResp
	if source != nil {
		pChatRetrievalResultRespList = make([]*chat.RetrievalResultResp, len(source))
		for i := 0; i < len(source); i++ {
			pChatRetrievalResultRespList[i] = pVoChatRetrievalResultToPChatRetrievalResultResp(source[i])
		}
	}
	return pChatRetrievalResultRespList
}
func commonJSONArrayToCommonJSONArray(source common.JSONArray) common.JSONArray {
	return source
}
func pEntityChatExchangeTraceStageToPChatConversationTraceStageResp(source *entity.ChatExchangeTraceStage) *chat.ConversationTraceStageResp {
	var pChatConversationTraceStageResp *chat.ConversationTraceStageResp
	if source != nil {
		var chatConversationTraceStageResp chat.ConversationTraceStageResp
		chatConversationTraceStageResp.ID = (*source).ID
		chatConversationTraceStageResp.TraceId = (*source).TraceId
		chatConversationTraceStageResp.StageCode = (*source).StageCode
		chatConversationTraceStageResp.StageName = (*source).StageName
		chatConversationTraceStageResp.StageOrder = (*source).StageOrder
		chatConversationTraceStageResp.StageLevel = (*source).StageLevel
		chatConversationTraceStageResp.ParentStageId = (*source).ParentStageId
		chatConversationTraceStageResp.ExecutionMode = (*source).ExecutionMode
		chatConversationTraceStageResp.StageState = ToChatQueryModeName((*source).StageState)
		chatConversationTraceStageResp.StartTime = TimeToString((*source).StartTime)
		chatConversationTraceStageResp.EndTime = TimeToString((*source).EndTime)
		chatConversationTraceStageResp.DurationMs = (*source).DurationMs
		if (*source).SummaryText != nil {
			chatConversationTraceStageResp.SummaryText = *(*source).SummaryText
		}
		if (*source).ErrorMessage != nil {
			chatConversationTraceStageResp.ErrorMessage = *(*source).ErrorMessage
		}
		if (*source).SnapshotJson != nil {
			chatConversationTraceStageResp.SnapshotJson = *(*source).SnapshotJson
		}
		pChatConversationTraceStageResp = &chatConversationTraceStageResp
	}
	return pChatConversationTraceStageResp
}
func pEntityConversationSummaryToPChatConversationSummary(source *entity.ConversationSummary) *chat.ConversationSummary {
	var pChatConversationSummary *chat.ConversationSummary
	if source != nil {
		var chatConversationSummary chat.ConversationSummary
		chatConversationSummary.Summary = (*source).Summary
		chatConversationSummary.ConversationGoal = (*source).ConversationGoal
		chatConversationSummary.StableFacts = (*source).StableFacts
		chatConversationSummary.UserPreferences = (*source).UserPreferences
		chatConversationSummary.ResolvedPoints = (*source).ResolvedPoints
		chatConversationSummary.PendingQuestions = (*source).PendingQuestions
		chatConversationSummary.RetrievalHints = (*source).RetrievalHints
		pChatConversationSummary = &chatConversationSummary
	}
	return pChatConversationSummary
}
func pVoChatChannelExecutionToPModelChatChannelExecution(source *vo.ChatChannelExecution) *model.ChatChannelExecution {
	var pModelChatChannelExecution *model.ChatChannelExecution
	if source != nil {
		var modelChatChannelExecution model.ChatChannelExecution
		modelChatChannelExecution.ID = (*source).ID
		modelChatChannelExecution.ConversationId = (*source).ConversationId
		modelChatChannelExecution.ExchangeId = (*source).ExchangeId
		modelChatChannelExecution.TraceId = (*source).TraceId
		modelChatChannelExecution.SubQuestionIndex = (*source).SubQuestionIndex
		modelChatChannelExecution.SubQuestion = (*source).SubQuestion
		modelChatChannelExecution.ChannelType = (*source).ChannelType
		modelChatChannelExecution.ExecutionState = (*source).ExecutionState
		modelChatChannelExecution.StartTime = timeTimeToTimeTime((*source).StartTime)
		modelChatChannelExecution.EndTime = timeTimeToTimeTime((*source).EndTime)
		modelChatChannelExecution.DurationMs = (*source).DurationMs
		modelChatChannelExecution.RecalledCount = (*source).RecalledCount
		modelChatChannelExecution.AcceptedCount = (*source).AcceptedCount
		modelChatChannelExecution.FinalSelectedCount = (*source).FinalSelectedCount
		modelChatChannelExecution.AvgScore = (*source).AvgScore
		modelChatChannelExecution.MaxScore = (*source).MaxScore
		modelChatChannelExecution.MinScore = (*source).MinScore
		modelChatChannelExecution.ConfigSnapshot = (*source).ConfigSnapshot
		modelChatChannelExecution.ErrorMessage = (*source).ErrorMessage
		pModelChatChannelExecution = &modelChatChannelExecution
	}
	return pModelChatChannelExecution
}
func pVoChatRetrievalResultToPChatRetrievalResultResp(source *vo.ChatRetrievalResult) *chat.RetrievalResultResp {
	var pChatRetrievalResultResp *chat.RetrievalResultResp
	if source != nil {
		var chatRetrievalResultResp chat.RetrievalResultResp
		chatRetrievalResultResp.ID = (*source).ID
		chatRetrievalResultResp.ConversationId = (*source).ConversationId
		chatRetrievalResultResp.ExchangeId = (*source).ExchangeId
		chatRetrievalResultResp.TraceId = (*source).TraceId
		chatRetrievalResultResp.SubQuestionIndex = (*source).SubQuestionIndex
		chatRetrievalResultResp.SubQuestion = (*source).SubQuestion
		chatRetrievalResultResp.ChannelType = (*source).ChannelType
		chatRetrievalResultResp.ChannelRank = (*source).ChannelRank
		chatRetrievalResultResp.RrfRank = (*source).RrfRank
		chatRetrievalResultResp.FinalRank = (*source).FinalRank
		chatRetrievalResultResp.OriginalScore = (*source).OriginalScore
		chatRetrievalResultResp.RrfScore = (*source).RrfScore
		chatRetrievalResultResp.RerankScore = (*source).RerankScore
		chatRetrievalResultResp.GatePassed = (*source).GatePassed
		chatRetrievalResultResp.IsElevated = (*source).IsElevated
		chatRetrievalResultResp.IsSelected = (*source).IsSelected
		chatRetrievalResultResp.SelectionReason = (*source).SelectionReason
		chatRetrievalResultResp.ChunkId = (*source).ChunkId
		chatRetrievalResultResp.ChunkNo = (*source).ChunkNo
		chatRetrievalResultResp.ParentBlockId = (*source).ParentBlockId
		chatRetrievalResultResp.ParentBlockNo = (*source).ParentBlockNo
		chatRetrievalResultResp.SectionPath = (*source).SectionPath
		chatRetrievalResultResp.ChunkTextPreview = (*source).ChunkTextPreview
		chatRetrievalResultResp.ChunkCharCount = (*source).ChunkCharCount
		chatRetrievalResultResp.CreateTime = TimeToString((*source).CreateTime)
		pChatRetrievalResultResp = &chatRetrievalResultResp
	}
	return pChatRetrievalResultResp
}
func pVoChatRetrievalResultToPModelChatRetrievalResult(source *vo.ChatRetrievalResult) *model.ChatRetrievalResult {
	var pModelChatRetrievalResult *model.ChatRetrievalResult
	if source != nil {
		var modelChatRetrievalResult model.ChatRetrievalResult
		modelChatRetrievalResult.ID = (*source).ID
		modelChatRetrievalResult.ConversationId = (*source).ConversationId
		modelChatRetrievalResult.ExchangeId = (*source).ExchangeId
		modelChatRetrievalResult.TraceId = (*source).TraceId
		modelChatRetrievalResult.SubQuestionIndex = (*source).SubQuestionIndex
		modelChatRetrievalResult.SubQuestion = (*source).SubQuestion
		modelChatRetrievalResult.ChannelType = (*source).ChannelType
		modelChatRetrievalResult.ChannelRank = (*source).ChannelRank
		modelChatRetrievalResult.RrfRank = (*source).RrfRank
		modelChatRetrievalResult.FinalRank = (*source).FinalRank
		modelChatRetrievalResult.OriginalScore = (*source).OriginalScore
		modelChatRetrievalResult.RrfScore = (*source).RrfScore
		modelChatRetrievalResult.RerankScore = (*source).RerankScore
		modelChatRetrievalResult.GatePassed = (*source).GatePassed
		modelChatRetrievalResult.IsElevated = (*source).IsElevated
		modelChatRetrievalResult.IsSelected = (*source).IsSelected
		modelChatRetrievalResult.SelectionReason = (*source).SelectionReason
		modelChatRetrievalResult.DocumentId = (*source).DocumentId
		modelChatRetrievalResult.DocumentName = (*source).DocumentName
		modelChatRetrievalResult.ChunkId = (*source).ChunkId
		modelChatRetrievalResult.ChunkNo = (*source).ChunkNo
		modelChatRetrievalResult.ParentBlockId = (*source).ParentBlockId
		modelChatRetrievalResult.ParentBlockNo = (*source).ParentBlockNo
		modelChatRetrievalResult.SectionPath = (*source).SectionPath
		modelChatRetrievalResult.ChunkTextPreview = (*source).ChunkTextPreview
		modelChatRetrievalResult.ChunkCharCount = (*source).ChunkCharCount
		pModelChatRetrievalResult = &modelChatRetrievalResult
	}
	return pModelChatRetrievalResult
}
func timeTimeToTimeTime(source time.Time) time.Time {
	return source
}
func FromConfirmStrategyReq(source *document.ConfirmStrategyReq) *vo1.DocumentStrategyConfirmCmd {
	var pVoDocumentStrategyConfirmCmd *vo1.DocumentStrategyConfirmCmd
	if source != nil {
		var voDocumentStrategyConfirmCmd vo1.DocumentStrategyConfirmCmd
		voDocumentStrategyConfirmCmd.DocumentId = (*source).DocumentId
		voDocumentStrategyConfirmCmd.BasePlanId = (*source).BasePlanId
		voDocumentStrategyConfirmCmd.OperatorId = (*source).OperatorId
		voDocumentStrategyConfirmCmd.AdjustNote = (*source).AdjustNote
		if (*source).ParentSteps != nil {
			voDocumentStrategyConfirmCmd.ParentSteps = make([]*vo1.DocumentStrategyStepItem, len((*source).ParentSteps))
			for i := 0; i < len((*source).ParentSteps); i++ {
				voDocumentStrategyConfirmCmd.ParentSteps[i] = pDocumentStrategyStepItemToPVoDocumentStrategyStepItem((*source).ParentSteps[i])
			}
		}
		if (*source).ChildSteps != nil {
			voDocumentStrategyConfirmCmd.ChildSteps = make([]*vo1.DocumentStrategyStepItem, len((*source).ChildSteps))
			for j := 0; j < len((*source).ChildSteps); j++ {
				voDocumentStrategyConfirmCmd.ChildSteps[j] = pDocumentStrategyStepItemToPVoDocumentStrategyStepItem((*source).ChildSteps[j])
			}
		}
		pVoDocumentStrategyConfirmCmd = &voDocumentStrategyConfirmCmd
	}
	return pVoDocumentStrategyConfirmCmd
}
func FromUploadDocumentReq(source *document.UploadDocumentReq) *entity1.Document {
	var pEntityDocument *entity1.Document
	if source != nil {
		var entityDocument entity1.Document
		entityDocument.DocumentName = (*source).DocumentName
		entityDocument.KnowledgeScopeCode = (*source).KnowledgeScopeCode
		entityDocument.KnowledgeScopeName = (*source).KnowledgeScopeName
		entityDocument.BusinessCategory = (*source).BusinessCategory
		entityDocument.DocumentTags = (*source).DocumentTags
		entityDocument.OperatorId = (*source).OperatorId
		pEntityDocument = &entityDocument
	}
	return pEntityDocument
}
func ToBuildIndexResp(source *vo1.DocumentIndexBuild) *document.BuildIndexResp {
	var pDocumentBuildIndexResp *document.BuildIndexResp
	if source != nil {
		var documentBuildIndexResp document.BuildIndexResp
		documentBuildIndexResp.TaskId = (*source).TaskId
		documentBuildIndexResp.DocumentId = (*source).DocumentId
		documentBuildIndexResp.TaskType = (*source).TaskType
		documentBuildIndexResp.TaskTypeName = (*source).TaskTypeName
		documentBuildIndexResp.TaskStatus = (*source).TaskStatus
		documentBuildIndexResp.TaskStatusName = (*source).TaskStatusName
		documentBuildIndexResp.IndexStatus = (*source).IndexStatus
		documentBuildIndexResp.IndexStatusName = (*source).IndexStatusName
		pDocumentBuildIndexResp = &documentBuildIndexResp
	}
	return pDocumentBuildIndexResp
}
func ToConfirmStrategyResp(source *entity1.DocumentStrategyPlan) *document.ConfirmStrategyResp {
	var pDocumentConfirmStrategyResp *document.ConfirmStrategyResp
	if source != nil {
		var documentConfirmStrategyResp document.ConfirmStrategyResp
		documentConfirmStrategyResp.ID = (*source).ID
		documentConfirmStrategyResp.DocumentId = (*source).DocumentId
		documentConfirmStrategyResp.PlanVersion = (*source).PlanVersion
		documentConfirmStrategyResp.Normalized = (*source).Normalized
		documentConfirmStrategyResp.ParentPipeline = pEntityDocumentStrategyPipelineToPDocumentDocumentStrategyPipeline((*source).ParentPipeline)
		documentConfirmStrategyResp.ChildPipeline = pEntityDocumentStrategyPipelineToPDocumentDocumentStrategyPipeline((*source).ChildPipeline)
		pDocumentConfirmStrategyResp = &documentConfirmStrategyResp
	}
	return pDocumentConfirmStrategyResp
}
func ToDocumentChunkItemList(source []*entity1.DocumentChunk) []*document.DocumentChunkItem {
	var pDocumentDocumentChunkItemList []*document.DocumentChunkItem
	if source != nil {
		pDocumentDocumentChunkItemList = make([]*document.DocumentChunkItem, len(source))
		for i := 0; i < len(source); i++ {
			pDocumentDocumentChunkItemList[i] = pEntityDocumentChunkToPDocumentDocumentChunkItem(source[i])
		}
	}
	return pDocumentDocumentChunkItemList
}
func ToDocumentChunkModel(source *entity1.DocumentChunk) *model.DocumentChunk {
	var pModelDocumentChunk *model.DocumentChunk
	if source != nil {
		var modelDocumentChunk model.DocumentChunk
		modelDocumentChunk.ID = (*source).ID
		modelDocumentChunk.DocumentId = (*source).DocumentId
		modelDocumentChunk.TaskId = (*source).TaskId
		modelDocumentChunk.PlanId = (*source).PlanId
		modelDocumentChunk.ParentBlockId = (*source).ParentBlockId
		modelDocumentChunk.ChunkNo = (*source).ChunkNo
		modelDocumentChunk.SourceType = (*source).SourceType
		modelDocumentChunk.SectionPath = (*source).SectionPath
		modelDocumentChunk.StructureNodeId = (*source).StructureNodeId
		modelDocumentChunk.StructureNodeType = (*source).StructureNodeType
		modelDocumentChunk.CanonicalPath = (*source).CanonicalPath
		modelDocumentChunk.ItemIndex = (*source).ItemIndex
		modelDocumentChunk.ChunkText = (*source).ChunkText
		modelDocumentChunk.CharCount = (*source).CharCount
		modelDocumentChunk.TokenCount = (*source).TokenCount
		modelDocumentChunk.VectorStatus = (*source).VectorStatus
		modelDocumentChunk.VectorStoreType = (*source).VectorStoreType
		modelDocumentChunk.VectorId = (*source).VectorId
		pModelDocumentChunk = &modelDocumentChunk
	}
	return pModelDocumentChunk
}
func ToDocumentChunkModelList(source []*entity1.DocumentChunk) []*model.DocumentChunk {
	var pModelDocumentChunkList []*model.DocumentChunk
	if source != nil {
		pModelDocumentChunkList = make([]*model.DocumentChunk, len(source))
		for i := 0; i < len(source); i++ {
			pModelDocumentChunkList[i] = ToDocumentChunkModel(source[i])
		}
	}
	return pModelDocumentChunkList
}
func ToDocumentListItem(source *entity1.Document) *document.DocumentListItem {
	var pDocumentDocumentListItem *document.DocumentListItem
	if source != nil {
		var documentDocumentListItem document.DocumentListItem
		documentDocumentListItem.ID = (*source).ID
		documentDocumentListItem.DocumentName = (*source).DocumentName
		documentDocumentListItem.OriginalFileName = (*source).OriginalFileName
		documentDocumentListItem.FileType = (*source).FileType
		documentDocumentListItem.FileTypeName = (*source).FileTypeName
		documentDocumentListItem.FileSize = (*source).FileSize
		documentDocumentListItem.CharCount = (*source).CharCount
		documentDocumentListItem.TokenCount = (*source).TokenCount
		documentDocumentListItem.ParseStatus = (*source).ParseStatus
		documentDocumentListItem.ParseStatusName = (*source).ParseStatusName
		documentDocumentListItem.StrategyStatus = (*source).StrategyStatus
		documentDocumentListItem.StrategyStatusName = (*source).StrategyStatusName
		documentDocumentListItem.IndexStatus = (*source).IndexStatus
		documentDocumentListItem.IndexStatusName = (*source).IndexStatusName
		if (*source).ParseErrorMsg != nil {
			documentDocumentListItem.ParseErrorMsg = *(*source).ParseErrorMsg
		}
		documentDocumentListItem.KnowledgeScopeCode = (*source).KnowledgeScopeCode
		documentDocumentListItem.KnowledgeScopeName = (*source).KnowledgeScopeName
		documentDocumentListItem.BusinessCategory = (*source).BusinessCategory
		documentDocumentListItem.DocumentTags = (*source).DocumentTags
		documentDocumentListItem.CurrentPlanId = (*source).CurrentPlanId
		documentDocumentListItem.LastIndexTaskId = (*source).LastIndexTaskId
		documentDocumentListItem.LatestTaskId = (*source).LatestTaskId
		documentDocumentListItem.LatestTaskType = (*source).LatestTaskType
		documentDocumentListItem.LatestTaskTypeName = (*source).LatestTaskTypeName
		documentDocumentListItem.LatestTaskStatus = (*source).LatestTaskStatus
		documentDocumentListItem.LatestTaskStatusName = (*source).LatestTaskStatusName
		documentDocumentListItem.CreateTime = TimeToString((*source).CreateTime)
		documentDocumentListItem.UpdateTime = TimeToString((*source).UpdateTime)
		pDocumentDocumentListItem = &documentDocumentListItem
	}
	return pDocumentDocumentListItem
}
func ToDocumentListItemList(source []*entity1.Document) []*document.DocumentListItem {
	var pDocumentDocumentListItemList []*document.DocumentListItem
	if source != nil {
		pDocumentDocumentListItemList = make([]*document.DocumentListItem, len(source))
		for i := 0; i < len(source); i++ {
			pDocumentDocumentListItemList[i] = ToDocumentListItem(source[i])
		}
	}
	return pDocumentDocumentListItemList
}
func ToDocumentModel(source *entity1.Document) *model.Document {
	var pModelDocument *model.Document
	if source != nil {
		var modelDocument model.Document
		modelDocument.ID = (*source).ID
		modelDocument.DocumentName = (*source).DocumentName
		modelDocument.OriginalFileName = (*source).OriginalFileName
		modelDocument.FileType = (*source).FileType
		modelDocument.MimeType = (*source).MimeType
		modelDocument.FileSize = (*source).FileSize
		modelDocument.StorageType = (*source).StorageType
		modelDocument.BucketName = (*source).BucketName
		modelDocument.ObjectName = (*source).ObjectName
		modelDocument.ObjectUrl = (*source).ObjectUrl
		modelDocument.ParseStatus = (*source).ParseStatus
		modelDocument.StrategyStatus = (*source).StrategyStatus
		modelDocument.IndexStatus = (*source).IndexStatus
		modelDocument.CharCount = (*source).CharCount
		modelDocument.TokenCount = (*source).TokenCount
		modelDocument.StructureLevel = (*source).StructureLevel
		modelDocument.ContentQualityLevel = (*source).ContentQualityLevel
		modelDocument.ParseTextPath = (*source).ParseTextPath
		modelDocument.ParseErrorMsg = (*source).ParseErrorMsg
		modelDocument.KnowledgeScopeCode = (*source).KnowledgeScopeCode
		modelDocument.KnowledgeScopeName = (*source).KnowledgeScopeName
		modelDocument.BusinessCategory = (*source).BusinessCategory
		modelDocument.DocumentTags = (*source).DocumentTags
		modelDocument.CurrentPlanId = (*source).CurrentPlanId
		modelDocument.LastParseTaskId = (*source).LastParseTaskId
		modelDocument.StructureNodeCount = (*source).StructureNodeCount
		modelDocument.LastIndexTaskId = (*source).LastIndexTaskId
		pModelDocument = &modelDocument
	}
	return pModelDocument
}
func ToDocumentParentBlockModel(source *entity1.DocumentParentBlock) *model.DocumentParentBlock {
	var pModelDocumentParentBlock *model.DocumentParentBlock
	if source != nil {
		var modelDocumentParentBlock model.DocumentParentBlock
		modelDocumentParentBlock.ID = (*source).ID
		modelDocumentParentBlock.DocumentId = (*source).DocumentId
		modelDocumentParentBlock.TaskId = (*source).TaskId
		modelDocumentParentBlock.PlanId = (*source).PlanId
		modelDocumentParentBlock.ParentNo = (*source).ParentNo
		modelDocumentParentBlock.SourceType = (*source).SourceType
		modelDocumentParentBlock.SectionPath = (*source).SectionPath
		modelDocumentParentBlock.StructureNodeId = (*source).StructureNodeId
		modelDocumentParentBlock.StructureNodeType = (*source).StructureNodeType
		modelDocumentParentBlock.CanonicalPath = (*source).CanonicalPath
		modelDocumentParentBlock.ItemIndex = (*source).ItemIndex
		modelDocumentParentBlock.ParentText = (*source).ParentText
		modelDocumentParentBlock.CharCount = (*source).CharCount
		modelDocumentParentBlock.TokenCount = (*source).TokenCount
		modelDocumentParentBlock.ChildCount = (*source).ChildCount
		modelDocumentParentBlock.StartChunkNo = (*source).StartChunkNo
		modelDocumentParentBlock.EndChunkNo = (*source).EndChunkNo
		pModelDocumentParentBlock = &modelDocumentParentBlock
	}
	return pModelDocumentParentBlock
}
func ToDocumentParentBlockModelList(source []*entity1.DocumentParentBlock) []*model.DocumentParentBlock {
	var pModelDocumentParentBlockList []*model.DocumentParentBlock
	if source != nil {
		pModelDocumentParentBlockList = make([]*model.DocumentParentBlock, len(source))
		for i := 0; i < len(source); i++ {
			pModelDocumentParentBlockList[i] = ToDocumentParentBlockModel(source[i])
		}
	}
	return pModelDocumentParentBlockList
}
func ToDocumentProfileModel(source *entity1.DocumentProfile) *model.DocumentProfile {
	var pModelDocumentProfile *model.DocumentProfile
	if source != nil {
		var modelDocumentProfile model.DocumentProfile
		modelDocumentProfile.ID = (*source).ID
		modelDocumentProfile.DocumentId = (*source).DocumentId
		modelDocumentProfile.ProfileVersion = (*source).ProfileVersion
		modelDocumentProfile.DocumentSummary = (*source).DocumentSummary
		modelDocumentProfile.DocumentType = (*source).DocumentType
		modelDocumentProfile.CoreTopics = (*source).CoreTopics
		modelDocumentProfile.ExampleQuestions = (*source).ExampleQuestions
		modelDocumentProfile.GraphFriendly = (*source).GraphFriendly
		modelDocumentProfile.SupportsGraphOutline = (*source).SupportsGraphOutline
		modelDocumentProfile.SupportsItemLookup = (*source).SupportsItemLookup
		modelDocumentProfile.SupportsGraphAssist = (*source).SupportsGraphAssist
		modelDocumentProfile.ProfileSource = (*source).ProfileSource
		modelDocumentProfile.ProfileStatus = (*source).ProfileStatus
		modelDocumentProfile.ErrorMsg = (*source).ErrorMsg
		pModelDocumentProfile = &modelDocumentProfile
	}
	return pModelDocumentProfile
}
func ToDocumentProfileResp(source *entity1.DocumentProfile) *document.DocumentProfileResp {
	var pDocumentDocumentProfileResp *document.DocumentProfileResp
	if source != nil {
		var documentDocumentProfileResp document.DocumentProfileResp
		documentDocumentProfileResp.DocumentId = (*source).DocumentId
		documentDocumentProfileResp.DocumentSummary = (*source).DocumentSummary
		documentDocumentProfileResp.DocumentType = (*source).DocumentType
		documentDocumentProfileResp.CoreTopics = (*source).CoreTopics
		documentDocumentProfileResp.ExampleQuestions = (*source).ExampleQuestions
		documentDocumentProfileResp.GraphFriendly = (*source).GraphFriendly
		documentDocumentProfileResp.SupportsGraphOutline = (*source).SupportsGraphOutline
		documentDocumentProfileResp.SupportsItemLookup = (*source).SupportsItemLookup
		documentDocumentProfileResp.SupportsGraphAssist = (*source).SupportsGraphAssist
		documentDocumentProfileResp.ProfileSource = (*source).ProfileSource
		documentDocumentProfileResp.ProfileStatus = (*source).ProfileStatus
		if (*source).ErrorMsg != nil {
			documentDocumentProfileResp.ErrorMsg = *(*source).ErrorMsg
		}
		pDocumentDocumentProfileResp = &documentDocumentProfileResp
	}
	return pDocumentDocumentProfileResp
}
func ToDocumentProfileRespList(source []*entity1.DocumentProfile) []*document.DocumentProfileResp {
	var pDocumentDocumentProfileRespList []*document.DocumentProfileResp
	if source != nil {
		pDocumentDocumentProfileRespList = make([]*document.DocumentProfileResp, len(source))
		for i := 0; i < len(source); i++ {
			pDocumentDocumentProfileRespList[i] = ToDocumentProfileResp(source[i])
		}
	}
	return pDocumentDocumentProfileRespList
}
func ToDocumentStrategyPlan(source *entity1.DocumentStrategyPlan) *document.DocumentStrategyPlan {
	var pDocumentDocumentStrategyPlan *document.DocumentStrategyPlan
	if source != nil {
		var documentDocumentStrategyPlan document.DocumentStrategyPlan
		documentDocumentStrategyPlan.ID = (*source).ID
		documentDocumentStrategyPlan.PlanVersion = (*source).PlanVersion
		documentDocumentStrategyPlan.PlanSource = (*source).PlanSource
		documentDocumentStrategyPlan.PlanSourceName = (*source).PlanSourceName
		documentDocumentStrategyPlan.PlanStatus = (*source).PlanStatus
		documentDocumentStrategyPlan.PlanStatusName = (*source).PlanStatusName
		documentDocumentStrategyPlan.StrategySnapshot = (*source).StrategySnapshot
		documentDocumentStrategyPlan.RecommendReason = (*source).RecommendReason
		documentDocumentStrategyPlan.ParentPipeline = pEntityDocumentStrategyPipelineToPDocumentDocumentStrategyPipeline((*source).ParentPipeline)
		documentDocumentStrategyPlan.ChildPipeline = pEntityDocumentStrategyPipelineToPDocumentDocumentStrategyPipeline((*source).ChildPipeline)
		pDocumentDocumentStrategyPlan = &documentDocumentStrategyPlan
	}
	return pDocumentDocumentStrategyPlan
}
func ToDocumentStrategyPlanModel(source *entity1.DocumentStrategyPlan) *model.DocumentStrategyPlan {
	var pModelDocumentStrategyPlan *model.DocumentStrategyPlan
	if source != nil {
		var modelDocumentStrategyPlan model.DocumentStrategyPlan
		modelDocumentStrategyPlan.ID = (*source).ID
		modelDocumentStrategyPlan.DocumentId = (*source).DocumentId
		modelDocumentStrategyPlan.PlanVersion = (*source).PlanVersion
		modelDocumentStrategyPlan.PlanSource = (*source).PlanSource
		modelDocumentStrategyPlan.PlanStatus = (*source).PlanStatus
		modelDocumentStrategyPlan.StrategyCount = (*source).StrategyCount
		modelDocumentStrategyPlan.StrategySnapshot = (*source).StrategySnapshot
		modelDocumentStrategyPlan.RecommendReason = (*source).RecommendReason
		modelDocumentStrategyPlan.AdjustNote = (*source).AdjustNote
		modelDocumentStrategyPlan.ConfirmUserId = (*source).ConfirmUserId
		modelDocumentStrategyPlan.ConfirmTime = (*source).ConfirmTime
		pModelDocumentStrategyPlan = &modelDocumentStrategyPlan
	}
	return pModelDocumentStrategyPlan
}
func ToDocumentStrategyStepModel(source *entity1.DocumentStrategyStep) *model.DocumentStrategyStep {
	var pModelDocumentStrategyStep *model.DocumentStrategyStep
	if source != nil {
		var modelDocumentStrategyStep model.DocumentStrategyStep
		modelDocumentStrategyStep.ID = (*source).ID
		modelDocumentStrategyStep.DocumentId = (*source).DocumentId
		modelDocumentStrategyStep.PlanId = (*source).PlanId
		modelDocumentStrategyStep.StepNo = (*source).StepNo
		modelDocumentStrategyStep.PipelineType = (*source).PipelineType
		modelDocumentStrategyStep.StrategyType = (*source).StrategyType
		modelDocumentStrategyStep.StrategyRole = (*source).StrategyRole
		modelDocumentStrategyStep.SourceType = (*source).SourceType
		modelDocumentStrategyStep.ExecuteStatus = (*source).ExecuteStatus
		modelDocumentStrategyStep.RecommendReason = (*source).RecommendReason
		pModelDocumentStrategyStep = &modelDocumentStrategyStep
	}
	return pModelDocumentStrategyStep
}
func ToDocumentStrategyStepModelList(source []*entity1.DocumentStrategyStep) []*model.DocumentStrategyStep {
	var pModelDocumentStrategyStepList []*model.DocumentStrategyStep
	if source != nil {
		pModelDocumentStrategyStepList = make([]*model.DocumentStrategyStep, len(source))
		for i := 0; i < len(source); i++ {
			pModelDocumentStrategyStepList[i] = ToDocumentStrategyStepModel(source[i])
		}
	}
	return pModelDocumentStrategyStepList
}
func ToDocumentStructureNodeModelList(source []*entity1.DocumentStructureNode) []*model.DocumentStructureNode {
	var pModelDocumentStructureNodeList []*model.DocumentStructureNode
	if source != nil {
		pModelDocumentStructureNodeList = make([]*model.DocumentStructureNode, len(source))
		for i := 0; i < len(source); i++ {
			pModelDocumentStructureNodeList[i] = pEntityDocumentStructureNodeToPModelDocumentStructureNode(source[i])
		}
	}
	return pModelDocumentStructureNodeList
}
func ToDocumentTaskLogModel(source *entity1.DocumentTaskLog) *model.DocumentTaskLog {
	var pModelDocumentTaskLog *model.DocumentTaskLog
	if source != nil {
		var modelDocumentTaskLog model.DocumentTaskLog
		modelDocumentTaskLog.ID = (*source).ID
		modelDocumentTaskLog.TaskId = (*source).TaskId
		modelDocumentTaskLog.DocumentId = (*source).DocumentId
		modelDocumentTaskLog.StageType = (*source).StageType
		modelDocumentTaskLog.EventType = (*source).EventType
		modelDocumentTaskLog.LogLevel = (*source).LogLevel
		modelDocumentTaskLog.OperatorType = (*source).OperatorType
		modelDocumentTaskLog.OperatorId = (*source).OperatorId
		modelDocumentTaskLog.Content = (*source).Content
		modelDocumentTaskLog.DetailJson = (*source).DetailJson
		pModelDocumentTaskLog = &modelDocumentTaskLog
	}
	return pModelDocumentTaskLog
}
func ToDocumentTaskModel(source *entity1.DocumentTask) *model.DocumentTask {
	var pModelDocumentTask *model.DocumentTask
	if source != nil {
		var modelDocumentTask model.DocumentTask
		modelDocumentTask.ID = (*source).ID
		modelDocumentTask.DocumentId = (*source).DocumentId
		modelDocumentTask.PlanId = (*source).PlanId
		modelDocumentTask.TaskType = (*source).TaskType
		modelDocumentTask.TaskStatus = (*source).TaskStatus
		modelDocumentTask.CurrentStage = (*source).CurrentStage
		modelDocumentTask.TriggerSource = (*source).TriggerSource
		modelDocumentTask.StrategySnapshot = (*source).StrategySnapshot
		modelDocumentTask.RetryCount = (*source).RetryCount
		modelDocumentTask.StartTime = timeTimeToTimeTime2((*source).StartTime)
		modelDocumentTask.FinishTime = timeTimeToTimeTime2((*source).FinishTime)
		modelDocumentTask.CostMillis = (*source).CostMillis
		modelDocumentTask.ErrorCode = (*source).ErrorCode
		modelDocumentTask.ErrorMsg = (*source).ErrorMsg
		modelDocumentTask.ExtJson = (*source).ExtJson
		pModelDocumentTask = &modelDocumentTask
	}
	return pModelDocumentTask
}
func ToKnowledgeDocumentOptionRespList(source []*vo1.KnowledgeDocument) []*document.KnowledgeDocumentOptionResp {
	var pDocumentKnowledgeDocumentOptionRespList []*document.KnowledgeDocumentOptionResp
	if source != nil {
		pDocumentKnowledgeDocumentOptionRespList = make([]*document.KnowledgeDocumentOptionResp, len(source))
		for i := 0; i < len(source); i++ {
			pDocumentKnowledgeDocumentOptionRespList[i] = pEntityDocumentToPDocumentKnowledgeDocumentOptionResp(source[i])
		}
	}
	return pDocumentKnowledgeDocumentOptionRespList
}
func ToQueryDocumentChunkDetailResp(source *aggregate.DocumentChunkDetail) *document.QueryDocumentChunkDetailResp {
	var pDocumentQueryDocumentChunkDetailResp *document.QueryDocumentChunkDetailResp
	if source != nil {
		var documentQueryDocumentChunkDetailResp document.QueryDocumentChunkDetailResp
		documentQueryDocumentChunkDetailResp.DocumentId = (*source).DocumentId
		documentQueryDocumentChunkDetailResp.TaskId = (*source).TaskId
		documentQueryDocumentChunkDetailResp.PlanId = (*source).PlanId
		documentQueryDocumentChunkDetailResp.Chunk = pEntityDocumentChunkToPDocumentDocumentChunkItem((*source).Chunk)
		documentQueryDocumentChunkDetailResp.ParentBlock = pEntityDocumentParentBlockToPDocumentDocumentParentBlockItem((*source).ParentBlock)
		documentQueryDocumentChunkDetailResp.SiblingChunks = ToDocumentChunkItemList((*source).SiblingChunks)
		pDocumentQueryDocumentChunkDetailResp = &documentQueryDocumentChunkDetailResp
	}
	return pDocumentQueryDocumentChunkDetailResp
}
func ToQueryStrategyPlanResp(source *entity1.Document) *document.QueryStrategyPlanResp {
	var pDocumentQueryStrategyPlanResp *document.QueryStrategyPlanResp
	if source != nil {
		var documentQueryStrategyPlanResp document.QueryStrategyPlanResp
		documentQueryStrategyPlanResp.ID = (*source).ID
		documentQueryStrategyPlanResp.DocumentName = (*source).DocumentName
		documentQueryStrategyPlanResp.ParseStatus = (*source).ParseStatus
		documentQueryStrategyPlanResp.ParseStatusName = (*source).ParseStatusName
		documentQueryStrategyPlanResp.StrategyStatus = (*source).StrategyStatus
		documentQueryStrategyPlanResp.StrategyStatusName = (*source).StrategyStatusName
		documentQueryStrategyPlanResp.IndexStatus = (*source).IndexStatus
		documentQueryStrategyPlanResp.IndexStatusName = (*source).IndexStatusName
		if (*source).ParseErrorMsg != nil {
			documentQueryStrategyPlanResp.ParseErrorMsg = *(*source).ParseErrorMsg
		}
		documentQueryStrategyPlanResp.PlanReady = (*source).PlanReady
		pDocumentQueryStrategyPlanResp = &documentQueryStrategyPlanResp
	}
	return pDocumentQueryStrategyPlanResp
}
func ToQueryTaskLogsResp(source *entity1.DocumentTask) *document.QueryTaskLogsResp {
	var pDocumentQueryTaskLogsResp *document.QueryTaskLogsResp
	if source != nil {
		var documentQueryTaskLogsResp document.QueryTaskLogsResp
		documentQueryTaskLogsResp.ID = (*source).ID
		documentQueryTaskLogsResp.DocumentId = (*source).DocumentId
		documentQueryTaskLogsResp.TaskType = (*source).TaskType
		documentQueryTaskLogsResp.TaskTypeName = (*source).TaskTypeName
		documentQueryTaskLogsResp.TaskStatus = (*source).TaskStatus
		documentQueryTaskLogsResp.TaskStatusName = (*source).TaskStatusName
		documentQueryTaskLogsResp.CurrentStage = (*source).CurrentStage
		documentQueryTaskLogsResp.CurrentStageName = (*source).CurrentStageName
		documentQueryTaskLogsResp.StartTime = TimeToString((*source).StartTime)
		documentQueryTaskLogsResp.FinishTime = TimeToString((*source).FinishTime)
		documentQueryTaskLogsResp.CostMillis = (*source).CostMillis
		if (*source).ErrorCode != nil {
			documentQueryTaskLogsResp.ErrorCode = *(*source).ErrorCode
		}
		if (*source).ErrorMsg != nil {
			documentQueryTaskLogsResp.ErrorMsg = *(*source).ErrorMsg
		}
		if (*source).Logs != nil {
			documentQueryTaskLogsResp.Logs = make([]*document.TaskLog, len((*source).Logs))
			for i := 0; i < len((*source).Logs); i++ {
				documentQueryTaskLogsResp.Logs[i] = pEntityDocumentTaskLogToPDocumentTaskLog((*source).Logs[i])
			}
		}
		pDocumentQueryTaskLogsResp = &documentQueryTaskLogsResp
	}
	return pDocumentQueryTaskLogsResp
}
func ToUploadDocumentResp(source *vo1.DocumentUpload) *document.UploadDocumentResp {
	var pDocumentUploadDocumentResp *document.UploadDocumentResp
	if source != nil {
		var documentUploadDocumentResp document.UploadDocumentResp
		documentUploadDocumentResp.DocumentId = (*source).DocumentId
		documentUploadDocumentResp.TaskId = (*source).TaskId
		documentUploadDocumentResp.DocumentName = (*source).DocumentName
		documentUploadDocumentResp.ParseStatus = (*source).ParseStatus
		documentUploadDocumentResp.StrategyStatus = (*source).StrategyStatus
		documentUploadDocumentResp.IndexStatus = (*source).IndexStatus
		pDocumentUploadDocumentResp = &documentUploadDocumentResp
	}
	return pDocumentUploadDocumentResp
}
func pDocumentStrategyStepItemToPVoDocumentStrategyStepItem(source *document.StrategyStepItem) *vo1.DocumentStrategyStepItem {
	var pVoDocumentStrategyStepItem *vo1.DocumentStrategyStepItem
	if source != nil {
		var voDocumentStrategyStepItem vo1.DocumentStrategyStepItem
		voDocumentStrategyStepItem.StepNo = (*source).StepNo
		voDocumentStrategyStepItem.StrategyType = (*source).StrategyType
		pVoDocumentStrategyStepItem = &voDocumentStrategyStepItem
	}
	return pVoDocumentStrategyStepItem
}
func pEntityDocumentChunkToPDocumentDocumentChunkItem(source *entity1.DocumentChunk) *document.DocumentChunkItem {
	var pDocumentDocumentChunkItem *document.DocumentChunkItem
	if source != nil {
		var documentDocumentChunkItem document.DocumentChunkItem
		documentDocumentChunkItem.ParentBlockId = (*source).ParentBlockId
		documentDocumentChunkItem.ParentBlockNo = (*source).ParentBlockNo
		documentDocumentChunkItem.ParentChildCount = (*source).ParentChildCount
		documentDocumentChunkItem.ParentStartChunkNo = (*source).ParentStartChunkNo
		documentDocumentChunkItem.ParentEndChunkNo = (*source).ParentEndChunkNo
		documentDocumentChunkItem.ChunkNo = (*source).ChunkNo
		documentDocumentChunkItem.SectionPath = (*source).SectionPath
		documentDocumentChunkItem.SourceType = (*source).SourceType
		documentDocumentChunkItem.SourceTypeName = (*source).SourceTypeName
		documentDocumentChunkItem.CharCount = (*source).CharCount
		documentDocumentChunkItem.TokenCount = (*source).TokenCount
		documentDocumentChunkItem.VectorStatus = (*source).VectorStatus
		documentDocumentChunkItem.VectorStatusName = (*source).VectorStatusName
		documentDocumentChunkItem.ChunkText = (*source).ChunkText
		pDocumentDocumentChunkItem = &documentDocumentChunkItem
	}
	return pDocumentDocumentChunkItem
}
func pEntityDocumentParentBlockToPDocumentDocumentParentBlockItem(source *entity1.DocumentParentBlock) *document.DocumentParentBlockItem {
	var pDocumentDocumentParentBlockItem *document.DocumentParentBlockItem
	if source != nil {
		var documentDocumentParentBlockItem document.DocumentParentBlockItem
		documentDocumentParentBlockItem.SectionPath = (*source).SectionPath
		documentDocumentParentBlockItem.SourceType = (*source).SourceType
		documentDocumentParentBlockItem.SourceTypeName = (*source).SourceTypeName
		documentDocumentParentBlockItem.CharCount = (*source).CharCount
		documentDocumentParentBlockItem.TokenCount = (*source).TokenCount
		documentDocumentParentBlockItem.ChildCount = (*source).ChildCount
		documentDocumentParentBlockItem.StartChunkNo = (*source).StartChunkNo
		documentDocumentParentBlockItem.EndChunkNo = (*source).EndChunkNo
		documentDocumentParentBlockItem.ParentText = (*source).ParentText
		pDocumentDocumentParentBlockItem = &documentDocumentParentBlockItem
	}
	return pDocumentDocumentParentBlockItem
}
func pEntityDocumentStrategyPipelineToPDocumentDocumentStrategyPipeline(source *entity1.DocumentStrategyPipeline) *document.DocumentStrategyPipeline {
	var pDocumentDocumentStrategyPipeline *document.DocumentStrategyPipeline
	if source != nil {
		var documentDocumentStrategyPipeline document.DocumentStrategyPipeline
		documentDocumentStrategyPipeline.PipelineType = (*source).PipelineType
		documentDocumentStrategyPipeline.PipelineTypeName = (*source).PipelineTypeName
		documentDocumentStrategyPipeline.StrategySnapshot = (*source).StrategySnapshot
		if (*source).Steps != nil {
			documentDocumentStrategyPipeline.Steps = make([]*document.DocumentStrategyStep, len((*source).Steps))
			for i := 0; i < len((*source).Steps); i++ {
				documentDocumentStrategyPipeline.Steps[i] = pEntityDocumentStrategyStepToPDocumentDocumentStrategyStep((*source).Steps[i])
			}
		}
		pDocumentDocumentStrategyPipeline = &documentDocumentStrategyPipeline
	}
	return pDocumentDocumentStrategyPipeline
}
func pEntityDocumentStrategyStepToPDocumentDocumentStrategyStep(source *entity1.DocumentStrategyStep) *document.DocumentStrategyStep {
	var pDocumentDocumentStrategyStep *document.DocumentStrategyStep
	if source != nil {
		var documentDocumentStrategyStep document.DocumentStrategyStep
		documentDocumentStrategyStep.StepNo = (*source).StepNo
		documentDocumentStrategyStep.PipelineType = (*source).PipelineType
		documentDocumentStrategyStep.PipelineTypeName = (*source).PipelineTypeName
		documentDocumentStrategyStep.StrategyType = (*source).StrategyType
		documentDocumentStrategyStep.StrategyTypeName = (*source).StrategyTypeName
		documentDocumentStrategyStep.StrategyRole = (*source).StrategyRole
		documentDocumentStrategyStep.StrategyRoleName = (*source).StrategyRoleName
		documentDocumentStrategyStep.SourceType = (*source).SourceType
		documentDocumentStrategyStep.SourceTypeName = (*source).SourceTypeName
		documentDocumentStrategyStep.ExecuteStatus = (*source).ExecuteStatus
		documentDocumentStrategyStep.ExecuteStatusName = (*source).ExecuteStatusName
		documentDocumentStrategyStep.RecommendReason = (*source).RecommendReason
		pDocumentDocumentStrategyStep = &documentDocumentStrategyStep
	}
	return pDocumentDocumentStrategyStep
}
func pEntityDocumentStructureNodeToPModelDocumentStructureNode(source *entity1.DocumentStructureNode) *model.DocumentStructureNode {
	var pModelDocumentStructureNode *model.DocumentStructureNode
	if source != nil {
		var modelDocumentStructureNode model.DocumentStructureNode
		modelDocumentStructureNode.DocumentId = (*source).DocumentId
		modelDocumentStructureNode.ParseTaskId = (*source).ParseTaskId
		modelDocumentStructureNode.NodeNo = (*source).NodeNo
		modelDocumentStructureNode.NodeType = (*source).NodeType
		modelDocumentStructureNode.ParentNodeId = (*source).ParentNodeId
		modelDocumentStructureNode.PrevSiblingNodeId = (*source).PrevSiblingNodeId
		modelDocumentStructureNode.NextSiblingNodeId = (*source).NextSiblingNodeId
		modelDocumentStructureNode.Depth = (*source).Depth
		modelDocumentStructureNode.NodeCode = (*source).NodeCode
		modelDocumentStructureNode.Title = (*source).Title
		modelDocumentStructureNode.AnchorText = (*source).AnchorText
		modelDocumentStructureNode.CanonicalPath = (*source).CanonicalPath
		modelDocumentStructureNode.SectionPath = (*source).SectionPath
		modelDocumentStructureNode.ContentText = (*source).ContentText
		modelDocumentStructureNode.ItemIndex = (*source).ItemIndex
		pModelDocumentStructureNode = &modelDocumentStructureNode
	}
	return pModelDocumentStructureNode
}
func pEntityDocumentTaskLogToPDocumentTaskLog(source *entity1.DocumentTaskLog) *document.TaskLog {
	var pDocumentTaskLog *document.TaskLog
	if source != nil {
		var documentTaskLog document.TaskLog
		documentTaskLog.ID = (*source).ID
		documentTaskLog.StageType = (*source).StageType
		documentTaskLog.StageTypeName = (*source).StageTypeName
		documentTaskLog.EventType = (*source).EventType
		documentTaskLog.EventTypeName = (*source).EventTypeName
		documentTaskLog.LogLevel = (*source).LogLevel
		documentTaskLog.LogLevelName = (*source).LogLevelName
		documentTaskLog.Content = (*source).Content
		documentTaskLog.DetailJson = (*source).DetailJson
		documentTaskLog.CreateTime = TimeToString((*source).CreateTime)
		pDocumentTaskLog = &documentTaskLog
	}
	return pDocumentTaskLog
}
func pEntityDocumentToPDocumentKnowledgeDocumentOptionResp(source *vo1.KnowledgeDocument) *document.KnowledgeDocumentOptionResp {
	var pDocumentKnowledgeDocumentOptionResp *document.KnowledgeDocumentOptionResp
	if source != nil {
		var documentKnowledgeDocumentOptionResp document.KnowledgeDocumentOptionResp
		documentKnowledgeDocumentOptionResp.DocumentName = (*source).DocumentName
		documentKnowledgeDocumentOptionResp.KnowledgeScopeName = (*source).KnowledgeScopeName
		documentKnowledgeDocumentOptionResp.BusinessCategory = (*source).BusinessCategory
		documentKnowledgeDocumentOptionResp.DocumentTags = StringToStringSlice((*source).DocumentTags)
		pDocumentKnowledgeDocumentOptionResp = &documentKnowledgeDocumentOptionResp
	}
	return pDocumentKnowledgeDocumentOptionResp
}
func timeTimeToTimeTime2(source time.Time) time.Time {
	return source
}
func FromKnowledgeScopeSaveReq(source *knowledge.KnowledgeScopeSaveReq) *entity2.KnowledgeScopeNode {
	var pEntityKnowledgeScopeNode *entity2.KnowledgeScopeNode
	if source != nil {
		var entityKnowledgeScopeNode entity2.KnowledgeScopeNode
		entityKnowledgeScopeNode.ID = (*source).ID
		entityKnowledgeScopeNode.ScopeCode = NormalizeString((*source).ScopeCode)
		entityKnowledgeScopeNode.ScopeName = NormalizeString((*source).ScopeName)
		entityKnowledgeScopeNode.ParentScopeCode = NormalizeString((*source).ParentScopeCode)
		entityKnowledgeScopeNode.Description = NormalizeString((*source).Description)
		entityKnowledgeScopeNode.Aliases = NormalizeString((*source).Aliases)
		entityKnowledgeScopeNode.Examples = NormalizeString((*source).Examples)
		entityKnowledgeScopeNode.SortOrder = (*source).SortOrder
		entityKnowledgeScopeNode.OperatorId = NormalizeString((*source).OperatorId)
		pEntityKnowledgeScopeNode = &entityKnowledgeScopeNode
	}
	return pEntityKnowledgeScopeNode
}
func FromKnowledgeTopicDocumentRelationSaveReq(source *knowledge.TopicDocumentRelationSaveReq) *entity2.KnowledgeTopicDocumentRelation {
	var pEntityKnowledgeTopicDocumentRelation *entity2.KnowledgeTopicDocumentRelation
	if source != nil {
		var entityKnowledgeTopicDocumentRelation entity2.KnowledgeTopicDocumentRelation
		entityKnowledgeTopicDocumentRelation.TopicCode = NormalizeString((*source).TopicCode)
		entityKnowledgeTopicDocumentRelation.DocumentId = (*source).DocumentId
		entityKnowledgeTopicDocumentRelation.RelationScore = (*source).RelationScore
		entityKnowledgeTopicDocumentRelation.RelationSource = NormalizeString((*source).RelationSource)
		entityKnowledgeTopicDocumentRelation.Reason = NormalizeString((*source).Reason)
		pEntityKnowledgeTopicDocumentRelation = &entityKnowledgeTopicDocumentRelation
	}
	return pEntityKnowledgeTopicDocumentRelation
}
func FromKnowledgeTopicSaveReq(source *knowledge.KnowledgeTopicSaveReq) *entity2.KnowledgeTopicNode {
	var pEntityKnowledgeTopicNode *entity2.KnowledgeTopicNode
	if source != nil {
		var entityKnowledgeTopicNode entity2.KnowledgeTopicNode
		entityKnowledgeTopicNode.ID = (*source).ID
		entityKnowledgeTopicNode.TopicCode = NormalizeString((*source).TopicCode)
		entityKnowledgeTopicNode.TopicName = NormalizeString((*source).TopicName)
		entityKnowledgeTopicNode.ScopeCode = NormalizeString((*source).ScopeCode)
		entityKnowledgeTopicNode.Description = NormalizeString((*source).Description)
		entityKnowledgeTopicNode.Aliases = NormalizeString((*source).Aliases)
		entityKnowledgeTopicNode.Examples = NormalizeString((*source).Examples)
		entityKnowledgeTopicNode.AnswerShape = NormalizeString((*source).AnswerShape)
		entityKnowledgeTopicNode.ExecutionPreference = NormalizeString((*source).ExecutionPreference)
		entityKnowledgeTopicNode.SortOrder = (*source).SortOrder
		entityKnowledgeTopicNode.OperatorId = NormalizeString((*source).OperatorId)
		pEntityKnowledgeTopicNode = &entityKnowledgeTopicNode
	}
	return pEntityKnowledgeTopicNode
}
func ToKnowledgeRouteTraceItem(source *entity2.KnowledgeRouteTrace) *knowledge.KnowledgeRouteTraceItem {
	var pKnowledgeKnowledgeRouteTraceItem *knowledge.KnowledgeRouteTraceItem
	if source != nil {
		var knowledgeKnowledgeRouteTraceItem knowledge.KnowledgeRouteTraceItem
		knowledgeKnowledgeRouteTraceItem.ID = (*source).ID
		knowledgeKnowledgeRouteTraceItem.ConversationId = NormalizeString((*source).ConversationId)
		knowledgeKnowledgeRouteTraceItem.ExchangeId = (*source).ExchangeId
		knowledgeKnowledgeRouteTraceItem.Question = NormalizeString((*source).Question)
		knowledgeKnowledgeRouteTraceItem.RewriteQuestion = NormalizeString((*source).RewriteQuestion)
		knowledgeKnowledgeRouteTraceItem.Mode = NormalizeString((*source).Mode)
		knowledgeKnowledgeRouteTraceItem.TopScopesJson = NormalizeString((*source).TopScopesJson)
		knowledgeKnowledgeRouteTraceItem.TopTopicsJson = NormalizeString((*source).TopTopicsJson)
		knowledgeKnowledgeRouteTraceItem.TopDocumentsJson = NormalizeString((*source).TopDocumentsJson)
		knowledgeKnowledgeRouteTraceItem.SelectedDocumentId = (*source).SelectedDocumentId
		knowledgeKnowledgeRouteTraceItem.HitSelectedDocument = (*source).HitSelectedDocument
		knowledgeKnowledgeRouteTraceItem.Confidence = (*source).Confidence
		knowledgeKnowledgeRouteTraceItem.RouteStatus = ToRouteStatus((*source).RouteStatus)
		knowledgeKnowledgeRouteTraceItem.ErrorMsg = NormalizeString((*source).ErrorMsg)
		pKnowledgeKnowledgeRouteTraceItem = &knowledgeKnowledgeRouteTraceItem
	}
	return pKnowledgeKnowledgeRouteTraceItem
}
func ToKnowledgeRouteTraceItemList(source []*entity2.KnowledgeRouteTrace) []*knowledge.KnowledgeRouteTraceItem {
	var pKnowledgeKnowledgeRouteTraceItemList []*knowledge.KnowledgeRouteTraceItem
	if source != nil {
		pKnowledgeKnowledgeRouteTraceItemList = make([]*knowledge.KnowledgeRouteTraceItem, len(source))
		for i := 0; i < len(source); i++ {
			pKnowledgeKnowledgeRouteTraceItemList[i] = ToKnowledgeRouteTraceItem(source[i])
		}
	}
	return pKnowledgeKnowledgeRouteTraceItemList
}
func ToKnowledgeRouteTraceModel(source *entity2.KnowledgeRouteTrace) *model.KnowledgeRouteTrace {
	var pModelKnowledgeRouteTrace *model.KnowledgeRouteTrace
	if source != nil {
		var modelKnowledgeRouteTrace model.KnowledgeRouteTrace
		modelKnowledgeRouteTrace.ID = (*source).ID
		modelKnowledgeRouteTrace.ConversationId = NormalizeString((*source).ConversationId)
		modelKnowledgeRouteTrace.ExchangeId = (*source).ExchangeId
		modelKnowledgeRouteTrace.Question = NormalizeString((*source).Question)
		modelKnowledgeRouteTrace.RewriteQuestion = NormalizeString((*source).RewriteQuestion)
		modelKnowledgeRouteTrace.Mode = NormalizeString((*source).Mode)
		modelKnowledgeRouteTrace.TopScopesJson = NormalizeString((*source).TopScopesJson)
		modelKnowledgeRouteTrace.TopTopicsJson = NormalizeString((*source).TopTopicsJson)
		modelKnowledgeRouteTrace.TopDocumentsJson = NormalizeString((*source).TopDocumentsJson)
		modelKnowledgeRouteTrace.SelectedDocumentId = (*source).SelectedDocumentId
		modelKnowledgeRouteTrace.HitSelectedDocument = (*source).HitSelectedDocument
		modelKnowledgeRouteTrace.Confidence = (*source).Confidence
		modelKnowledgeRouteTrace.RouteStatus = (*source).RouteStatus
		modelKnowledgeRouteTrace.ErrorMsg = NormalizeString((*source).ErrorMsg)
		pModelKnowledgeRouteTrace = &modelKnowledgeRouteTrace
	}
	return pModelKnowledgeRouteTrace
}
func ToKnowledgeScopeItem(source *entity2.KnowledgeScopeNode) *knowledge.KnowledgeScopeItem {
	var pKnowledgeKnowledgeScopeItem *knowledge.KnowledgeScopeItem
	if source != nil {
		var knowledgeKnowledgeScopeItem knowledge.KnowledgeScopeItem
		knowledgeKnowledgeScopeItem.ID = (*source).ID
		knowledgeKnowledgeScopeItem.ScopeCode = NormalizeString((*source).ScopeCode)
		knowledgeKnowledgeScopeItem.ScopeName = NormalizeString((*source).ScopeName)
		knowledgeKnowledgeScopeItem.ParentScopeCode = NormalizeString((*source).ParentScopeCode)
		knowledgeKnowledgeScopeItem.Description = NormalizeString((*source).Description)
		knowledgeKnowledgeScopeItem.Aliases = NormalizeString((*source).Aliases)
		knowledgeKnowledgeScopeItem.Examples = NormalizeString((*source).Examples)
		knowledgeKnowledgeScopeItem.SortOrder = (*source).SortOrder
		pKnowledgeKnowledgeScopeItem = &knowledgeKnowledgeScopeItem
	}
	return pKnowledgeKnowledgeScopeItem
}
func ToKnowledgeScopeItemList(source []*entity2.KnowledgeScopeNode) []*knowledge.KnowledgeScopeItem {
	var pKnowledgeKnowledgeScopeItemList []*knowledge.KnowledgeScopeItem
	if source != nil {
		pKnowledgeKnowledgeScopeItemList = make([]*knowledge.KnowledgeScopeItem, len(source))
		for i := 0; i < len(source); i++ {
			pKnowledgeKnowledgeScopeItemList[i] = ToKnowledgeScopeItem(source[i])
		}
	}
	return pKnowledgeKnowledgeScopeItemList
}
func ToKnowledgeScopeNodeModel(source *entity2.KnowledgeScopeNode) *model.KnowledgeScopeNode {
	var pModelKnowledgeScopeNode *model.KnowledgeScopeNode
	if source != nil {
		var modelKnowledgeScopeNode model.KnowledgeScopeNode
		modelKnowledgeScopeNode.ID = (*source).ID
		modelKnowledgeScopeNode.ScopeCode = NormalizeString((*source).ScopeCode)
		modelKnowledgeScopeNode.ScopeName = NormalizeString((*source).ScopeName)
		modelKnowledgeScopeNode.ParentScopeCode = NormalizeString((*source).ParentScopeCode)
		modelKnowledgeScopeNode.Description = NormalizeString((*source).Description)
		modelKnowledgeScopeNode.Aliases = NormalizeString((*source).Aliases)
		modelKnowledgeScopeNode.Examples = NormalizeString((*source).Examples)
		modelKnowledgeScopeNode.SortOrder = (*source).SortOrder
		pModelKnowledgeScopeNode = &modelKnowledgeScopeNode
	}
	return pModelKnowledgeScopeNode
}
func ToKnowledgeTopicDocumentRelationItem(source *entity2.KnowledgeTopicDocumentRelation) *knowledge.TopicDocumentRelationItem {
	var pKnowledgeTopicDocumentRelationItem *knowledge.TopicDocumentRelationItem
	if source != nil {
		var knowledgeTopicDocumentRelationItem knowledge.TopicDocumentRelationItem
		knowledgeTopicDocumentRelationItem.TopicCode = NormalizeString((*source).TopicCode)
		knowledgeTopicDocumentRelationItem.DocumentId = (*source).DocumentId
		knowledgeTopicDocumentRelationItem.DocumentName = NormalizeString((*source).DocumentName)
		knowledgeTopicDocumentRelationItem.KnowledgeScopeCode = NormalizeString((*source).KnowledgeScopeCode)
		knowledgeTopicDocumentRelationItem.KnowledgeScopeName = NormalizeString((*source).KnowledgeScopeName)
		knowledgeTopicDocumentRelationItem.BusinessCategory = NormalizeString((*source).BusinessCategory)
		knowledgeTopicDocumentRelationItem.DocumentTags = NormalizeString((*source).DocumentTags)
		knowledgeTopicDocumentRelationItem.RelationScore = (*source).RelationScore
		knowledgeTopicDocumentRelationItem.RelationSource = NormalizeString((*source).RelationSource)
		knowledgeTopicDocumentRelationItem.Reason = NormalizeString((*source).Reason)
		pKnowledgeTopicDocumentRelationItem = &knowledgeTopicDocumentRelationItem
	}
	return pKnowledgeTopicDocumentRelationItem
}
func ToKnowledgeTopicDocumentRelationItemList(source []*entity2.KnowledgeTopicDocumentRelation) []*knowledge.TopicDocumentRelationItem {
	var pKnowledgeTopicDocumentRelationItemList []*knowledge.TopicDocumentRelationItem
	if source != nil {
		pKnowledgeTopicDocumentRelationItemList = make([]*knowledge.TopicDocumentRelationItem, len(source))
		for i := 0; i < len(source); i++ {
			pKnowledgeTopicDocumentRelationItemList[i] = ToKnowledgeTopicDocumentRelationItem(source[i])
		}
	}
	return pKnowledgeTopicDocumentRelationItemList
}
func ToKnowledgeTopicDocumentRelationModel(source *entity2.KnowledgeTopicDocumentRelation) *model.KnowledgeTopicDocumentRelation {
	var pModelKnowledgeTopicDocumentRelation *model.KnowledgeTopicDocumentRelation
	if source != nil {
		var modelKnowledgeTopicDocumentRelation model.KnowledgeTopicDocumentRelation
		modelKnowledgeTopicDocumentRelation.ID = (*source).ID
		modelKnowledgeTopicDocumentRelation.TopicCode = NormalizeString((*source).TopicCode)
		modelKnowledgeTopicDocumentRelation.DocumentId = (*source).DocumentId
		modelKnowledgeTopicDocumentRelation.RelationScore = (*source).RelationScore
		modelKnowledgeTopicDocumentRelation.RelationSource = NormalizeString((*source).RelationSource)
		modelKnowledgeTopicDocumentRelation.Reason = NormalizeString((*source).Reason)
		pModelKnowledgeTopicDocumentRelation = &modelKnowledgeTopicDocumentRelation
	}
	return pModelKnowledgeTopicDocumentRelation
}
func ToKnowledgeTopicItem(source *entity2.KnowledgeTopicNode) *knowledge.KnowledgeTopicItem {
	var pKnowledgeKnowledgeTopicItem *knowledge.KnowledgeTopicItem
	if source != nil {
		var knowledgeKnowledgeTopicItem knowledge.KnowledgeTopicItem
		knowledgeKnowledgeTopicItem.ID = (*source).ID
		knowledgeKnowledgeTopicItem.TopicCode = NormalizeString((*source).TopicCode)
		knowledgeKnowledgeTopicItem.TopicName = NormalizeString((*source).TopicName)
		knowledgeKnowledgeTopicItem.ScopeCode = NormalizeString((*source).ScopeCode)
		knowledgeKnowledgeTopicItem.Description = NormalizeString((*source).Description)
		knowledgeKnowledgeTopicItem.Aliases = NormalizeString((*source).Aliases)
		knowledgeKnowledgeTopicItem.Examples = NormalizeString((*source).Examples)
		knowledgeKnowledgeTopicItem.AnswerShape = NormalizeString((*source).AnswerShape)
		knowledgeKnowledgeTopicItem.ExecutionPreference = NormalizeString((*source).ExecutionPreference)
		knowledgeKnowledgeTopicItem.SortOrder = (*source).SortOrder
		pKnowledgeKnowledgeTopicItem = &knowledgeKnowledgeTopicItem
	}
	return pKnowledgeKnowledgeTopicItem
}
func ToKnowledgeTopicItemList(source []*entity2.KnowledgeTopicNode) []*knowledge.KnowledgeTopicItem {
	var pKnowledgeKnowledgeTopicItemList []*knowledge.KnowledgeTopicItem
	if source != nil {
		pKnowledgeKnowledgeTopicItemList = make([]*knowledge.KnowledgeTopicItem, len(source))
		for i := 0; i < len(source); i++ {
			pKnowledgeKnowledgeTopicItemList[i] = ToKnowledgeTopicItem(source[i])
		}
	}
	return pKnowledgeKnowledgeTopicItemList
}
func ToKnowledgeTopicNodeModel(source *entity2.KnowledgeTopicNode) *model.KnowledgeTopicNode {
	var pModelKnowledgeTopicNode *model.KnowledgeTopicNode
	if source != nil {
		var modelKnowledgeTopicNode model.KnowledgeTopicNode
		modelKnowledgeTopicNode.ID = (*source).ID
		modelKnowledgeTopicNode.TopicCode = NormalizeString((*source).TopicCode)
		modelKnowledgeTopicNode.TopicName = NormalizeString((*source).TopicName)
		modelKnowledgeTopicNode.ScopeCode = NormalizeString((*source).ScopeCode)
		modelKnowledgeTopicNode.Description = NormalizeString((*source).Description)
		modelKnowledgeTopicNode.Aliases = NormalizeString((*source).Aliases)
		modelKnowledgeTopicNode.Examples = NormalizeString((*source).Examples)
		modelKnowledgeTopicNode.AnswerShape = NormalizeString((*source).AnswerShape)
		modelKnowledgeTopicNode.ExecutionPreference = NormalizeString((*source).ExecutionPreference)
		modelKnowledgeTopicNode.SortOrder = (*source).SortOrder
		pModelKnowledgeTopicNode = &modelKnowledgeTopicNode
	}
	return pModelKnowledgeTopicNode
}
