// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package convert

import (
	chat "github.com/swiftbit/know-agent/api/chat"
	document "github.com/swiftbit/know-agent/api/document"
	common "github.com/swiftbit/know-agent/common"
	entity1 "github.com/swiftbit/know-agent/internal/domain/chat/model/entity"
	vo "github.com/swiftbit/know-agent/internal/domain/chat/model/vo"
	entity "github.com/swiftbit/know-agent/internal/domain/document/model/entity"
	vo1 "github.com/swiftbit/know-agent/internal/domain/document/model/vo"
	model "github.com/swiftbit/know-agent/internal/infrastructure/model"
	"time"
)

func FromChatReq(source *chat.ChatReq) *vo.ChatCommand {
	var pVoChatCommand *vo.ChatCommand
	if source != nil {
		var voChatCommand vo.ChatCommand
		voChatCommand.Question = (*source).Question
		voChatCommand.ConversationId = (*source).ConversationId
		voChatCommand.ChatMode = ToChatQueryMode((*source).ChatMode)
		voChatCommand.SelectedDocumentId = (*source).SelectedDocumentId
		pVoChatCommand = &voChatCommand
	}
	return pVoChatCommand
}
func FromUploadDocumentReq(source *document.UploadDocumentReq) *entity.Document {
	var pEntityDocument *entity.Document
	if source != nil {
		var entityDocument entity.Document
		entityDocument.DocumentName = (*source).DocumentName
		entityDocument.KnowledgeScopeCode = (*source).KnowledgeScopeCode
		entityDocument.KnowledgeScopeName = (*source).KnowledgeScopeName
		entityDocument.BusinessCategory = (*source).BusinessCategory
		entityDocument.DocumentTags = (*source).DocumentTags
		entityDocument.OperatorId = (*source).OperatorId
		pEntityDocument = &entityDocument
	}
	return pEntityDocument
}
func ToBuildIndexResp(source *vo1.DocumentIndexBuild) *document.BuildIndexResp {
	var pDocumentBuildIndexResp *document.BuildIndexResp
	if source != nil {
		var documentBuildIndexResp document.BuildIndexResp
		documentBuildIndexResp.TaskId = (*source).TaskId
		documentBuildIndexResp.DocumentId = (*source).DocumentId
		documentBuildIndexResp.TaskType = (*source).TaskType
		documentBuildIndexResp.TaskTypeName = (*source).TaskTypeName
		documentBuildIndexResp.TaskStatus = (*source).TaskStatus
		documentBuildIndexResp.TaskStatusName = (*source).TaskStatusName
		documentBuildIndexResp.IndexStatus = (*source).IndexStatus
		documentBuildIndexResp.IndexStatusName = (*source).IndexStatusName
		pDocumentBuildIndexResp = &documentBuildIndexResp
	}
	return pDocumentBuildIndexResp
}
func ToChatDialogueModel(source *entity1.ChatDialogue) *model.ChatDialogue {
	var pModelChatDialogue *model.ChatDialogue
	if source != nil {
		var modelChatDialogue model.ChatDialogue
		modelChatDialogue.Model = entityChatDialogueToCommonModel((*source))
		modelChatDialogue.ConversationId = (*source).ConversationId
		modelChatDialogue.SessionStatus = (*source).SessionStatus
		modelChatDialogue.ChatMode = (*source).ChatMode
		modelChatDialogue.SelectedDocumentId = (*source).SelectedDocumentId
		modelChatDialogue.SelectedDocumentName = (*source).SelectedDocumentName
		pModelChatDialogue = &modelChatDialogue
	}
	return pModelChatDialogue
}
func ToChatExchangeModel(source *entity1.ChatExchange) *model.ChatExchange {
	var pModelChatExchange *model.ChatExchange
	if source != nil {
		var modelChatExchange model.ChatExchange
		modelChatExchange.Model = entityChatExchangeToCommonModel((*source))
		modelChatExchange.ConversationId = (*source).ConversationId
		modelChatExchange.Question = (*source).Question
		modelChatExchange.Answer = (*source).Answer
		modelChatExchange.ThinkingSteps = commonJSONArrayToCommonJSONArray((*source).ThinkingSteps)
		modelChatExchange.ReferenceList = commonJSONArrayToCommonJSONArray((*source).ReferenceList)
		modelChatExchange.RecommendationList = commonJSONArrayToCommonJSONArray((*source).RecommendationList)
		modelChatExchange.UsedToolList = commonJSONArrayToCommonJSONArray((*source).UsedToolList)
		modelChatExchange.DebugTraceJson = (*source).DebugTraceJson
		modelChatExchange.TurnStatus = (*source).TurnStatus
		modelChatExchange.ErrorMessage = (*source).ErrorMessage
		modelChatExchange.FirstResponseTimeMs = (*source).FirstResponseTimeMs
		modelChatExchange.TotalResponseTimeMs = (*source).TotalResponseTimeMs
		pModelChatExchange = &modelChatExchange
	}
	return pModelChatExchange
}
func ToDocumentListItem(source *entity.Document) *document.DocumentListItem {
	var pDocumentDocumentListItem *document.DocumentListItem
	if source != nil {
		var documentDocumentListItem document.DocumentListItem
		documentDocumentListItem.DocumentId = (*source).ID
		documentDocumentListItem.DocumentName = (*source).DocumentName
		documentDocumentListItem.OriginalFileName = (*source).OriginalFileName
		documentDocumentListItem.FileType = (*source).FileType
		documentDocumentListItem.FileTypeName = (*source).FileTypeName
		documentDocumentListItem.FileSize = (*source).FileSize
		documentDocumentListItem.CharCount = (*source).CharCount
		documentDocumentListItem.TokenCount = (*source).TokenCount
		documentDocumentListItem.ParseStatus = (*source).ParseStatus
		documentDocumentListItem.ParseStatusName = (*source).ParseStatusName
		documentDocumentListItem.StrategyStatus = (*source).StrategyStatus
		documentDocumentListItem.StrategyStatusName = (*source).StrategyStatusName
		documentDocumentListItem.IndexStatus = (*source).IndexStatus
		documentDocumentListItem.IndexStatusName = (*source).IndexStatusName
		documentDocumentListItem.ParseErrorMsg = (*source).ParseErrorMsg
		documentDocumentListItem.KnowledgeScopeCode = (*source).KnowledgeScopeCode
		documentDocumentListItem.KnowledgeScopeName = (*source).KnowledgeScopeName
		documentDocumentListItem.BusinessCategory = (*source).BusinessCategory
		documentDocumentListItem.DocumentTags = (*source).DocumentTags
		documentDocumentListItem.CurrentPlanId = (*source).CurrentPlanId
		documentDocumentListItem.LastIndexTaskId = (*source).LastIndexTaskId
		documentDocumentListItem.LatestTaskId = (*source).LatestTaskId
		documentDocumentListItem.LatestTaskType = (*source).LatestTaskType
		documentDocumentListItem.LatestTaskTypeName = (*source).LatestTaskTypeName
		documentDocumentListItem.LatestTaskStatus = (*source).LatestTaskStatus
		documentDocumentListItem.LatestTaskStatusName = (*source).LatestTaskStatusName
		documentDocumentListItem.CreateTime = TimeToString((*source).CreateTime)
		documentDocumentListItem.UpdateTime = TimeToString((*source).UpdateTime)
		pDocumentDocumentListItem = &documentDocumentListItem
	}
	return pDocumentDocumentListItem
}
func ToDocumentListItemList(source []*entity.Document) []*document.DocumentListItem {
	var pDocumentDocumentListItemList []*document.DocumentListItem
	if source != nil {
		pDocumentDocumentListItemList = make([]*document.DocumentListItem, len(source))
		for i := 0; i < len(source); i++ {
			pDocumentDocumentListItemList[i] = ToDocumentListItem(source[i])
		}
	}
	return pDocumentDocumentListItemList
}
func ToDocumentModel(source *entity.Document) *model.Document {
	var pModelDocument *model.Document
	if source != nil {
		var modelDocument model.Document
		modelDocument.Model = entityDocumentToCommonModel((*source))
		modelDocument.DocumentName = (*source).DocumentName
		modelDocument.OriginalFileName = (*source).OriginalFileName
		modelDocument.FileType = (*source).FileType
		modelDocument.MimeType = (*source).MimeType
		modelDocument.FileSize = (*source).FileSize
		modelDocument.StorageType = (*source).StorageType
		modelDocument.BucketName = (*source).BucketName
		modelDocument.ObjectName = (*source).ObjectName
		modelDocument.ObjectUrl = (*source).ObjectUrl
		modelDocument.ParseStatus = (*source).ParseStatus
		modelDocument.StrategyStatus = (*source).StrategyStatus
		modelDocument.IndexStatus = (*source).IndexStatus
		modelDocument.CharCount = (*source).CharCount
		modelDocument.TokenCount = (*source).TokenCount
		modelDocument.StructureLevel = (*source).StructureLevel
		modelDocument.ContentQualityLevel = (*source).ContentQualityLevel
		modelDocument.ParseTextPath = (*source).ParseTextPath
		modelDocument.ParseErrorMsg = (*source).ParseErrorMsg
		modelDocument.KnowledgeScopeCode = (*source).KnowledgeScopeCode
		modelDocument.KnowledgeScopeName = (*source).KnowledgeScopeName
		modelDocument.BusinessCategory = (*source).BusinessCategory
		modelDocument.DocumentTags = (*source).DocumentTags
		modelDocument.CurrentPlanId = (*source).CurrentPlanId
		modelDocument.LastParseTaskId = (*source).LastParseTaskId
		modelDocument.StructureNodeCount = (*source).StructureNodeCount
		modelDocument.LastIndexTaskId = (*source).LastIndexTaskId
		pModelDocument = &modelDocument
	}
	return pModelDocument
}
func ToDocumentStrategyPlan(source *entity.DocumentStrategyPlan) *document.DocumentStrategyPlan {
	var pDocumentDocumentStrategyPlan *document.DocumentStrategyPlan
	if source != nil {
		var documentDocumentStrategyPlan document.DocumentStrategyPlan
		documentDocumentStrategyPlan.PlanId = (*source).ID
		documentDocumentStrategyPlan.PlanVersion = (*source).PlanVersion
		documentDocumentStrategyPlan.PlanSource = (*source).PlanSource
		documentDocumentStrategyPlan.PlanSourceName = (*source).PlanSourceName
		documentDocumentStrategyPlan.PlanStatus = (*source).PlanStatus
		documentDocumentStrategyPlan.PlanStatusName = (*source).PlanStatusName
		documentDocumentStrategyPlan.StrategySnapshot = (*source).StrategySnapshot
		documentDocumentStrategyPlan.RecommendReason = (*source).RecommendReason
		documentDocumentStrategyPlan.ParentPipeline = pEntityDocumentStrategyPipelineToPDocumentDocumentStrategyPipeline((*source).ParentPipeline)
		documentDocumentStrategyPlan.ChildPipeline = pEntityDocumentStrategyPipelineToPDocumentDocumentStrategyPipeline((*source).ChildPipeline)
		pDocumentDocumentStrategyPlan = &documentDocumentStrategyPlan
	}
	return pDocumentDocumentStrategyPlan
}
func ToDocumentTaskLogModel(source *entity.DocumentTaskLog) *model.DocumentTaskLog {
	var pModelDocumentTaskLog *model.DocumentTaskLog
	if source != nil {
		var modelDocumentTaskLog model.DocumentTaskLog
		modelDocumentTaskLog.Model = entityDocumentTaskLogToCommonModel((*source))
		modelDocumentTaskLog.TaskId = (*source).TaskId
		modelDocumentTaskLog.DocumentId = (*source).DocumentId
		modelDocumentTaskLog.StageType = (*source).StageType
		modelDocumentTaskLog.EventType = (*source).EventType
		modelDocumentTaskLog.LogLevel = (*source).LogLevel
		modelDocumentTaskLog.OperatorType = (*source).OperatorType
		modelDocumentTaskLog.OperatorId = (*source).OperatorId
		modelDocumentTaskLog.Content = (*source).Content
		modelDocumentTaskLog.DetailJson = (*source).DetailJson
		pModelDocumentTaskLog = &modelDocumentTaskLog
	}
	return pModelDocumentTaskLog
}
func ToDocumentTaskModel(source *entity.DocumentTask) *model.DocumentTask {
	var pModelDocumentTask *model.DocumentTask
	if source != nil {
		var modelDocumentTask model.DocumentTask
		modelDocumentTask.Model = entityDocumentTaskToCommonModel((*source))
		modelDocumentTask.DocumentId = (*source).DocumentId
		modelDocumentTask.PlanId = (*source).PlanId
		modelDocumentTask.TaskType = (*source).TaskType
		modelDocumentTask.TaskStatus = (*source).TaskStatus
		modelDocumentTask.CurrentStage = (*source).CurrentStage
		modelDocumentTask.TriggerSource = (*source).TriggerSource
		modelDocumentTask.StrategySnapshot = (*source).StrategySnapshot
		modelDocumentTask.RetryCount = (*source).RetryCount
		modelDocumentTask.StartTime = timeTimeToTimeTime((*source).StartTime)
		modelDocumentTask.FinishTime = timeTimeToTimeTime((*source).FinishTime)
		modelDocumentTask.CostMillis = (*source).CostMillis
		modelDocumentTask.ErrorCode = (*source).ErrorCode
		modelDocumentTask.ErrorMsg = (*source).ErrorMsg
		modelDocumentTask.ExtJson = (*source).ExtJson
		pModelDocumentTask = &modelDocumentTask
	}
	return pModelDocumentTask
}
func ToQueryStrategyPlanResp(source *entity.Document) *document.QueryStrategyPlanResp {
	var pDocumentQueryStrategyPlanResp *document.QueryStrategyPlanResp
	if source != nil {
		var documentQueryStrategyPlanResp document.QueryStrategyPlanResp
		documentQueryStrategyPlanResp.DocumentId = (*source).ID
		documentQueryStrategyPlanResp.DocumentName = (*source).DocumentName
		documentQueryStrategyPlanResp.ParseStatus = (*source).ParseStatus
		documentQueryStrategyPlanResp.ParseStatusName = (*source).ParseStatusName
		documentQueryStrategyPlanResp.StrategyStatus = (*source).StrategyStatus
		documentQueryStrategyPlanResp.StrategyStatusName = (*source).StrategyStatusName
		documentQueryStrategyPlanResp.IndexStatus = (*source).IndexStatus
		documentQueryStrategyPlanResp.IndexStatusName = (*source).IndexStatusName
		documentQueryStrategyPlanResp.ParseErrorMsg = (*source).ParseErrorMsg
		documentQueryStrategyPlanResp.PlanReady = (*source).PlanReady
		pDocumentQueryStrategyPlanResp = &documentQueryStrategyPlanResp
	}
	return pDocumentQueryStrategyPlanResp
}
func ToUploadDocumentResp(source *vo1.DocumentUpload) *document.UploadDocumentResp {
	var pDocumentUploadDocumentResp *document.UploadDocumentResp
	if source != nil {
		var documentUploadDocumentResp document.UploadDocumentResp
		documentUploadDocumentResp.DocumentId = (*source).DocumentId
		documentUploadDocumentResp.TaskId = (*source).TaskId
		documentUploadDocumentResp.DocumentName = (*source).DocumentName
		documentUploadDocumentResp.ParseStatus = (*source).ParseStatus
		documentUploadDocumentResp.StrategyStatus = (*source).StrategyStatus
		documentUploadDocumentResp.IndexStatus = (*source).IndexStatus
		pDocumentUploadDocumentResp = &documentUploadDocumentResp
	}
	return pDocumentUploadDocumentResp
}
func commonJSONArrayToCommonJSONArray(source common.JSONArray) common.JSONArray {
	return source
}
func entityChatDialogueToCommonModel(source entity1.ChatDialogue) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityChatExchangeToCommonModel(source entity1.ChatExchange) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityDocumentTaskLogToCommonModel(source entity.DocumentTaskLog) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityDocumentTaskToCommonModel(source entity.DocumentTask) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func entityDocumentToCommonModel(source entity.Document) common.Model {
	var commonModel common.Model
	commonModel.ID = source.ID
	return commonModel
}
func pEntityDocumentStrategyPipelineToPDocumentDocumentStrategyPipeline(source *entity.DocumentStrategyPipeline) *document.DocumentStrategyPipeline {
	var pDocumentDocumentStrategyPipeline *document.DocumentStrategyPipeline
	if source != nil {
		var documentDocumentStrategyPipeline document.DocumentStrategyPipeline
		documentDocumentStrategyPipeline.PipelineType = (*source).PipelineType
		documentDocumentStrategyPipeline.PipelineTypeName = (*source).PipelineTypeName
		documentDocumentStrategyPipeline.StrategySnapshot = (*source).StrategySnapshot
		if (*source).Steps != nil {
			documentDocumentStrategyPipeline.Steps = make([]*document.DocumentStrategyStep, len((*source).Steps))
			for i := 0; i < len((*source).Steps); i++ {
				documentDocumentStrategyPipeline.Steps[i] = pEntityDocumentStrategyStepToPDocumentDocumentStrategyStep((*source).Steps[i])
			}
		}
		pDocumentDocumentStrategyPipeline = &documentDocumentStrategyPipeline
	}
	return pDocumentDocumentStrategyPipeline
}
func pEntityDocumentStrategyStepToPDocumentDocumentStrategyStep(source *entity.DocumentStrategyStep) *document.DocumentStrategyStep {
	var pDocumentDocumentStrategyStep *document.DocumentStrategyStep
	if source != nil {
		var documentDocumentStrategyStep document.DocumentStrategyStep
		documentDocumentStrategyStep.StepNo = (*source).StepNo
		documentDocumentStrategyStep.PipelineType = (*source).PipelineType
		documentDocumentStrategyStep.PipelineTypeName = (*source).PipelineTypeName
		documentDocumentStrategyStep.StrategyType = (*source).StrategyType
		documentDocumentStrategyStep.StrategyTypeName = (*source).StrategyTypeName
		documentDocumentStrategyStep.StrategyRole = (*source).StrategyRole
		documentDocumentStrategyStep.StrategyRoleName = (*source).StrategyRoleName
		documentDocumentStrategyStep.SourceType = (*source).SourceType
		documentDocumentStrategyStep.SourceTypeName = (*source).SourceTypeName
		documentDocumentStrategyStep.ExecuteStatus = (*source).ExecuteStatus
		documentDocumentStrategyStep.ExecuteStatusName = (*source).ExecuteStatusName
		documentDocumentStrategyStep.RecommendReason = (*source).RecommendReason
		pDocumentDocumentStrategyStep = &documentDocumentStrategyStep
	}
	return pDocumentDocumentStrategyStep
}
func timeTimeToTimeTime(source time.Time) time.Time {
	return source
}
