CREATE TABLE `chat_channel_execution` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `conversation_id` VARCHAR(64) NOT NULL COMMENT '对话ID',
  `exchange_id` BIGINT NOT NULL COMMENT '交换ID',
  `trace_id` VARCHAR(128) NOT NULL COMMENT '跟踪ID',
  `sub_question_index` INT NOT NULL DEFAULT 0 COMMENT '子问题索引',
  `sub_question` TEXT COMMENT '子问题',
  `channel_type` VARCHAR(32) NOT NULL COMMENT '渠道类型',
  `execution_state` INT NOT NULL DEFAULT 0 COMMENT '执行状态',
  `start_time` DATETIME NOT NULL COMMENT '开始时间',
  `end_time` DATETIME COMMENT '结束时间',
  `duration_ms` BIGINT NOT NULL DEFAULT 0 COMMENT '执行时长（毫秒）',
  `recalled_count` INT NOT NULL DEFAULT 0 COMMENT '召回数量',
  `accepted_count` INT NOT NULL DEFAULT 0 COMMENT '接受数量',
  `final_selected_count` INT NOT NULL DEFAULT 0 COMMENT '最终选中数量',
  `avg_score` DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT '平均分数',
  `max_score` DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT '最大分数',
  `min_score` DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT '最小分数',
  `config_snapshot` TEXT COMMENT '配置快照',
  `error_message` TEXT COMMENT '错误信息',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  INDEX `idx_conversation_id` (`conversation_id`),
  INDEX `idx_exchange_id` (`exchange_id`),
  INDEX `idx_trace_id` (`trace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='通道执行记录';

CREATE TABLE `chat_dialogue` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `conversation_id` VARCHAR(64) NOT NULL COMMENT '会话ID',
  `session_status` INT NOT NULL DEFAULT 0 COMMENT '会话状态',
  `chat_mode` INT NOT NULL DEFAULT 0 COMMENT '聊天模式',
  `selected_document_id` BIGINT NOT NULL DEFAULT 0 COMMENT '选中的文档ID',
  `selected_document_name` VARCHAR(255) COMMENT '选中的文档名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_conversation_id` (`conversation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会话记录表';

CREATE TABLE `chat_exchange` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `conversation_id` VARCHAR(64) NOT NULL COMMENT '会话ID',
  `question` TEXT NOT NULL COMMENT '用户问题',
  `answer` LONGTEXT COMMENT '回答内容',
  `thinking_steps` JSON COMMENT '思维步骤',
  `references` JSON COMMENT '参考列表',
  `recommendations` JSON COMMENT '建议列表',
  `used_tools` JSON COMMENT '工具使用列表',
  `debug_trace_json` LONGTEXT COMMENT '调试跟踪JSON',
  `turn_status` INT NOT NULL DEFAULT 0 COMMENT '轮次状态',
  `error_message` TEXT COMMENT '错误信息',
  `first_response_time_ms` BIGINT NOT NULL DEFAULT 0 COMMENT '首个响应时间毫秒',
  `total_response_time_ms` BIGINT NOT NULL DEFAULT 0 COMMENT '总响应时间毫秒',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  INDEX `idx_conversation_id` (`conversation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='对话记录表';

CREATE TABLE `chat_exchange_trace_stage` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `conversation_id` VARCHAR(64) NOT NULL COMMENT '会话ID',
  `exchange_id` BIGINT NOT NULL COMMENT '交换ID',
  `trace_id` VARCHAR(128) NOT NULL COMMENT '跟踪ID',
  `stage_code` VARCHAR(64) NOT NULL COMMENT '阶段编码',
  `stage_name` VARCHAR(128) NOT NULL COMMENT '阶段名称',
  `stage_order` INT NOT NULL DEFAULT 0 COMMENT '阶段顺序',
  `stage_level` INT NOT NULL DEFAULT 0 COMMENT '阶段层级',
  `parent_stage_id` BIGINT NOT NULL DEFAULT 0 COMMENT '父阶段ID',
  `execution_mode` VARCHAR(32) NOT NULL COMMENT '执行模式',
  `stage_state` INT NOT NULL DEFAULT 0 COMMENT '阶段状态',
  `start_time` DATETIME NOT NULL COMMENT '开始时间',
  `end_time` DATETIME COMMENT '结束时间',
  `duration_ms` BIGINT NOT NULL DEFAULT 0 COMMENT '执行时长（毫秒）',
  `summary_text` TEXT COMMENT '阶段摘要',
  `error_message` TEXT COMMENT '错误信息',
  `snapshot_json` LONGTEXT COMMENT '快照JSON',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  INDEX `idx_conversation_id` (`conversation_id`),
  INDEX `idx_exchange_id` (`exchange_id`),
  INDEX `idx_trace_id` (`trace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='对话执行阶段追踪';

CREATE TABLE `chat_memory_summary` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `conversation_id` VARCHAR(64) NOT NULL COMMENT '会话ID',
  `covered_exchange_id` BIGINT NOT NULL DEFAULT 0 COMMENT '覆盖的最后轮次ID',
  `covered_exchange_count` INT NOT NULL DEFAULT 0 COMMENT '覆盖的轮数',
  `compression_count` INT NOT NULL DEFAULT 0 COMMENT '压缩次数',
  `summary_version` INT NOT NULL DEFAULT 1 COMMENT '摘要版本',
  `summary_text` TEXT NOT NULL COMMENT '摘要文本',
  `summary_json` LONGTEXT COMMENT '摘要JSON',
  `last_source_update_time` DATETIME NOT NULL COMMENT '最后源更新时间',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_conversation_id` (`conversation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会话记忆摘要';

CREATE TABLE `chat_retrieval_result` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `conversation_id` VARCHAR(64) NOT NULL COMMENT '对话ID',
  `exchange_id` BIGINT NOT NULL COMMENT '交互ID',
  `trace_id` VARCHAR(128) NOT NULL COMMENT '跟踪ID',
  `sub_question_index` INT NOT NULL DEFAULT 0 COMMENT '子问题索引',
  `sub_question` TEXT COMMENT '子问题',
  `channel_type` VARCHAR(32) NOT NULL COMMENT '渠道类型',
  `channel_rank` INT NOT NULL DEFAULT 0 COMMENT '渠道排名',
  `rrf_rank` INT NOT NULL DEFAULT 0 COMMENT 'RRF排名',
  `final_rank` INT NOT NULL DEFAULT 0 COMMENT '最终排名',
  `original_score` DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT '原始分数',
  `rrf_score` DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'RRF分数',
  `rerank_score` DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT '重排分数',
  `gate_passed` TINYINT NOT NULL DEFAULT 0 COMMENT '是否通过门控',
  `is_elevated` TINYINT NOT NULL DEFAULT 0 COMMENT '是否升级',
  `is_selected` TINYINT NOT NULL DEFAULT 0 COMMENT '是否选中',
  `selection_reason` VARCHAR(512) COMMENT '选中原因',
  `document_id` BIGINT NOT NULL DEFAULT 0 COMMENT '文档ID',
  `document_name` VARCHAR(255) COMMENT '文档名称',
  `chunk_id` BIGINT NOT NULL DEFAULT 0 COMMENT '分块ID',
  `chunk_no` INT NOT NULL DEFAULT 0 COMMENT '分块序号',
  `parent_block_id` BIGINT NOT NULL DEFAULT 0 COMMENT '父块ID',
  `parent_block_no` INT NOT NULL DEFAULT 0 COMMENT '父块序号',
  `section_path` VARCHAR(512) COMMENT '章节路径',
  `chunk_text_preview` TEXT COMMENT '分块文本预览',
  `chunk_char_count` INT NOT NULL DEFAULT 0 COMMENT '分块字符数',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  INDEX `idx_conversation_id` (`conversation_id`),
  INDEX `idx_exchange_id` (`exchange_id`),
  INDEX `idx_document_id` (`document_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='对话检索结果';

CREATE TABLE `document` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `document_name` VARCHAR(255) NOT NULL COMMENT '文档名称',
  `original_file_name` VARCHAR(255) NOT NULL COMMENT '原始文件名',
  `file_type` INT NOT NULL DEFAULT 0 COMMENT '文件类型',
  `mime_type` VARCHAR(128) COMMENT '媒体类型',
  `file_size` BIGINT NOT NULL DEFAULT 0 COMMENT '文件大小',
  `storage_type` INT NOT NULL DEFAULT 0 COMMENT '存储类型',
  `bucket_name` VARCHAR(128) COMMENT '存储桶名称',
  `object_name` VARCHAR(512) COMMENT '对象名称',
  `object_url` VARCHAR(512) COMMENT '对象访问地址',
  `parse_status` INT NOT NULL DEFAULT 0 COMMENT '解析状态',
  `strategy_status` INT NOT NULL DEFAULT 0 COMMENT '策略状态',
  `index_status` INT NOT NULL DEFAULT 0 COMMENT '索引状态',
  `char_count` INT NOT NULL DEFAULT 0 COMMENT '字符数',
  `token_count` INT NOT NULL DEFAULT 0 COMMENT 'Token数量',
  `structure_level` INT NOT NULL DEFAULT 0 COMMENT '结构化等级',
  `content_quality_level` INT NOT NULL DEFAULT 0 COMMENT '内容质量等级',
  `parse_text_path` VARCHAR(512) COMMENT '解析文本路径',
  `parse_error_msg` TEXT COMMENT '解析错误信息',
  `knowledge_scope_code` VARCHAR(64) COMMENT '知识范围编码',
  `knowledge_scope_name` VARCHAR(128) COMMENT '知识范围名称',
  `business_category` VARCHAR(128) COMMENT '业务分类',
  `document_tags` TEXT COMMENT '文档标签',
  `current_plan_id` BIGINT NOT NULL DEFAULT 0 COMMENT '当前方案ID',
  `last_parse_task_id` BIGINT NOT NULL DEFAULT 0 COMMENT '上一次解析任务ID',
  `structure_node_count` INT NOT NULL DEFAULT 0 COMMENT '结构化节点数',
  `last_index_task_id` BIGINT NOT NULL DEFAULT 0 COMMENT '上一次索引任务ID',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  INDEX `idx_parse_status` (`parse_status`),
  INDEX `idx_index_status` (`index_status`),
  INDEX `idx_knowledge_scope_code` (`knowledge_scope_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文档表';

CREATE TABLE `document_chunk` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `document_id` BIGINT NOT NULL COMMENT '文档ID',
  `task_id` BIGINT NOT NULL DEFAULT 0 COMMENT '任务ID',
  `plan_id` BIGINT NOT NULL DEFAULT 0 COMMENT '计划ID',
  `parent_block_id` BIGINT NOT NULL DEFAULT 0 COMMENT '父块ID',
  `chunk_no` INT NOT NULL DEFAULT 0 COMMENT '块序号',
  `source_type` INT NOT NULL DEFAULT 0 COMMENT '来源类型',
  `section_path` VARCHAR(512) COMMENT '章节路径',
  `structure_node_id` BIGINT NOT NULL DEFAULT 0 COMMENT '结构节点ID',
  `structure_node_type` INT NOT NULL DEFAULT 0 COMMENT '结构节点类型',
  `canonical_path` VARCHAR(512) COMMENT '规范路径',
  `item_index` INT NOT NULL DEFAULT 0 COMMENT '项索引',
  `chunk_text` TEXT NOT NULL COMMENT '块文本',
  `char_count` INT NOT NULL DEFAULT 0 COMMENT '字符数',
  `token_count` INT NOT NULL DEFAULT 0 COMMENT 'token数',
  `vector_status` INT NOT NULL DEFAULT 0 COMMENT '向量状态',
  `vector_store_type` INT NOT NULL DEFAULT 0 COMMENT '向量存储类型',
  `vector_id` VARCHAR(128) COMMENT '向量ID',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  INDEX `idx_document_id` (`document_id`),
  INDEX `idx_parent_block_id` (`parent_block_id`),
  INDEX `idx_vector_status` (`vector_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文档分块';

CREATE TABLE `document_parent_block` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `document_id` BIGINT NOT NULL COMMENT '文档ID',
  `task_id` BIGINT NOT NULL DEFAULT 0 COMMENT '任务ID',
  `plan_id` BIGINT NOT NULL DEFAULT 0 COMMENT '计划ID',
  `parent_no` INT NOT NULL DEFAULT 0 COMMENT '父节点编号',
  `source_type` INT NOT NULL DEFAULT 0 COMMENT '来源类型',
  `section_path` VARCHAR(255) COMMENT '章节路径',
  `structure_node_id` BIGINT NOT NULL DEFAULT 0 COMMENT '结构节点ID',
  `structure_node_type` INT NOT NULL DEFAULT 0 COMMENT '结构节点类型',
  `canonical_path` VARCHAR(255) COMMENT '规范路径',
  `item_index` INT NOT NULL DEFAULT 0 COMMENT '项目索引',
  `parent_text` VARCHAR(255) COMMENT '父节点文本',
  `char_count` INT NOT NULL DEFAULT 0 COMMENT '字符数',
  `token_count` INT NOT NULL DEFAULT 0 COMMENT '令牌数',
  `child_count` INT NOT NULL DEFAULT 0 COMMENT '子节点数',
  `start_chunk_no` INT NOT NULL DEFAULT 0 COMMENT '起始块号',
  `end_chunk_no` INT NOT NULL DEFAULT 0 COMMENT '结束块号',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  INDEX `idx_document_id` (`document_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文档父块';

CREATE TABLE `document_profile` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `document_id` BIGINT NOT NULL COMMENT '文档ID',
  `profile_version` INT NOT NULL DEFAULT 1 COMMENT '画像版本',
  `document_summary` TEXT COMMENT '文档摘要',
  `document_type` VARCHAR(128) COMMENT '文档类型',
  `core_topics` TEXT COMMENT '核心主题',
  `example_questions` TEXT COMMENT '示例问题',
  `graph_friendly` TINYINT NOT NULL DEFAULT 0 COMMENT '是否支持图表示',
  `supports_graph_outline` TINYINT NOT NULL DEFAULT 0 COMMENT '是否支持图大纲',
  `supports_item_lookup` TINYINT NOT NULL DEFAULT 0 COMMENT '是否支持项目查找',
  `supports_graph_assist` TINYINT NOT NULL DEFAULT 0 COMMENT '是否支持图辅助',
  `profile_source` VARCHAR(64) COMMENT '画像来源',
  `profile_status` INT NOT NULL DEFAULT 0 COMMENT '画像状态',
  `error_msg` TEXT COMMENT '错误信息',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_document_id` (`document_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文档画像';

CREATE TABLE `document_strategy_plan` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `document_id` BIGINT NOT NULL COMMENT '文档ID',
  `plan_version` INT NOT NULL DEFAULT 1 COMMENT '方案版本',
  `plan_source` INT NOT NULL DEFAULT 0 COMMENT '方案来源',
  `plan_status` INT NOT NULL DEFAULT 0 COMMENT '方案状态',
  `strategy_count` INT NOT NULL DEFAULT 0 COMMENT '策略数量',
  `strategy_snapshot` LONGTEXT COMMENT '策略快照',
  `recommend_reason` TEXT COMMENT '推荐理由',
  `adjust_note` TEXT COMMENT '调整备注',
  `confirm_user_id` BIGINT NOT NULL DEFAULT 0 COMMENT '确认人ID',
  `confirm_time` DATETIME COMMENT '确认时间',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  INDEX `idx_document_id` (`document_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='策略方案';

CREATE TABLE `document_strategy_step` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `document_id` BIGINT NOT NULL COMMENT '文档ID',
  `plan_id` BIGINT NOT NULL COMMENT '方案ID',
  `step_no` INT NOT NULL DEFAULT 0 COMMENT '步骤序号',
  `pipeline_type` VARCHAR(64) COMMENT '流水线类型',
  `strategy_type` INT NOT NULL DEFAULT 0 COMMENT '策略类型',
  `strategy_role` INT NOT NULL DEFAULT 0 COMMENT '策略角色',
  `source_type` INT NOT NULL DEFAULT 0 COMMENT '来源类型',
  `execute_status` INT NOT NULL DEFAULT 0 COMMENT '执行状态',
  `recommend_reason` TEXT COMMENT '推荐理由',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  INDEX `idx_document_id` (`document_id`),
  INDEX `idx_plan_id` (`plan_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='策略步骤';

CREATE TABLE `document_structure_node` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `document_id` BIGINT NOT NULL COMMENT '文档ID',
  `parse_task_id` BIGINT NOT NULL DEFAULT 0 COMMENT '解析任务ID',
  `node_no` INT NOT NULL DEFAULT 0 COMMENT '节点序号',
  `node_type` INT NOT NULL DEFAULT 0 COMMENT '节点类型',
  `parent_node_id` BIGINT NOT NULL DEFAULT 0 COMMENT '父节点ID',
  `prev_sibling_node_id` BIGINT NOT NULL DEFAULT 0 COMMENT '前一个兄弟节点ID',
  `next_sibling_node_id` BIGINT NOT NULL DEFAULT 0 COMMENT '后一个兄弟节点ID',
  `depth` INT NOT NULL DEFAULT 0 COMMENT '深度',
  `node_code` VARCHAR(128) COMMENT '节点编码',
  `title` VARCHAR(512) COMMENT '标题',
  `anchor_text` VARCHAR(255) COMMENT '锚文本',
  `canonical_path` VARCHAR(512) COMMENT '规范路径',
  `section_path` VARCHAR(512) COMMENT '章节路径',
  `content_text` TEXT COMMENT '内容文本',
  `item_index` INT NOT NULL DEFAULT 0 COMMENT '条目索引',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  INDEX `idx_document_id` (`document_id`),
  INDEX `idx_parent_node_id` (`parent_node_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文档结构节点';

CREATE TABLE `document_task` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `document_id` BIGINT NOT NULL COMMENT '文档ID',
  `plan_id` BIGINT NOT NULL DEFAULT 0 COMMENT '方案ID',
  `task_type` INT NOT NULL DEFAULT 0 COMMENT '任务类型',
  `task_status` INT NOT NULL DEFAULT 0 COMMENT '任务状态',
  `current_stage` INT NOT NULL DEFAULT 0 COMMENT '当前阶段',
  `trigger_source` INT NOT NULL DEFAULT 0 COMMENT '触发来源',
  `strategy_snapshot` LONGTEXT COMMENT '策略快照',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  `start_time` DATETIME COMMENT '开始时间',
  `finish_time` DATETIME COMMENT '完成时间',
  `cost_millis` BIGINT NOT NULL DEFAULT 0 COMMENT '耗时(毫秒)',
  `error_code` VARCHAR(64) COMMENT '错误码',
  `error_msg` TEXT COMMENT '错误信息',
  `ext_json` TEXT COMMENT '扩展JSON',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  INDEX `idx_document_id` (`document_id`),
  INDEX `idx_task_status` (`task_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文档任务';

CREATE TABLE `document_task_log` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `task_id` BIGINT NOT NULL COMMENT '任务ID',
  `document_id` BIGINT NOT NULL COMMENT '文档ID',
  `stage_type` INT NOT NULL DEFAULT 0 COMMENT '阶段类型',
  `event_type` INT NOT NULL DEFAULT 0 COMMENT '事件类型',
  `log_level` INT NOT NULL DEFAULT 0 COMMENT '日志级别',
  `operator_type` INT NOT NULL DEFAULT 0 COMMENT '操作人类型',
  `operator_id` BIGINT NOT NULL DEFAULT 0 COMMENT '操作人ID',
  `content` TEXT COMMENT '日志内容',
  `detail_json` LONGTEXT COMMENT '详情JSON',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  INDEX `idx_task_id` (`task_id`),
  INDEX `idx_document_id` (`document_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务日志';

CREATE TABLE `knowledge_document_profile` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `document_id` BIGINT NOT NULL COMMENT '文档ID',
  `profile_version` INT NOT NULL DEFAULT 1 COMMENT '画像版本',
  `document_summary` TEXT COMMENT '文档摘要',
  `document_type` VARCHAR(128) COMMENT '文档类型',
  `core_topics` TEXT COMMENT '核心主题',
  `example_questions` TEXT COMMENT '示例问题',
  `graph_friendly` TINYINT NOT NULL DEFAULT 0 COMMENT '是否支持图表示',
  `supports_graph_outline` TINYINT NOT NULL DEFAULT 0 COMMENT '是否支持图大纲',
  `supports_item_lookup` TINYINT NOT NULL DEFAULT 0 COMMENT '是否支持项目查找',
  `supports_graph_assist` TINYINT NOT NULL DEFAULT 0 COMMENT '是否支持图辅助',
  `profile_source` VARCHAR(64) COMMENT '画像来源',
  `profile_status` INT NOT NULL DEFAULT 0 COMMENT '画像状态',
  `error_msg` TEXT COMMENT '错误信息',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_document_id` (`document_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='知识文档画像';

CREATE TABLE `knowledge_route_trace` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `conversation_id` VARCHAR(64) NOT NULL COMMENT '会话ID',
  `exchange_id` BIGINT NOT NULL COMMENT '交互ID',
  `question` TEXT NOT NULL COMMENT '问题',
  `rewrite_question` TEXT COMMENT '重写问题',
  `mode` VARCHAR(32) NOT NULL COMMENT '模式',
  `top_scopes_json` TEXT COMMENT '顶级范围JSON',
  `top_topics_json` TEXT COMMENT '顶级话题JSON',
  `top_documents_json` TEXT COMMENT '顶级文档JSON',
  `selected_document_id` BIGINT NOT NULL DEFAULT 0 COMMENT '选中的文档ID',
  `hit_selected_document` TINYINT NOT NULL DEFAULT 0 COMMENT '命中选中的文档',
  `confidence` DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT '置信度',
  `route_status` INT NOT NULL DEFAULT 0 COMMENT '路由状态',
  `error_msg` TEXT COMMENT '错误信息',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  INDEX `idx_conversation_id` (`conversation_id`),
  INDEX `idx_exchange_id` (`exchange_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='知识路由追踪';

CREATE TABLE `knowledge_scope_node` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `scope_code` VARCHAR(64) NOT NULL COMMENT '范围编码',
  `scope_name` VARCHAR(128) NOT NULL COMMENT '范围名称',
  `parent_scope_code` VARCHAR(64) COMMENT '父范围编码',
  `description` TEXT COMMENT '描述',
  `aliases` TEXT COMMENT '别名',
  `examples` TEXT COMMENT '示例',
  `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序顺序',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_scope_code` (`scope_code`),
  INDEX `idx_parent_scope_code` (`parent_scope_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='知识范围节点';

CREATE TABLE `knowledge_topic_document_relation` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `topic_code` VARCHAR(64) NOT NULL COMMENT '主题编码',
  `document_id` BIGINT NOT NULL COMMENT '文档ID',
  `relation_score` DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT '关联分数',
  `relation_source` VARCHAR(64) COMMENT '关联来源',
  `reason` TEXT COMMENT '关联原因',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  INDEX `idx_topic_code` (`topic_code`),
  INDEX `idx_document_id` (`document_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='主题-文档映射关系';

CREATE TABLE `knowledge_topic_node` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `topic_code` VARCHAR(64) NOT NULL COMMENT '话题编码',
  `topic_name` VARCHAR(128) NOT NULL COMMENT '话题名称',
  `scope_code` VARCHAR(64) COMMENT '范围编码',
  `description` TEXT COMMENT '描述',
  `aliases` TEXT COMMENT '别名',
  `examples` TEXT COMMENT '示例',
  `answer_shape` VARCHAR(64) COMMENT '答案形态',
  `execution_preference` VARCHAR(64) COMMENT '执行偏好',
  `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序顺序',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_topic_code` (`topic_code`),
  INDEX `idx_scope_code` (`scope_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='知识话题节点';

CREATE TABLE `topic_document_relation` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `topic_code` VARCHAR(64) NOT NULL COMMENT '主题编码',
  `document_id` BIGINT NOT NULL COMMENT '文档ID',
  `relation_score` DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT '关联分数',
  `relation_source` VARCHAR(64) COMMENT '关联来源',
  `reason` TEXT COMMENT '关联原因',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `edit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记(1:未删除,0:已删除)',
  PRIMARY KEY (`id`),
  INDEX `idx_topic_code` (`topic_code`),
  INDEX `idx_document_id` (`document_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='主题文档关系';
