// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package document

type UploadDocumentReq struct {
	DocumentName       string // 文档名称
	OperatorId         string // 操作人ID
	KnowledgeScopeCode string // 知识范围编码
	KnowledgeScopeName string // 知识范围名称
	BusinessCategory   string // 业务分类
	DocumentTags       string // 文档标签
}

type UploadDocumentResp struct {
	DocumentId     int64  // 文档ID
	TaskId         int64  // 任务ID
	DocumentName   string // 文档名称
	ParseStatus    int    // 解析状态
	StrategyStatus int    // 策略状态
	IndexStatus    int    // 索引状态
}
