// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package document

type BuildIndexReq struct {
	DocumentId string `json:"documentId"`          // 文档ID
	PlanId     string `json:"planId"`              // 方案ID
	OperatorId string `json:"operatorId,optional"` // 操作人ID
}

type BuildIndexResp struct {
	TaskId          string `json:"taskId"`          // 任务ID
	DocumentId      string `json:"documentId"`      // 文档ID
	TaskType        int    `json:"taskType"`        // 任务类型
	TaskTypeName    string `json:"taskTypeName"`    // 任务类型名
	TaskStatus      int    `json:"taskStatus"`      // 任务状态
	TaskStatusName  string `json:"taskStatusName"`  // 任务状态名
	IndexStatus     int    `json:"indexStatus"`     // 索引状态
	IndexStatusName string `json:"indexStatusName"` // 索引状态名
}

type ConfirmStrategyReq struct {
	DocumentId  string              `json:"documentId"`          // 文档ID
	BasePlanId  string              `json:"basePlanId"`          // 基础方案ID
	OperatorId  string              `json:"operatorId,optional"` // 操作人ID
	AdjustNote  string              `json:"adjustNote,optional"` // 调整备注
	ParentSteps []*StrategyStepItem `json:"parentSteps"`         // 父块步骤
	ChildSteps  []*StrategyStepItem `json:"childSteps"`          // 子块步骤
}

type ConfirmStrategyResp struct {
	ID                 string                    `json:"planId"`             // 方案ID
	DocumentId         string                    `json:"documentId"`         // 文档ID
	PlanVersion        int                       `json:"planVersion"`        // 方案版本
	StrategyStatus     int                       `json:"strategyStatus"`     // 策略状态
	StrategyStatusName string                    `json:"strategyStatusName"` // 策略状态描述
	Normalized         bool                      `json:"normalized"`         // 是否经过标准化
	ParentPipeline     *DocumentStrategyPipeline `json:"parentPipeline"`     // 父块流水线
	ChildPipeline      *DocumentStrategyPipeline `json:"childPipeline"`      // 子块流水线
}

type DeleteDocumentReq struct {
	DocumentId string `json:"documentId"` // 文档ID
}

type DeleteDocumentResp struct {
	DocumentId   string `json:"documentId"`   // 文档ID
	DocumentName string `json:"documentName"` // 文档名称
}

type DocumentChunkItem struct {
	ID                 string `json:"chunkId"`            // 分片ID
	ParentBlockId      string `json:"parentBlockId"`      // 父块ID
	ParentBlockNo      int    `json:"parentBlockNo"`      // 父块编号
	ParentChildCount   int    `json:"parentChildCount"`   // 父块下子分片总数
	ParentStartChunkNo int    `json:"parentStartChunkNo"` // 父块起始分片号
	ParentEndChunkNo   int    `json:"parentEndChunkNo"`   // 父块结束分片号
	ChunkNo            int    `json:"chunkNo"`            // 当前分片编号
	SectionPath        string `json:"sectionPath"`        // 章节路径
	SourceType         int    `json:"sourceType"`         // 来源类型
	SourceTypeName     string `json:"sourceTypeName"`     // 来源类型名称
	CharCount          int    `json:"charCount"`          // 字符数量
	TokenCount         int    `json:"tokenCount"`         // Token数量
	VectorStatus       int    `json:"vectorStatus"`       // 向量化状态
	VectorStatusName   string `json:"vectorStatusName"`   // 向量化状态名称
	ChunkText          string `json:"chunkText"`          // 分片文本内容
}

type DocumentDetailResp struct {
	ID                   string `json:"documentId"`           // 文档ID
	DocumentName         string `json:"documentName"`         // 文档名称
	OriginalFileName     string `json:"originalFileName"`     // 原始文件名
	FileType             int    `json:"fileType"`             // 文件类型
	FileTypeName         string `json:"fileTypeName"`         // 文件类型名
	FileSize             int64  `json:"fileSize"`             // 文件大小
	CharCount            int    `json:"charCount"`            // 字符数
	TokenCount           int    `json:"tokenCount"`           // token数
	ParseStatus          int    `json:"parseStatus"`          // 解析状态
	ParseStatusName      string `json:"parseStatusName"`      // 解析状态名
	StrategyStatus       int    `json:"strategyStatus"`       // 策略状态
	StrategyStatusName   string `json:"strategyStatusName"`   // 策略状态名
	IndexStatus          int    `json:"indexStatus"`          // 索引状态
	IndexStatusName      string `json:"indexStatusName"`      // 索引状态名
	ParseErrorMsg        string `json:"parseErrorMsg"`        // 解析错误信息
	KnowledgeScopeCode   string `json:"knowledgeScopeCode"`   // 知识范围编码
	KnowledgeScopeName   string `json:"knowledgeScopeName"`   // 知识范围名称
	BusinessCategory     string `json:"businessCategory"`     // 业务分类
	DocumentTags         string `json:"documentTags"`         // 文档标签
	CurrentPlanId        string `json:"currentPlanId"`        // 当前策略ID
	LastIndexTaskId      string `json:"lastIndexTaskId"`      // 上一次索引任务ID
	LatestTaskId         string `json:"latestTaskId"`         // 最新任务ID
	LatestTaskType       int    `json:"latestTaskType"`       // 最新任务类型
	LatestTaskTypeName   string `json:"latestTaskTypeName"`   // 最新任务类型名
	LatestTaskStatus     int    `json:"latestTaskStatus"`     // 最新任务状态
	LatestTaskStatusName string `json:"latestTaskStatusName"` // 最新任务状态名
	CreateTime           string `json:"createTime"`           // 创建时间
	UpdateTime           string `json:"updateTime"`           // 更新时间
}

type DocumentParentBlockItem struct {
	ParentBlockId  string `json:"parentBlockId"`  // 父块ID
	ParentBlockNo  int    `json:"parentBlockNo"`  // 父块编号
	SectionPath    string `json:"sectionPath"`    // 章节路径
	SourceType     int    `json:"sourceType"`     // 来源类型
	SourceTypeName string `json:"sourceTypeName"` // 来源类型名称
	CharCount      int    `json:"charCount"`      // 字符总数
	TokenCount     int    `json:"tokenCount"`     // Token总数
	ChildCount     int    `json:"childCount"`     // 子分片数量
	StartChunkNo   int    `json:"startChunkNo"`   // 起始分片编号
	EndChunkNo     int    `json:"endChunkNo"`     // 结束分片编号
	ParentText     string `json:"parentText"`     // 父块文本内容
}

type DocumentProfileBatchRegenerateReq struct {
	DocumentIds []string `json:"documentIds"`         // 文档ID列表
	OperatorId  string   `json:"operatorId,optional"` // 操作人ID
}

type DocumentProfileDetailReq struct {
	DocumentId string `json:"documentId"` // 文档ID
}

type DocumentProfileRegenerateReq struct {
	DocumentId string `json:"documentId"`          // 文档ID
	OperatorId string `json:"operatorId,optional"` // 操作人ID
}

type DocumentProfileResp struct {
	DocumentId           string `json:"documentId"`           // 文档ID
	DocumentSummary      string `json:"documentSummary"`      // 文档摘要
	DocumentType         string `json:"documentType"`         // 文档类型
	CoreTopics           string `json:"coreTopics"`           // 核心主题
	ExampleQuestions     string `json:"exampleQuestions"`     // 示例问题
	GraphFriendly        int    `json:"graphFriendly"`        // 是否支持结构图
	SupportsGraphOutline int    `json:"supportsGraphOutline"` // 是否支持图纲
	SupportsItemLookup   int    `json:"supportsItemLookup"`   // 是否支持条目检索
	SupportsGraphAssist  int    `json:"supportsGraphAssist"`  // 是否支持图辅助
	ProfileSource        string `json:"profileSource"`        // 画像来源
	ProfileStatus        int    `json:"profileStatus"`        // 画像状态
	ErrorMsg             string `json:"errorMsg"`             // 错误信息
}

type DocumentStrategyPipeline struct {
	PipelineType     string                  `json:"pipelineType"`     // 流水线类型
	PipelineTypeName string                  `json:"pipelineTypeName"` // 流水线类型名称
	StrategySnapshot string                  `json:"strategySnapshot"` // 策略快照
	Steps            []*DocumentStrategyStep `json:"steps"`            // 步骤列表
}

type DocumentStrategyPlan struct {
	ID               string                    `json:"planId"`           // 方案ID
	PlanVersion      int                       `json:"planVersion"`      // 方案版本
	PlanSource       int                       `json:"planSource"`       // 方案来源
	PlanSourceName   string                    `json:"planSourceName"`   // 方案来源名称
	PlanStatus       int                       `json:"planStatus"`       // 方案状态
	PlanStatusName   string                    `json:"planStatusName"`   // 方案状态名称
	StrategySnapshot string                    `json:"strategySnapshot"` // 策略快照
	RecommendReason  string                    `json:"recommendReason"`  // 推荐理由
	ParentPipeline   *DocumentStrategyPipeline `json:"parentPipeline"`   // 父块流水线
	ChildPipeline    *DocumentStrategyPipeline `json:"childPipeline"`    // 子块流水线
}

type DocumentStrategyStep struct {
	StepNo            int    `json:"stepNo"`            // 步骤序号
	PipelineType      string `json:"pipelineType"`      // 流水线类型
	PipelineTypeName  string `json:"pipelineTypeName"`  // 流水线类型名称
	StrategyType      int    `json:"strategyType"`      // 策略类型
	StrategyTypeName  string `json:"strategyTypeName"`  // 策略类型名称
	StrategyRole      int    `json:"strategyRole"`      // 策略角色
	StrategyRoleName  string `json:"strategyRoleName"`  // 策略角色名称
	SourceType        int    `json:"sourceType"`        // 来源类型
	SourceTypeName    string `json:"sourceTypeName"`    // 来源类型名称
	ExecuteStatus     int    `json:"executeStatus"`     // 执行状态
	ExecuteStatusName string `json:"executeStatusName"` // 执行状态名称
	RecommendReason   string `json:"recommendReason"`   // 推荐理由
}

type KnowledgeDocumentOptionResp struct {
	DocumentId         string   `json:"documentId"`         // 文档ID
	DocumentName       string   `json:"documentName"`       // 文档名称
	KnowledgeScopeName string   `json:"knowledgeScopeName"` // 知识范围名称
	BusinessCategory   string   `json:"businessCategory"`   // 业务分类
	DocumentTags       []string `json:"documentTags"`       // 文档标签
}

type QueryDocumentChunkDetailReq struct {
	DocumentId string `json:"documentId"`      // 文档ID
	ChunkId    string `json:"chunkId"`         // 块ID
	TaskId     string `json:"taskId,optional"` // 任务ID
}

type QueryDocumentChunkDetailResp struct {
	DocumentId    string                   `json:"documentId"`    // 文档ID
	TaskId        string                   `json:"taskId"`        // 任务ID
	PlanId        string                   `json:"planId"`        // 方案ID
	Chunk         *DocumentChunkItem       `json:"chunk"`         // 当前分片信息
	ParentBlock   *DocumentParentBlockItem `json:"parentBlock"`   // 父级块信息
	SiblingChunks []*DocumentChunkItem     `json:"siblingChunks"` // 同级分片列表
}

type QueryDocumentChunksReq struct {
	DocumentId string `json:"documentId"`                   // 文档ID
	TaskId     string `json:"taskId,optional"`              // 任务ID
	PageNo     int    `json:"pageNo,optional,default=1"`    // 页码
	PageSize   int    `json:"pageSize,optional,default=10"` // 每页大小
}

type QueryDocumentChunksResp struct {
	DocumentId string               `json:"documentId"` // 文档ID
	TaskId     string               `json:"taskId"`     // 任务ID
	PlanId     string               `json:"planId"`     // 方案ID
	PageNo     int                  `json:"pageNo"`     // 页码
	PageSize   int                  `json:"pageSize"`   // 页大小
	Total      int64                `json:"total"`      // 总条数
	Records    []*DocumentChunkItem `json:"records"`    // 分片数据列表
}

type QueryDocumentDetailReq struct {
	DocumentId string `json:"documentId"` // 文档ID
}

type QueryDocumentPageReq struct {
	PageNo   int    `json:"pageNo,optional,default=1"`    // 页码
	PageSize int    `json:"pageSize,optional,default=10"` // 每页大小
	Keyword  string `json:"keyword,optional"`             // 关键词
}

type QueryDocumentPageResp struct {
	PageNo   int                   `json:"pageNo"`   // 页码
	PageSize int                   `json:"pageSize"` // 每页大小
	Total    int64                 `json:"total"`    // 总记录数
	Records  []*DocumentDetailResp `json:"records"`  // 文档列表
}

type QueryStrategyPlanReq struct {
	DocumentId string `json:"documentId"` // 文档ID
}

type QueryStrategyPlanResp struct {
	ID                 string                `json:"documentId"`         // 文档ID
	DocumentName       string                `json:"documentName"`       // 文档名称
	ParseStatus        int                   `json:"parseStatus"`        // 解析状态
	ParseStatusName    string                `json:"parseStatusName"`    // 解析状态名
	StrategyStatus     int                   `json:"strategyStatus"`     // 策略状态
	StrategyStatusName string                `json:"strategyStatusName"` // 策略状态名
	IndexStatus        int                   `json:"indexStatus"`        // 索引状态
	IndexStatusName    string                `json:"indexStatusName"`    // 索引状态名
	ParseErrorMsg      string                `json:"parseErrorMsg"`      // 解析错误信息
	PlanReady          bool                  `json:"planReady"`          // 方案是否就绪
	Plan               *DocumentStrategyPlan `json:"plan"`               // 策略方案
}

type QueryTaskLogsReq struct {
	TaskId   string `json:"taskId"`                       // 任务ID
	PageNo   int    `json:"pageNo,optional,default=1"`    // 页码
	PageSize int    `json:"pageSize,optional,default=10"` // 每页大小
}

type QueryTaskLogsResp struct {
	ID               string     `json:"taskId"`           // 任务ID
	DocumentId       string     `json:"documentId"`       // 文档ID
	TaskType         int        `json:"taskType"`         // 任务类型
	TaskTypeName     string     `json:"taskTypeName"`     // 任务类型名称
	TaskStatus       int        `json:"taskStatus"`       // 任务状态
	TaskStatusName   string     `json:"taskStatusName"`   // 任务状态名称
	CurrentStage     int        `json:"currentStage"`     // 当前阶段编码
	CurrentStageName string     `json:"currentStageName"` // 当前阶段名称
	StartTime        string     `json:"startTime"`        // 开始时间
	FinishTime       string     `json:"finishTime"`       // 结束时间
	CostMillis       int64      `json:"costMillis"`       // 耗时毫秒数
	ErrorCode        string     `json:"errorCode"`        // 错误码
	ErrorMsg         string     `json:"errorMsg"`         // 错误信息
	Total            int64      `json:"total"`            // 数据总量
	Logs             []*TaskLog `json:"logs"`             // 任务日志明细列表
}

type StrategyStepItem struct {
	StepNo       int `json:"stepNo"`                     // 步骤序号
	StrategyType int `json:"strategyType,options=1|2|3"` // 策略类型
}

type TaskLog struct {
	ID            string `json:"id"`            // 主键ID
	StageType     int    `json:"stageType"`     // 阶段类型编码
	StageTypeName string `json:"stageTypeName"` // 阶段类型名称
	EventType     int    `json:"eventType"`     // 事件类型编码
	EventTypeName string `json:"eventTypeName"` // 事件类型名称
	LogLevel      int    `json:"logLevel"`      // 日志等级编码
	LogLevelName  string `json:"logLevelName"`  // 日志等级名称
	Content       string `json:"content"`       // 日志简短内容
	DetailJson    string `json:"detailJson"`    // 详细JSON数据
	CreateTime    string `json:"createTime"`    // 创建时间
}

type UploadDocumentReq struct {
	DocumentName       string `json:"documentName,optional"`       // 文档名称
	OperatorId         string `json:"operatorId,optional"`         // 操作人ID
	KnowledgeScopeCode string `json:"knowledgeScopeCode,optional"` // 知识范围编码
	KnowledgeScopeName string `json:"knowledgeScopeName,optional"` // 知识范围名称
	BusinessCategory   string `json:"businessCategory,optional"`   // 业务分类
	DocumentTags       string `json:"documentTags,optional"`       // 文档标签
}

type UploadDocumentResp struct {
	DocumentId     string `json:"documentId"`     // 文档ID
	TaskId         string `json:"taskId"`         // 任务ID
	DocumentName   string `json:"documentName"`   // 文档名称
	ParseStatus    int    `json:"parseStatus"`    // 解析状态
	StrategyStatus int    `json:"strategyStatus"` // 策略状态
	IndexStatus    int    `json:"indexStatus"`    // 索引状态
}
