// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package knowledge

type KnowledgeRouteTraceItem struct {
	ID                  string  `json:"id"`                  // 主键ID
	ConversationId      string  `json:"conversationId"`      // 会话ID
	ExchangeId          string  `json:"exchangeId"`          // 轮次ID
	Question            string  `json:"question"`            // 用户提问
	RewriteQuestion     string  `json:"rewriteQuestion"`     // 改写后的问题
	Mode                string  `json:"mode"`                // 模式
	TopScopesJson       string  `json:"topScopesJson"`       // 候选范围JSON
	TopTopicsJson       string  `json:"topTopicsJson"`       // 候选主题JSON
	TopDocumentsJson    string  `json:"topDocumentsJson"`    // 候选文档JSON
	SelectedDocumentId  string  `json:"selectedDocumentId"`  // 选中的文档ID
	HitSelectedDocument int     `json:"hitSelectedDocument"` // 是否命中选中文档
	Confidence          float64 `json:"confidence"`          // 置信度
	RouteStatus         string  `json:"routeStatus"`         // 路由状态
	ErrorMsg            string  `json:"errorMsg"`            // 错误信息
	CreateTime          string  `json:"createTime"`          // 创建时间
}

type KnowledgeRouteTracePageReq struct {
	ConversationId string `json:"conversationId,optional"`      // 会话ID
	Mode           string `json:"mode,optional"`                // 模式
	RouteStatus    int    `json:"routeStatus,optional"`         // 路由状态
	PageNo         int    `json:"pageNo,optional,default=1"`    // 页码
	PageSize       int    `json:"pageSize,optional,default=10"` // 每页大小
}

type KnowledgeRouteTracePageResp struct {
	PageNo     int                        `json:"pageNo"`     // 页码
	PageSize   int                        `json:"pageSize"`   // 每页大小
	Total      int64                      `json:"total"`      // 总条数
	TotalPages int                        `json:"totalPages"` // 总页数
	Records    []*KnowledgeRouteTraceItem `json:"records"`    // 列表数据
}

type KnowledgeScopeDeleteReq struct {
	ScopeCode  string `json:"scopeCode"`           // 范围编码
	OperatorId string `json:"operatorId,optional"` // 操作人ID
}

type KnowledgeScopeResp struct {
	ID              string `json:"id"`              // 主键ID
	ScopeCode       string `json:"scopeCode"`       // 范围编码
	ScopeName       string `json:"scopeName"`       // 范围名称
	ParentScopeCode string `json:"parentScopeCode"` // 上级范围编码
	Description     string `json:"description"`     // 描述
	Aliases         string `json:"aliases"`         // 别名
	Examples        string `json:"examples"`        // 示例
	SortOrder       int    `json:"sortOrder"`       // 排序
}

type KnowledgeScopeSaveReq struct {
	ID              string `json:"id,optional"`              // 主键ID
	ScopeCode       string `json:"scopeCode"`                // 范围编码
	ScopeName       string `json:"scopeName"`                // 范围名称
	ParentScopeCode string `json:"parentScopeCode,optional"` // 上级范围编码
	Description     string `json:"description,optional"`     // 描述
	Aliases         string `json:"aliases,optional"`         // 别名
	Examples        string `json:"examples,optional"`        // 示例
	SortOrder       int    `json:"sortOrder,optional"`       // 排序
	OperatorId      string `json:"operatorId,optional"`      // 操作人ID
}

type KnowledgeTopicDeleteReq struct {
	TopicCode  string `json:"topicCode"`           // 主题编码
	OperatorId string `json:"operatorId,optional"` // 操作人ID
}

type KnowledgeTopicListReq struct {
	ScopeCode string `json:"scopeCode,optional"` // 所属范围编码
}

type KnowledgeTopicResp struct {
	ID                  string `json:"id"`                  // 主键ID
	TopicCode           string `json:"topicCode"`           // 主题编码
	TopicName           string `json:"topicName"`           // 主题名称
	ScopeCode           string `json:"scopeCode"`           // 所属范围编码
	Description         string `json:"description"`         // 描述
	Aliases             string `json:"aliases"`             // 别名
	Examples            string `json:"examples"`            // 示例
	AnswerShape         string `json:"answerShape"`         // 答复形态
	ExecutionPreference string `json:"executionPreference"` // 执行偏好
	SortOrder           int    `json:"sortOrder"`           // 排序
}

type KnowledgeTopicSaveReq struct {
	ID                  string `json:"id,optional"`                  // 主键ID
	TopicCode           string `json:"topicCode"`                    // 主题编码
	TopicName           string `json:"topicName"`                    // 主题名称
	ScopeCode           string `json:"scopeCode"`                    // 所属范围编码
	Description         string `json:"description,optional"`         // 描述
	Aliases             string `json:"aliases,optional"`             // 别名
	Examples            string `json:"examples,optional"`            // 示例
	AnswerShape         string `json:"answerShape,optional"`         // 答复形态
	ExecutionPreference string `json:"executionPreference,optional"` // 执行偏好
	SortOrder           int    `json:"sortOrder,optional"`           // 排序
	OperatorId          string `json:"operatorId,optional"`          // 操作人ID
}

type TopicDocumentRelationListReq struct {
	TopicCode string `json:"topicCode"` // 主题编码
}

type TopicDocumentRelationRemoveReq struct {
	TopicCode  string `json:"topicCode"`           // 主题编码
	DocumentId string `json:"documentId"`          // 文档ID
	OperatorId string `json:"operatorId,optional"` // 操作人ID
}

type TopicDocumentRelationResp struct {
	TopicCode          string  `json:"topicCode"`          // 主题编码
	DocumentId         string  `json:"documentId"`         // 文档ID
	DocumentName       string  `json:"documentName"`       // 文档名称
	KnowledgeScopeCode string  `json:"knowledgeScopeCode"` // 知识范围编码
	KnowledgeScopeName string  `json:"knowledgeScopeName"` // 知识范围名称
	BusinessCategory   string  `json:"businessCategory"`   // 业务分类
	DocumentTags       string  `json:"documentTags"`       // 文档标签
	RelationScore      float64 `json:"relationScore"`      // 关联分数
	RelationSource     string  `json:"relationSource"`     // 关联来源
	Reason             string  `json:"reason"`             // 理由
}

type TopicDocumentRelationSaveReq struct {
	TopicCode      string  `json:"topicCode"`               // 主题编码
	DocumentId     string  `json:"documentId"`              // 文档ID
	RelationScore  float64 `json:"relationScore,optional"`  // 关联分数
	RelationSource string  `json:"relationSource,optional"` // 关联来源
	Reason         string  `json:"reason,optional"`         // 理由
	OperatorId     string  `json:"operatorId,optional"`     // 操作人ID
}
