// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package knowledge

type KnowledgeBaseItemResp struct {
	ID                       string `json:"id"`                       // 主键ID
	BaseName                 string `json:"baseName"`                 // 知识库名称
	Description              string `json:"description"`              // 描述
	EmbeddingModel           string `json:"embeddingModel"`           // 嵌入模型
	RetrievalConfigJson      string `json:"retrievalConfigJson"`      // 检索配置JSON
	GraphRagConfigJson       string `json:"graphRagConfigJson"`       // 图谱RAG配置JSON
	RaptorConfigJson         string `json:"raptorConfigJson"`         // RAPTOR配置JSON
	MetadataFilterJson       string `json:"metadataFilterJson"`       // 元数据过滤JSON
	IsDefault                int    `json:"isDefault"`                // 是否默认
	SortOrder                int    `json:"sortOrder"`                // 排序
	DocumentCount            int    `json:"documentCount"`            // 文档数量
	RetrievableDocumentCount int    `json:"retrievableDocumentCount"` // 可检索文档数量
}

type KnowledgeBaseOptionResp struct {
	ID                       string `json:"id"`                       // 主键ID
	BaseName                 string `json:"baseName"`                 // 知识库名称
	Description              string `json:"description"`              // 描述
	IsDefault                int    `json:"isDefault"`                // 是否默认
	RetrievableDocumentCount int    `json:"retrievableDocumentCount"` // 可检索文档数量
}

type KnowledgeRouteTraceItem struct {
	ID                  string  `json:"id"`                  // 主键ID
	ConversationId      string  `json:"conversationId"`      // 会话ID
	ExchangeId          string  `json:"exchangeId"`          // 轮次ID
	Question            string  `json:"question"`            // 用户提问
	RewriteQuestion     string  `json:"rewriteQuestion"`     // 改写后的问题
	Mode                string  `json:"mode"`                // 模式
	TopScopesJson       string  `json:"topScopesJson"`       // 候选范围JSON
	TopTopicsJson       string  `json:"topTopicsJson"`       // 候选主题JSON
	TopDocumentsJson    string  `json:"topDocumentsJson"`    // 候选文档JSON
	SelectedDocumentId  string  `json:"selectedDocumentId"`  // 选中的文档ID
	HitSelectedDocument int     `json:"hitSelectedDocument"` // 是否命中选中文档
	Confidence          float64 `json:"confidence"`          // 置信度
	RouteStatus         string  `json:"routeStatus"`         // 路由状态
	ErrorMsg            string  `json:"errorMsg"`            // 错误信息
	CreateTime          string  `json:"createTime"`          // 创建时间
}

type KnowledgeRouteTracePageReq struct {
	ConversationId string `json:"conversationId,optional"`      // 会话ID
	Mode           string `json:"mode,optional"`                // 模式
	RouteStatus    int    `json:"routeStatus,optional"`         // 路由状态
	PageNo         int    `json:"pageNo,optional,default=1"`    // 页码
	PageSize       int    `json:"pageSize,optional,default=10"` // 每页大小
}

type KnowledgeRouteTracePageResp struct {
	PageNo     int                        `json:"pageNo"`     // 页码
	PageSize   int                        `json:"pageSize"`   // 每页大小
	Total      int64                      `json:"total"`      // 总条数
	TotalPages int                        `json:"totalPages"` // 总页数
	Records    []*KnowledgeRouteTraceItem `json:"records"`    // 列表数据
}

type KnowledgeScopeDeleteReq struct {
	ID              string `json:"id"`                  // 主键ID
	KnowledgeBaseId string `json:"knowledgeBaseId"`     // 知识库ID
	OperatorId      string `json:"operatorId,optional"` // 操作人ID
}

type KnowledgeScopeListReq struct {
	KnowledgeBaseId string `json:"knowledgeBaseId"` // 知识库ID
}

type KnowledgeScopeResp struct {
	ID              string `json:"id"`              // 主键ID
	KnowledgeBaseId string `json:"knowledgeBaseId"` // 知识库ID
	ScopeName       string `json:"scopeName"`       // 范围名称
	ParentScopeId   string `json:"parentScopeId"`   // 上级范围ID
	Description     string `json:"description"`     // 描述
	Aliases         string `json:"aliases"`         // 别名
	Examples        string `json:"examples"`        // 示例
	SortOrder       int    `json:"sortOrder"`       // 排序
}

type KnowledgeScopeSaveReq struct {
	ID              string `json:"id,optional"`            // 主键ID
	KnowledgeBaseId string `json:"knowledgeBaseId"`        // 知识库ID
	ScopeName       string `json:"scopeName"`              // 范围名称
	ParentScopeId   string `json:"parentScopeId,optional"` // 上级范围ID
	Description     string `json:"description,optional"`   // 描述
	Aliases         string `json:"aliases,optional"`       // 别名
	Examples        string `json:"examples,optional"`      // 示例
	SortOrder       int    `json:"sortOrder,optional"`     // 排序
	OperatorId      string `json:"operatorId,optional"`    // 操作人ID
}

type KnowledgeTopicDeleteReq struct {
	ID              string `json:"id,optional"`         // 主键ID
	KnowledgeBaseId string `json:"knowledgeBaseId"`     // 知识库ID
	OperatorId      string `json:"operatorId,optional"` // 操作人ID
}

type KnowledgeTopicListReq struct {
	KnowledgeBaseId string `json:"knowledgeBaseId"`  // 知识库ID
	ScopeId         string `json:"scopeId,optional"` // 范围ID
}

type KnowledgeTopicResp struct {
	ID                  string `json:"id"`                  // 主键ID
	KnowledgeBaseId     string `json:"knowledgeBaseId"`     // 知识库ID
	TopicName           string `json:"topicName"`           // 主题名称
	ScopeId             string `json:"scopeId"`             // 所属范围ID
	Description         string `json:"description"`         // 描述
	Aliases             string `json:"aliases"`             // 别名
	Examples            string `json:"examples"`            // 示例
	AnswerShape         string `json:"answerShape"`         // 答复形态
	ExecutionPreference string `json:"executionPreference"` // 执行偏好
	SortOrder           int    `json:"sortOrder"`           // 排序
}

type KnowledgeTopicSaveReq struct {
	ID                  string `json:"id,optional"`                  // 主键ID
	KnowledgeBaseId     string `json:"knowledgeBaseId"`              // 知识库ID
	ScopeId             string `json:"scopeId"`                      // 范围ID
	TopicName           string `json:"topicName"`                    // 主题名称
	Description         string `json:"description,optional"`         // 描述
	Aliases             string `json:"aliases,optional"`             // 别名
	Examples            string `json:"examples,optional"`            // 示例
	AnswerShape         string `json:"answerShape,optional"`         // 答复形态
	ExecutionPreference string `json:"executionPreference,optional"` // 执行偏好
	SortOrder           int    `json:"sortOrder,optional"`           // 排序
	OperatorId          string `json:"operatorId,optional"`          // 操作人ID
}

type TopicDocumentRelationListReq struct {
	TopicId         string `json:"topicId"`         // 主题ID
	KnowledgeBaseId string `json:"knowledgeBaseId"` // 知识库ID
}

type TopicDocumentRelationRemoveReq struct {
	TopicId         string `json:"topicId"`             // 主题ID
	KnowledgeBaseId string `json:"knowledgeBaseId"`     // 知识库ID
	DocumentId      string `json:"documentId"`          // 文档ID
	OperatorId      string `json:"operatorId,optional"` // 操作人ID
}

type TopicDocumentRelationResp struct {
	KnowledgeBaseId string  `json:"knowledgeBaseId"` // 知识库ID
	TopicId         string  `json:"topicId"`         // 主题ID
	TopicName       string  `json:"topicName"`       // 主题名称
	ScopeId         string  `json:"scopeId"`         // 所属范围ID
	ScopeName       string  `json:"scopeName"`       // 所属范围名称
	DocumentId      string  `json:"documentId"`      // 文档ID
	DocumentName    string  `json:"documentName"`    // 文档名称
	RelationScore   float64 `json:"relationScore"`   // 关联分数
	RelationSource  string  `json:"relationSource"`  // 关联来源
	Reason          string  `json:"reason"`          // 理由
}

type TopicDocumentRelationSaveReq struct {
	TopicId         string  `json:"topicId"`                 // 主题ID
	KnowledgeBaseId string  `json:"knowledgeBaseId"`         // 知识库ID
	DocumentId      string  `json:"documentId"`              // 文档ID
	RelationScore   float64 `json:"relationScore,optional"`  // 关联分数
	RelationSource  string  `json:"relationSource,optional"` // 关联来源
	Reason          string  `json:"reason,optional"`         // 理由
	OperatorId      string  `json:"operatorId,optional"`     // 操作人ID
}
