// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/swiftbit/know-agent/common"
	"github.com/swiftbit/know-agent/internal/config"
	"github.com/swiftbit/know-agent/internal/domain/document/adapter"
	"github.com/swiftbit/know-agent/internal/domain/document/logic"
	"github.com/swiftbit/know-agent/internal/infrastructure/persistence"
	"github.com/swiftbit/know-agent/internal/infrastructure/port/mq"
	"github.com/swiftbit/know-agent/internal/infrastructure/port/storage"
	"github.com/swiftbit/know-agent/internal/server"
	"github.com/swiftbit/know-agent/internal/svc"
	"github.com/swiftbit/know-agent/internal/trigger/handler"
)

// Injectors from wire.go:

//go:generate wire gen ./wire.go
func WireApp(c config.Config) *server.Server {
	validate := common.NewValidator()
	serviceContext := svc.NewServiceContext(c, validate)
	minioStorage := storage.NewMinioStorage(serviceContext)
	mockMessageProducer := mq.NewMockMessageProducer()
	documentPort := adapter.NewDocumentPort(minioStorage, mockMessageProducer)
	commonConfig := provideCommonConfig(c)
	db := common.NewDb(commonConfig)
	client := common.NewRedisClient(commonConfig)
	cache := common.NewRedisCache(commonConfig)
	documentRepositoryImpl := persistence.NewDocumentRepository(db, client, cache)
	documentLifecycleLogicImpl := logic.NewDocumentLifecycleLogicImpl(serviceContext, documentPort, documentRepositoryImpl)
	documentService := handler.NewDocumentService(documentLifecycleLogicImpl)
	restServer := server.NewHTTPServer(c, serviceContext, documentService)
	serverServer := server.NewServer(restServer)
	return serverServer
}

// wire.go:

func provideCommonConfig(c config.Config) common.Config {
	return c
}
