// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/swiftbit/know-agent/internal/config"
	"github.com/swiftbit/know-agent/internal/domain"
	"github.com/swiftbit/know-agent/internal/domain/chat/logic/conversation"
	"github.com/swiftbit/know-agent/internal/domain/chat/logic/conversation/executor"
	"github.com/swiftbit/know-agent/internal/domain/chat/logic/graph"
	"github.com/swiftbit/know-agent/internal/domain/chat/logic/intent"
	"github.com/swiftbit/know-agent/internal/domain/chat/logic/memory"
	"github.com/swiftbit/know-agent/internal/domain/chat/logic/memory/strategy"
	"github.com/swiftbit/know-agent/internal/domain/chat/logic/orchestrator"
	"github.com/swiftbit/know-agent/internal/domain/chat/logic/prompt"
	"github.com/swiftbit/know-agent/internal/domain/chat/logic/rag"
	"github.com/swiftbit/know-agent/internal/domain/chat/logic/rag/channel"
	"github.com/swiftbit/know-agent/internal/domain/chat/logic/recommend"
	"github.com/swiftbit/know-agent/internal/domain/chat/logic/rewrite"
	"github.com/swiftbit/know-agent/internal/domain/document/adapter"
	"github.com/swiftbit/know-agent/internal/domain/document/logic"
	"github.com/swiftbit/know-agent/internal/domain/document/logic/process"
	"github.com/swiftbit/know-agent/internal/domain/document/logic/process/transform"
	logic2 "github.com/swiftbit/know-agent/internal/domain/knowledge/logic"
	"github.com/swiftbit/know-agent/internal/domain/knowledge/logic/route"
	"github.com/swiftbit/know-agent/internal/infrastructure"
	"github.com/swiftbit/know-agent/internal/infrastructure/persistence"
	"github.com/swiftbit/know-agent/internal/infrastructure/port/check"
	"github.com/swiftbit/know-agent/internal/infrastructure/port/keyword"
	"github.com/swiftbit/know-agent/internal/infrastructure/port/llm"
	"github.com/swiftbit/know-agent/internal/infrastructure/port/lock"
	"github.com/swiftbit/know-agent/internal/infrastructure/port/mq"
	"github.com/swiftbit/know-agent/internal/infrastructure/port/reranker"
	"github.com/swiftbit/know-agent/internal/infrastructure/port/storage"
	"github.com/swiftbit/know-agent/internal/infrastructure/port/vector"
	"github.com/swiftbit/know-agent/internal/server"
	"github.com/swiftbit/know-agent/internal/svc"
	"github.com/swiftbit/know-agent/internal/trigger/consumer"
	"github.com/swiftbit/know-agent/internal/trigger/handler"
)

// Injectors from wire.go:

//go:generate wire gen ./wire.go
func WireApp(c *config.Config) *server.Server {
	serviceContext := svc.NewServiceContext(c)
	minioStorage := storage.NewMinioStorage(serviceContext)
	rocketMQMessageProducer := mq.NewRocketMQMessageProducer(serviceContext)
	milvusVector := vector.NewMilvusVector(serviceContext)
	milvusKeyword := keyword.NewMilvusKeyword(serviceContext)
	documentPort := adapter.NewDocumentPort(minioStorage, rocketMQMessageProducer, milvusVector, milvusKeyword)
	documentRepositoryImpl := persistence.NewDocumentRepository(serviceContext, minioStorage, milvusVector)
	chatModelImpl := llm.NewChatModelImpl(serviceContext)
	templateRenderer := prompt.NewPromptTemplateLogicImpl()
	structureNodeManageImpl := process.NewStructureNodeManager(documentRepositoryImpl)
	chunkCoordinateImpl := process.NewChunkCoordinateImpl(serviceContext, chatModelImpl, templateRenderer, structureNodeManageImpl)
	lifecycleLogicImpl := logic.NewLifecycleLogicImpl(serviceContext, documentPort, documentRepositoryImpl, chunkCoordinateImpl)
	profileGenerateImpl := process.NewProfileGenerateImpl(documentRepositoryImpl)
	profileLogicImpl := logic.NewProfileLogicImpl(documentRepositoryImpl, documentPort, profileGenerateImpl)
	documentService := handler.NewDocumentService(lifecycleLogicImpl, profileLogicImpl)
	chatRepositoryImpl := persistence.NewChatRepository(serviceContext)
	dashScope := reranker.NewDashScope(serviceContext)
	vectorRetrievalChannel := channel.NewVectorRetrievalChannel(serviceContext, milvusVector)
	keywordRetrievalChannel := channel.NewKeywordRetrievalChannel(serviceContext, milvusKeyword)
	v := domain.NewRetrievalChannels(vectorRetrievalChannel, keywordRetrievalChannel)
	retrievalImpl := rag.NewRetrievalImpl(serviceContext, chatRepositoryImpl, dashScope, v, lifecycleLogicImpl)
	promptAssembler := rag.NewPromptAssembler(serviceContext, templateRenderer)
	ragChatExecutor := executor.NewRagChatExecutor(retrievalImpl, promptAssembler, chatModelImpl)
	defaultStructureGraphQuerier := graph.NewDefaultStructureGraphQuerier(serviceContext)
	defaultAnswerRender := graph.NewDefaultAnswerRender()
	graphOnlyExecutor := executor.NewGraphOnlyExecutor(defaultStructureGraphQuerier, defaultAnswerRender)
	graphThenEvidenceExecutor := executor.NewGraphThenEvidenceExecutor(defaultStructureGraphQuerier, defaultAnswerRender)
	clarificationExecutor := executor.NewClarificationExecutor()
	executorRegistry := domain.NewExecutorRegistry(ragChatExecutor, graphOnlyExecutor, graphThenEvidenceExecutor, clarificationExecutor)
	summaryCompressionStrategy := strategy.NewSummaryCompressionStrategy(serviceContext, chatRepositoryImpl, chatModelImpl, templateRenderer)
	sessionMemoryLogicImpl := memory.NewSessionMemoryLogicImpl(summaryCompressionStrategy)
	queryRewriter := rewrite.NewQueryRewriter(serviceContext, chatModelImpl, templateRenderer)
	defaultNavigationIndexService := intent.NewDefaultNavigationIndexService()
	documentQuestionRouterImpl := intent.NewDocumentQuestionRouterImpl(chatModelImpl, defaultStructureGraphQuerier, defaultNavigationIndexService, templateRenderer)
	knowledgeRepositoryImpl := persistence.NewKnowledgeRepository(serviceContext)
	v2 := domain.ProvideKnowledgeOptions()
	knowledgeRouteImpl := route.NewKnowledgeRouteImpl(knowledgeRepositoryImpl, lifecycleLogicImpl, profileLogicImpl, v2...)
	preparationOrchestratorImpl := orchestrator.NewChatPreparationOrchestratorImpl(serviceContext, chatRepositoryImpl, sessionMemoryLogicImpl, queryRewriter, documentQuestionRouterImpl, knowledgeRouteImpl, lifecycleLogicImpl)
	questionRecommender := recommend.NewQuestionRecommender(serviceContext, templateRenderer, chatModelImpl)
	redisMutexLock := lock.NewRedisMutexLock(serviceContext)
	memoryCheckPointStore := check.NewMemoryCheckPointStore()
	logicImpl := conversation.NewChatLogic(serviceContext, chatRepositoryImpl, executorRegistry, lifecycleLogicImpl, preparationOrchestratorImpl, templateRenderer, questionRecommender, sessionMemoryLogicImpl, redisMutexLock, memoryCheckPointStore)
	chatService := handler.NewChatService(logicImpl)
	knowledgeLogicImpl := logic2.NewKnowledgeLogicImpl(knowledgeRepositoryImpl, lifecycleLogicImpl)
	knowledgeService := handler.NewKnowledgeService(knowledgeLogicImpl)
	restServer := server.NewHTTPServer(serviceContext, documentService, chatService, knowledgeService)
	registry := infrastructure.NewParserRegistry()
	signalExtractor := transform.NewSignalExtractor()
	ambiguityResolver := transform.NewAmbiguityResolver(serviceContext, chatModelImpl, templateRenderer)
	hierarchyResolver := transform.NewHierarchyResolver()
	treeValidator := transform.NewTreeValidator()
	textPreprocessImpl := process.NewTextPreprocessImpl(registry, signalExtractor, ambiguityResolver, hierarchyResolver, treeValidator)
	asyncProcessImpl := process.NewAsyncProcessImpl(documentRepositoryImpl, documentPort, chunkCoordinateImpl, structureNodeManageImpl, textPreprocessImpl, profileGenerateImpl)
	parseDocumentConsumer := consumer.NewParseDocumentConsumer(serviceContext, asyncProcessImpl)
	buildIndexConsumer := consumer.NewBuildIndexConsumer(serviceContext, asyncProcessImpl)
	serverServer := server.NewServer(restServer, parseDocumentConsumer, buildIndexConsumer, rocketMQMessageProducer)
	return serverServer
}
