// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package chat

type ChannelExecutionResp struct {
	ID                 int64   `json:"id"`                   // 主键
	ConversationId     string  `json:"conversationId"`       // 对话ID
	ExchangeId         int64   `json:"exchange_id"`          // 交换ID
	TraceId            string  `json:"trace_id"`             // 跟踪ID
	SubQuestionIndex   int     `json:"sub_question_index"`   // 子问题索引
	SubQuestion        string  `json:"sub_question"`         // 子问题
	ChannelType        string  `json:"channel_type"`         // 渠道类型
	ExecutionState     int     `json:"execution_state"`      // 执行状态
	StartTime          string  `json:"start_time"`           // 开始时间
	EndTime            string  `json:"end_time"`             // 结束时间
	DurationMs         int64   `json:"duration_ms"`          // 执行时长（毫秒）
	RecalledCount      int     `json:"recalled_count"`       // 召回数量
	AcceptedCount      int     `json:"accepted_count"`       // 接受数量
	FinalSelectedCount int     `json:"final_selected_count"` // 最终选中数量
	AvgScore           float64 `json:"avg_score"`            // 平均分数
	MaxScore           float64 `json:"max_score"`            // 最大分数
	MinScore           float64 `json:"min_score"`            // 最小分数
	ErrorMessage       string  `json:"error_message"`        // 错误信息
	CreateTime         string  `json:"create_time"`          // 创建时间
}

type ChatReq struct {
	Question           string `json:"question"`                                          // 问题内容
	ConversationId     string `json:"conversationId,optional"`                           // 会话ID
	ChatMode           string `json:"chatMode,options=document|open_chat|auto_document"` // 聊天模式
	SelectedDocumentId int64  `json:"selectedDocumentId,optional"`                       // 选中的文档ID
}

type ConversationExchangeDetailQueryReq struct {
	ConversationId string `json:"conversationId"` // 会话ID
	ExchangeId     int64  `json:"exchangeId"`     // 对话ID
}

type ConversationExchangeDetailResp struct {
	ConversationId string                        `json:"conversationId"` // 会话ID
	Exchange       *ConversationExchangeResp     `json:"exchange"`       // 对话交换响应
	StageTraces    []*ConversationTraceStageResp `json:"stageTraces"`    // 阶段追踪列表
}

type ConversationExchangeResp struct {
	ID                  int64                  `json:"exchangeId"`          // 对话交换ID
	Question            string                 `json:"question"`            // 问题内容
	Answer              string                 `json:"answer"`              // 回答内容
	ThinkingSteps       []string               `json:"thinkingSteps"`       // 思维步骤列表
	References          []*SearchReferenceResp `json:"references"`          // 检索引用列表
	Recommendations     []string               `json:"recommendations"`     // 推荐问题列表
	UsedTools           []string               `json:"usedTools"`           // 使用工具列表
	DebugTraceJson      string                 `json:"debugTrace"`          // 调试轨迹
	TurnStatus          int                    `json:"status"`              // 对话状态
	ErrorMessage        string                 `json:"errorMessage"`        // 错误信息
	FirstResponseTimeMs int64                  `json:"firstResponseTimeMs"` // 首次响应时间毫秒
	TotalResponseTimeMs int64                  `json:"totalResponseTimeMs"` // 总响应时间毫秒
	CreateTime          string                 `json:"createTime"`          // 创建时间
	UpdateTime          string                 `json:"updateTime,optional"` // 最后更新时间
}

type ConversationIdentityReq struct {
	ConversationId string `json:"conversationId"` // 会话ID
}

type ConversationMemorySummaryResp struct {
	ConversationId       string               `json:"conversationId"`       // 会话ID
	IsCompressed         bool                 `json:"IsCompressed"`         // 是否执行过记忆压缩
	CoveredExchangeId    int64                `json:"coveredExchangeId"`    // 压缩截止交互ID
	CoveredExchangeCount int                  `json:"coveredExchangeCount"` // 压缩覆盖交互轮次
	CompressionCount     int                  `json:"compressionCount"`     // 累计压缩次数
	SummaryVersion       int                  `json:"summaryVersion"`       // 摘要版本号
	SummaryText          string               `json:"summaryText"`          // 纯文本摘要
	SummaryPayload       *ConversationSummary `json:"summaryPayload"`       // 结构化摘要载荷
	LastSourceUpdateTime string               `json:"lastSourceUpdateTime"` // 原始对话最后更新时间
	UpdatedAt            int64                `json:"updatedAt"`            // 摘要更新时间戳
}

type ConversationResetResp struct {
	ConversationId         string `json:"conversationId"`         // 会话ID
	Stopped                bool   `json:"stopped"`                // 是否停止
	RemovedDialogueCount   int    `json:"removedDialogueCount"`   // 移除对话数
	RemovedExchangeCount   int    `json:"removedExchangeCount"`   // 移除交换数
	RemovedCheckpointCount int    `json:"removedCheckpointCount"` // 移除检查点数
	Message                string `json:"message"`                // 消息
}

type ConversationSessionListReq struct {
	PageNo     int    `json:"pageNo,optional,default=1"`    // 页码
	PageSize   int    `json:"pageSize,optional,default=10"` // 每页大小
	Keyword    string `json:"keyword,optional"`             // 关键词
	ChatMode   string `json:"chatMode,optional"`            // 聊天模式过滤
	TurnStatus string `json:"turnStatus,optional"`          // 对话状态过滤
}

type ConversationSessionListResp struct {
	PageNo     int                        `json:"pageNo"`     // 页码
	PageSize   int                        `json:"pageSize"`   // 每页大小
	TotalSize  int64                      `json:"totalSize"`  // 总记录数
	TotalPages int64                      `json:"totalPages"` // 总页数
	Records    []*ConversationSessionResp `json:"records"`    // 会话列表
}

type ConversationSessionResp struct {
	ConversationId         string                         `json:"conversationId"`         // 会话唯一标识
	Running                bool                           `json:"running"`                // 是否正在会话中
	CheckpointCount        int                            `json:"checkpointCount"`        // 检查点数量
	MessageCount           int                            `json:"messageCount"`           // 消息总数
	LatestUserMessage      string                         `json:"latestUserMessage"`      // 最新用户提问
	LatestAssistantMessage string                         `json:"latestAssistantMessage"` // 模型最新回复
	LatestExchangeId       int64                          `json:"latestExchangeId"`       // 最新一轮交互ID
	LatestTurnStatus       string                         `json:"latestTurnStatus"`       // 本轮交互状态
	LatestTurnErrorMessage string                         `json:"latestTurnErrorMessage"` // 本轮交互错误信息
	ChatMode               string                         `json:"chatMode"`               // 对话查询模式
	SelectedDocumentId     int64                          `json:"selectedDocumentId"`     // 选中文档ID
	SelectedDocumentName   string                         `json:"selectedDocumentName"`   // 选中文档名称
	CreatedTime            string                         `json:"createdTime"`            // 创建时间
	UpdatedTime            string                         `json:"updatedTime"`            // 更新时间
	Exchanges              []*ConversationExchangeResp    `json:"exchanges"`              // 交互轮次列表
	MemorySummary          *ConversationMemorySummaryResp `json:"memorySummary"`          // 会话记忆摘要
}

type ConversationStopResp struct {
	ConversationId string `json:"conversationId"` // 会话ID
	Stopped        bool   `json:"stopped"`        // 是否停止
	Message        string `json:"message"`        // 消息
}

type ConversationSummary struct {
	Summary          string   `json:"summary"`          // 摘要文本
	ConversationGoal string   `json:"conversationGoal"` // 对话目标
	StableFacts      []string `json:"stableFacts"`      // 稳定事实列表
	UserPreferences  []string `json:"userPreferences"`  // 用户偏好列表
	ResolvedPoints   []string `json:"resolvedPoints"`   // 已解决问题列表
	PendingQuestions []string `json:"pendingQuestions"` // 待解决问题列表
	RetrievalHints   []string `json:"retrievalHints"`   // 检索提示列表
}

type ConversationTraceStageResp struct {
	ID            int64  `json:"id"`            // 阶段ID
	TraceId       string `json:"traceId"`       // 追踪ID
	StageCode     string `json:"stageCode"`     // 阶段代码
	StageName     string `json:"stageName"`     // 阶段名称
	StageOrder    int    `json:"stageOrder"`    // 阶段顺序
	StageLevel    int    `json:"stageLevel"`    // 阶段层级
	ParentStageId int64  `json:"parentStageId"` // 父阶段ID
	ExecutionMode string `json:"executionMode"` // 执行模式
	StageState    string `json:"stageState"`    // 阶段状态
	StartTime     string `json:"startTime"`     // 开始时间
	EndTime       string `json:"endTime"`       // 结束时间
	DurationMs    int64  `json:"durationMs"`    // 持续时间毫秒
	SummaryText   string `json:"summaryText"`   // 摘要文本
	ErrorMessage  string `json:"errorMessage"`  // 错误信息
	SnapshotJson  string `json:"snapshot"`      // 快照数据
}

type KnowledgeDocumentOptionResp struct {
	DocumentId         int64    `json:"documentId"`         // 文档ID
	DocumentName       string   `json:"documentName"`       // 文档名称
	KnowledgeScopeName string   `json:"knowledgeScopeName"` // 知识范围名称
	BusinessCategory   string   `json:"businessCategory"`   // 业务分类
	DocumentTags       []string `json:"documentTags"`       // 文档标签
}

type RetrievalObserveReq struct {
	ConversationId string `json:"conversationId"` // 会话ID
	ExchangeId     int64  `json:"exchangeId"`     // 对话ID
}

type RetrievalResultResp struct {
	ID               int64   `json:"id"`               // 主键ID
	ConversationId   string  `json:"conversationId"`   // 对话ID
	ExchangeId       int64   `json:"exchangeId"`       // 交互ID
	TraceId          string  `json:"traceId"`          // 跟踪ID
	SubQuestionIndex int     `json:"subQuestionIndex"` // 子问题索引
	SubQuestion      string  `json:"subQuestion"`      // 子问题
	ChannelType      string  `json:"channelType"`      // 渠道类型
	ChannelRank      int     `json:"channelRank"`      // 渠道排名
	RrfRank          int     `json:"rrfRank"`          // RRF排名
	FinalRank        int     `json:"finalRank"`        // 最终排名
	OriginalScore    float64 `json:"originalScore"`    // 原始分数
	RrfScore         float64 `json:"rrfScore"`         // RRF分数
	RerankScore      float64 `json:"rerankScore"`      // 重排分数
	GatePassed       int     `json:"gatePassed"`       // 是否通过门控
	IsElevated       int     `json:"isElevated"`       // 是否升级
	IsSelected       int     `json:"isSelected"`       // 是否选中
	SelectionReason  string  `json:"selectionReason"`  // 选中原因
	ChunkId          int64   `json:"chunkId"`          // 分块ID
	ChunkNo          int     `json:"chunkNo"`          // 分块序号
	ParentBlockId    int64   `json:"parentBlockId"`    // 父块ID
	ParentBlockNo    int     `json:"parentBlockNo"`    // 父块序号
	SectionPath      string  `json:"sectionPath"`      // 章节路径
	ChunkTextPreview string  `json:"chunkTextPreview"` // 分块文本预览
	ChunkCharCount   int     `json:"chunkCharCount"`   // 分块字符数
	CreateTime       string  `json:"createTime"`       // 创建时间
}

type SearchReferenceResp struct {
	ReferenceId        string  `json:"referenceId"`        // 引用ID
	SourceType         string  `json:"sourceType"`         // 来源类型
	Title              string  `json:"title"`              // 标题
	Url                string  `json:"url"`                // URL
	Snippet            string  `json:"snippet"`            // 片段
	DocumentId         int64   `json:"documentId"`         // 文档ID
	DocumentName       string  `json:"documentName"`       // 文档名称
	ChunkId            int64   `json:"chunkId"`            // 块ID
	ParentBlockId      int64   `json:"parentBlockId"`      // 父块ID
	ParentBlockNo      int     `json:"parentBlockNo"`      // 父块序号
	ChunkNo            int     `json:"chunkNo"`            // 块序号
	SectionPath        string  `json:"sectionPath"`        // 章节路径
	StructureNodeId    int64   `json:"structureNodeId"`    // 结构节点ID
	StructureNodeType  int     `json:"structureNodeType"`  // 结构节点类型
	CanonicalPath      string  `json:"canonicalPath"`      // 规范路径
	ItemIndex          int     `json:"itemIndex"`          // 项索引
	Score              float64 `json:"score"`              // 相似度分数
	SubQuestionIndex   int     `json:"subQuestionIndex"`   // 子问题索引
	SubQuestion        string  `json:"subQuestion"`        // 子问题
	Channel            string  `json:"channel"`            // 渠道
	ToolName           string  `json:"toolName"`           // 工具名称
	KnowledgeScopeCode string  `json:"knowledgeScopeCode"` // 知识范围代码
	KnowledgeScopeName string  `json:"knowledgeScopeName"` // 知识范围名称
}

type StageBenchmarkResp struct {
	StageName string `json:"stageName"` // 阶段名称
	Benchmark string `json:"benchmark"` // 基准值
}
