// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package chat

type ChannelExecutionResp struct {
	ExecutionId  string `json:"executionId"`  // 执行ID
	ChannelId    string `json:"channelId"`    // 渠道ID
	ChannelName  string `json:"channelName"`  // 渠道名称
	Status       int    `json:"status"`       // 执行状态
	ErrorMessage string `json:"errorMessage"` // 错误信息
	CreateTime   string `json:"createTime"`   // 创建时间
}

type ChatReq struct {
	Question           string `json:"question"`                    // 问题内容
	ConversationId     int64  `json:"conversationId,optional"`     // 会话ID
	ChatMode           string `json:"chatMode"`                    // 聊天模式
	SelectedDocumentId int64  `json:"selectedDocumentId,optional"` // 选中的文档ID
}

type ConversationExchangeDetailQueryReq struct {
	ConversationId string `json:"conversationId"` // 会话ID
	ExchangeId     string `json:"exchangeId"`     // 对话ID
}

type ConversationExchangeDetailResp struct {
	ExchangeId     string `json:"exchangeId"`     // 对话ID
	ConversationId string `json:"conversationId"` // 会话ID
	UserMessage    string `json:"userMessage"`    // 用户消息
	AgentMessage   string `json:"agentMessage"`   // 代理消息
	CreateTime     string `json:"createTime"`     // 创建时间
}

type ConversationIdentityReq struct {
	ConversationId string `json:"conversationId"` // 会话ID
}

type ConversationMemorySummaryResp struct {
	ConversationId string `json:"conversationId"` // 会话ID
	Summary        string `json:"summary"`        // 摘要内容
}

type ConversationResetResp struct {
	Success bool `json:"success"` // 是否成功
}

type ConversationSessionListReq struct {
	PageNo   int    `json:"pageNo,optional,default=1"`    // 页码
	PageSize int    `json:"pageSize,optional,default=10"` // 每页大小
	Keyword  string `json:"keyword,optional"`             // 关键词
}

type ConversationSessionListResp struct {
	PageNo   int                        `json:"pageNo"`   // 页码
	PageSize int                        `json:"pageSize"` // 每页大小
	Total    int64                      `json:"total"`    // 总记录数
	Records  []*ConversationSessionResp `json:"records"`  // 会话列表
}

type ConversationSessionResp struct {
	ConversationId string `json:"conversationId"` // 会话ID
	Title          string `json:"title"`          // 会话标题
	LatestMessage  string `json:"latestMessage"`  // 最新消息
	CreateTime     string `json:"createTime"`     // 创建时间
	UpdateTime     string `json:"updateTime"`     // 更新时间
}

type ConversationStopResp struct {
	Success bool `json:"success"` // 是否成功
}

type KnowledgeDocumentOptionResp struct {
	DocumentId   int64  `json:"documentId"`   // 文档ID
	DocumentName string `json:"documentName"` // 文档名称
}

type RetrievalObserveReq struct {
	ConversationId string `json:"conversationId"` // 会话ID
	ExchangeId     string `json:"exchangeId"`     // 对话ID
}

type RetrievalResultResp struct {
	RetrievalId  int64  `json:"retrievalId"`  // 检索ID
	DocumentId   int64  `json:"documentId"`   // 文档ID
	DocumentName string `json:"documentName"` // 文档名称
	Content      string `json:"content"`      // 检索内容
	Score        string `json:"score"`        // 相似度分数
}

type StageBenchmarkResp struct {
	StageName string `json:"stageName"` // 阶段名称
	Benchmark string `json:"benchmark"` // 基准值
}
