// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package chat

type ChannelExecutionResp struct {
	ExecutionId  string `json:"executionId"`  // 执行ID
	ChannelId    string `json:"channelId"`    // 渠道ID
	ChannelName  string `json:"channelName"`  // 渠道名称
	Status       int    `json:"status"`       // 执行状态
	ErrorMessage string `json:"errorMessage"` // 错误信息
	CreateTime   string `json:"createTime"`   // 创建时间
}

type ChatDebugTraceResp struct {
	ExecutionMode                 string                          `json:"executionMode"`                 // 执行模式
	ChatMode                      int                             `json:"chatMode"`                      // 聊天模式
	OriginalQuestion              string                          `json:"originalQuestion"`              // 原始问题
	RewriteQuestion               string                          `json:"rewriteQuestion"`               // 重写问题
	RewriteSubQuestions           []string                        `json:"rewriteSubQuestions"`           // 重写子问题列表
	RetrievalQuestion             string                          `json:"rewrittenQuestion"`             // 检索问题
	AgentQuestion                 string                          `json:"agentQuestion"`                 // Agent问题
	NavigationDecision            *DocumentNavigationDecisionResp `json:"navigationDecision"`            // 文档导航决策
	HistorySummary                string                          `json:"historySummary"`                // 历史摘要
	LongTermSummary               string                          `json:"longTermSummary"`               // 长期摘要
	RecentHistoryTranscript       string                          `json:"recentHistoryTranscript"`       // 近期历史转录
	AnswerRecentTranscript        string                          `json:"answerRecentTranscript"`        // 回答近期转录
	AnswerHistoryContext          string                          `json:"answerHistoryContext"`          // 回答历史上下文
	AnswerHistoryFollowUpQuestion bool                            `json:"answerHistoryFollowUpQuestion"` // 回答历史追问
	HistoryCompressionApplied     bool                            `json:"historyCompressionApplied"`     // 历史压缩已应用
	HistoryCoveredExchangeId      int64                           `json:"historyCoveredExchangeId"`      // 历史覆盖交换ID
	HistoryCoveredExchangeCount   int                             `json:"historyCoveredExchangeCount"`   // 历史覆盖交换数量
	HistoryCompressionCount       int                             `json:"historyCompressionCount"`       // 历史压缩次数
	CurrentDateText               string                          `json:"currentDateText"`               // 当前日期文本
	RequiresFreshSearch           bool                            `json:"requiresFreshSearch"`           // 需要新鲜搜索
	RequiresCurrentDateAnchoring  bool                            `json:"requiresCurrentDateAnchoring"`  // 需要当前日期锚定
	SubQuestions                  []string                        `json:"subQuestions"`                  // 检索子问题列表
	SelectedDocumentId            int64                           `json:"selectedDocumentId"`            // 选中的文档ID
	SelectedTaskId                int64                           `json:"selectedTaskId"`                // 选中的任务ID
	RetrievalNotes                []string                        `json:"retrievalNotes"`                // 检索备注列表
	UsedChannels                  []string                        `json:"usedChannels"`                  // 使用的渠道列表
	ToolTraces                    []*ChatToolTraceResp            `json:"toolTraces"`                    // 工具调用轨迹列表
	ModelUsageTraces              []*ChatModelUsageTraceResp      `json:"modelUsageTraces"`              // 模型使用轨迹列表
	LimitStats                    *ChatLimitStatsResp             `json:"limitStats"`                    // 限制统计
	RagSystemPrompt               string                          `json:"ragSystemPrompt"`               // RAG系统提示词
	RagUserPrompt                 string                          `json:"ragUserPrompt"`                 // RAG用户提示词
	NoEvidenceReply               string                          `json:"noEvidenceReply"`               // 无证据回复
}

type ChatLimitStatsResp struct {
	ModelCallsUsed        int    `json:"modelCallsUsed"`        // 已使用的模型调用次数
	ModelCallsRunLimit    int    `json:"modelCallsRunLimit"`    // 运行限制的模型调用次数
	ModelCallsThreadLimit int    `json:"modelCallsThreadLimit"` // 线程限制的模型调用次数
	ToolCallsUsed         int    `json:"toolCallsUsed"`         // 已使用的工具调用次数
	ToolCallsRunLimit     int    `json:"toolCallsRunLimit"`     // 运行限制的工具调用次数
	ToolCallsThreadLimit  int    `json:"toolCallsThreadLimit"`  // 线程限制的工具调用次数
	LimitTriggered        bool   `json:"limitTriggered"`        // 是否触发限制
	LimitReason           string `json:"limitReason"`           // 限制原因
}

type ChatModelUsageTraceResp struct {
	StageName        string  `json:"stageName"`        // 阶段名称
	Provider         string  `json:"provider"`         // 提供商
	Model            string  `json:"model"`            // 模型名称
	PromptTokens     int     `json:"promptTokens"`     // 提示词token数
	CompletionTokens int     `json:"completionTokens"` // 完成token数
	TotalTokens      int     `json:"totalTokens"`      // 总token数
	EstimatedCost    float64 `json:"estimatedCost"`    // 预估成本
	DurationMs       int64   `json:"durationMs"`       // 持续时间毫秒
	Status           string  `json:"status"`           // 状态
}

type ChatReq struct {
	Question           string `json:"question"`                                          // 问题内容
	ConversationId     string `json:"conversationId,optional"`                           // 会话ID
	ChatMode           string `json:"chatMode,options=document|open_chat|auto_document"` // 聊天模式
	SelectedDocumentId int64  `json:"selectedDocumentId,optional"`                       // 选中的文档ID
}

type ChatToolTraceResp struct {
	ToolName       string `json:"toolName"`       // 工具名称
	Status         string `json:"status"`         // 状态
	InputSummary   string `json:"inputSummary"`   // 输入摘要
	EffectiveInput string `json:"effectiveInput"` // 有效输入
	OutputSummary  string `json:"outputSummary"`  // 输出摘要
	ErrorMessage   string `json:"errorMessage"`   // 错误信息
	ReferenceCount int    `json:"referenceCount"` // 引用数量
	Topic          string `json:"topic"`          // 主题
	DurationMs     int64  `json:"durationMs"`     // 持续时间毫秒
}

type ConversationExchangeDetailQueryReq struct {
	ConversationId string `json:"conversationId"` // 会话ID
	ExchangeId     string `json:"exchangeId"`     // 对话ID
}

type ConversationExchangeDetailResp struct {
	ConversationId string                        `json:"conversationId"` // 会话ID
	Exchange       *ConversationExchangeResp     `json:"exchange"`       // 对话交换响应
	StageTraces    []*ConversationTraceStageResp `json:"stageTraces"`    // 阶段追踪列表
}

type ConversationExchangeResp struct {
	ExchangeId          int64                  `json:"exchangeId"`          // 对话交换ID
	Question            string                 `json:"question"`            // 问题内容
	Answer              string                 `json:"answer"`              // 回答内容
	ThinkingSteps       []string               `json:"thinkingSteps"`       // 思维步骤列表
	References          []*SearchReferenceResp `json:"references"`          // 检索引用列表
	Recommendations     []string               `json:"recommendations"`     // 推荐问题列表
	UsedTools           []string               `json:"usedTools"`           // 使用工具列表
	DebugTrace          *ChatDebugTraceResp    `json:"debugTrace"`          // 调试轨迹
	Status              int                    `json:"status"`              // 对话状态
	ErrorMessage        string                 `json:"errorMessage"`        // 错误信息
	FirstResponseTimeMs int64                  `json:"firstResponseTimeMs"` // 首次响应时间毫秒
	TotalResponseTimeMs int64                  `json:"totalResponseTimeMs"` // 总响应时间毫秒
	CreateTime          string                 `json:"createTime"`          // 创建时间
	UpdateTime          string                 `json:"updateTime"`          // 更新时间
}

type ConversationIdentityReq struct {
	ConversationId string `json:"conversationId"` // 会话ID
}

type ConversationItemAnchorResp struct {
	ItemIndex       int    `json:"itemIndex"`       // 项目索引
	ItemText        string `json:"itemText"`        // 项目文本
	StructureNodeId int64  `json:"structureNodeId"` // 结构节点ID
	CanonicalPath   string `json:"canonicalPath"`   // 规范路径
}

type ConversationMemorySummaryResp struct {
	ConversationId string `json:"conversationId"` // 会话ID
	Summary        string `json:"summary"`        // 摘要内容
}

type ConversationResetResp struct {
	Success bool `json:"success"` // 是否成功
}

type ConversationSessionListReq struct {
	PageNo   int    `json:"pageNo,optional,default=1"`    // 页码
	PageSize int    `json:"pageSize,optional,default=10"` // 每页大小
	Keyword  string `json:"keyword,optional"`             // 关键词
}

type ConversationSessionListResp struct {
	PageNo   int                        `json:"pageNo"`   // 页码
	PageSize int                        `json:"pageSize"` // 每页大小
	Total    int64                      `json:"total"`    // 总记录数
	Records  []*ConversationSessionResp `json:"records"`  // 会话列表
}

type ConversationSessionResp struct {
	ConversationId string `json:"conversationId"` // 会话ID
	Title          string `json:"title"`          // 会话标题
	LatestMessage  string `json:"latestMessage"`  // 最新消息
	CreateTime     string `json:"createTime"`     // 创建时间
	UpdateTime     string `json:"updateTime"`     // 更新时间
}

type ConversationStopResp struct {
	Success bool `json:"success"` // 是否成功
}

type ConversationStructureAnchorResp struct {
	RootSectionCode   string `json:"rootSectionCode"`   // 根章节代码
	RootSectionTitle  string `json:"rootSectionTitle"`  // 根章节标题
	TargetSectionHint string `json:"targetSectionHint"` // 目标章节提示
	StructureNodeId   int64  `json:"structureNodeId"`   // 结构节点ID
	CanonicalPath     string `json:"canonicalPath"`     // 规范路径
	ScopeMode         string `json:"scopeMode"`         // 范围模式
}

type ConversationTraceStageResp struct {
	StageId       int64  `json:"stageId"`       // 阶段ID
	TraceId       string `json:"traceId"`       // 追踪ID
	StageCode     string `json:"stageCode"`     // 阶段代码
	StageName     string `json:"stageName"`     // 阶段名称
	StageOrder    int    `json:"stageOrder"`    // 阶段顺序
	StageLevel    int    `json:"stageLevel"`    // 阶段层级
	ParentStageId int64  `json:"parentStageId"` // 父阶段ID
	ExecutionMode string `json:"executionMode"` // 执行模式
	StageState    string `json:"stageState"`    // 阶段状态
	StartTime     string `json:"startTime"`     // 开始时间
	EndTime       string `json:"endTime"`       // 结束时间
	DurationMs    int64  `json:"durationMs"`    // 持续时间毫秒
	SummaryText   string `json:"summaryText"`   // 摘要文本
	ErrorMessage  string `json:"errorMessage"`  // 错误信息
	Snapshot      string `json:"snapshot"`      // 快照数据
}

type DocumentNavigationDecisionResp struct {
	NavigationAction  string                           `json:"navigationAction"`  // 导航动作
	ExecutionMode     string                           `json:"executionMode"`     // 执行模式
	StructureAnchor   *ConversationStructureAnchorResp `json:"structureAnchor"`   // 结构锚点
	ItemAnchor        *ConversationItemAnchorResp      `json:"itemAnchor"`        // 项目锚点
	RetrievalPlan     *RetrievalQuestionPlanResp       `json:"retrievalPlan"`     // 检索问题计划
	SummaryText       string                           `json:"summaryText"`       // 摘要文本
	QueryContextHints []string                         `json:"queryContextHints"` // 查询上下文提示
	SoftSectionHints  []string                         `json:"softSectionHints"`  // 软章节提示
}

type KnowledgeDocumentOptionResp struct {
	DocumentId   int64  `json:"documentId"`   // 文档ID
	DocumentName string `json:"documentName"` // 文档名称
}

type RetrievalObserveReq struct {
	ConversationId string `json:"conversationId"` // 会话ID
	ExchangeId     string `json:"exchangeId"`     // 对话ID
}

type RetrievalQuestionPlanResp struct {
	RetrievalQuestion string   `json:"retrievalQuestion"` // 检索问题
	SubQuestions      []string `json:"subQuestions"`      // 子问题列表
}

type RetrievalResultResp struct {
	RetrievalId  int64  `json:"retrievalId"`  // 检索ID
	DocumentId   int64  `json:"documentId"`   // 文档ID
	DocumentName string `json:"documentName"` // 文档名称
	Content      string `json:"content"`      // 检索内容
	Score        string `json:"score"`        // 相似度分数
}

type SearchReferenceResp struct {
	ReferenceId        string  `json:"referenceId"`        // 引用ID
	SourceType         string  `json:"sourceType"`         // 来源类型
	Title              string  `json:"title"`              // 标题
	Url                string  `json:"url"`                // URL
	Snippet            string  `json:"snippet"`            // 片段
	DocumentId         int64   `json:"documentId"`         // 文档ID
	DocumentName       string  `json:"documentName"`       // 文档名称
	ChunkId            int64   `json:"chunkId"`            // 块ID
	ParentBlockId      int64   `json:"parentBlockId"`      // 父块ID
	ParentBlockNo      int     `json:"parentBlockNo"`      // 父块序号
	ChunkNo            int     `json:"chunkNo"`            // 块序号
	SectionPath        string  `json:"sectionPath"`        // 章节路径
	StructureNodeId    int64   `json:"structureNodeId"`    // 结构节点ID
	StructureNodeType  int     `json:"structureNodeType"`  // 结构节点类型
	CanonicalPath      string  `json:"canonicalPath"`      // 规范路径
	ItemIndex          int     `json:"itemIndex"`          // 项索引
	Score              float64 `json:"score"`              // 相似度分数
	SubQuestionIndex   int     `json:"subQuestionIndex"`   // 子问题索引
	SubQuestion        string  `json:"subQuestion"`        // 子问题
	Channel            string  `json:"channel"`            // 渠道
	ToolName           string  `json:"toolName"`           // 工具名称
	KnowledgeScopeCode string  `json:"knowledgeScopeCode"` // 知识范围代码
	KnowledgeScopeName string  `json:"knowledgeScopeName"` // 知识范围名称
}

type StageBenchmarkResp struct {
	StageName string `json:"stageName"` // 阶段名称
	Benchmark string `json:"benchmark"` // 基准值
}
