package errorx

import "github.com/swiftbit/know-agent/common"

var (
	ErrDocumentNotFound         = common.NewBizError(20001, "文档不存在：%d")
	ErrUnsupportedFileType      = common.NewBizError(20002, "暂不支持文件类型: %s")
	ErrEmptyFileContent         = common.NewBizError(20003, "文件内容为空：%s")
	ErrDocumentStatusInvalid    = common.NewBizError(20004, "文档状态无效：%s")
	ErrDocumentProfileNotFound  = common.NewBizError(20005, "文档属性不存在")
	ErrStrategyPlanNotFound     = common.NewBizError(20006, "策略方案不存在：%d")
	ErrStrategyStepEmpty        = common.NewBizError(20007, "当前没有可执行的策略步骤")
	ErrIndexTaskRunning         = common.NewBizError(20008, "当前文档已有索引任务正在执行")
	ErrMQSendFailed             = common.NewBizError(20009, "异步任务投递失败：%s")
	ErrDocumentParseFailed      = common.NewBizError(20010, "文件解析失败：%s")
	ErrDocumentStorageFailed    = common.NewBizError(20011, "文件存储失败：%s")
	ErrGraphRagBuildFailed      = common.NewBizError(20012, "GraphRag 已构建失败")
	ErrDocumentVectorFailed     = common.NewBizError(20013, "向量化处理失败：%s")
	ErrDocumentIndexUnavailable = common.NewBizError(20014, "文档当前没有可用索引：%s")
	ErrDocumentRetrieveEmpty    = common.NewBizError(20015, "未检索到可用资料：%s")
	ErrTaskNotFound             = common.NewBizError(20016, "任务不存在：%d")
	ErrParentBlockMissing       = common.NewBizError(20017, "当前方案缺少父块流水线，无法生成 Parent-Child 结构")
	ErrChildBlockMissing        = common.NewBizError(20018, "当前方案缺少子块流水线，无法生成 Parent-Child 结构")
	ErrDocumentBlocksMissing    = common.NewBizError(20019, "当前文档没有可用于切块的结构化 blocks")
	ErrDistributedLockNotFound  = common.NewBizError(20020, "分布式锁[%s]不存在")
	ErrSessionNotFound          = common.NewBizError(20021, "会话不存在: %d")
	ErrExchangeNotFound         = common.NewBizError(20022, "对话记录不存在: %d")
	ErrKnowledgeBaseNotFound    = common.NewBizError(20023, "知识库不存在: %d")
	ErrSessionRunning           = common.NewBizError(20024, "该会话当前正在执行中，请稍后再试")
	ErrKnowledgeBaseDisabled    = common.NewBizError(20025, "知识库不存在或已停用: %d")
	ErrKnowledgeBaseMissing     = common.NewBizError(20026, "请选择至少一个知识库")
)
